### PR TITLE
moths can open their wings

### PR DESCRIPTION
**Pull request by red031000**
## About The Pull Request

Moths can now open their wings
partial port from yogstation13/Yogstation#11040

in addition, adjust the timings for flap and aflap to be half the time, as they did not seem fast enough

## Why It's Good For The Game

looks beautiful, adds flavour to moths

## Changelog
:cl:
add: Add the ability for moths to open their wings
tweak: Change time for flap and aflap to half
imageadd: Add moth wings open images from yogstation
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
How do moths open their wings?

**Comment by red031000** [comment]
through the *wings emote, *flap and *aflap have animated wing opening as well

**Comment by red031000** [comment]
closing for now, as this has been ported upstream, will re-open if it gets rejected from there

**Comment by red031000** [comment]
reopening due to creative differences upstream, may be resolved, however I am operating under the assumption that it will not be

**Comment by Karmic-Skink** [comment]
Ditto with upstream.
Sprites are far too large for default species behavior.
Also tall poppy syndrome.

**Comment by red031000** [comment]
reopening here was partly because I had asked upstream on how to proceed but in the end got no consensus or response other than half saying they love the sprites and the other half saying they hate it, hoping to get something a bit more than that, if necessary sprites can be changed but imo they do need to be proportionate, another option is restricting when the sprites can be used, which can also happen with discussion, I just need to know *what* is preferable, which I just didn't get upstream

**Comment by TheFakeElon** [comment]
the wings are very big

**Comment by red031000** [comment]
closing to make a proper port from upstream

**Pull request closed without merging**
