### PR TITLE
Removes SS_TICKER From SSLighting

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

Full credit to https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11848.

## Why It's Good For The Game

Optimisation change resulting in the lighting processing being done in one big bulk of usage (but way faster processing) rather than being throttled. 
## Changelog
:cl:
tweak: Removed SS_TICKER from lighting subsystem to hopefully increase performance.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
I'd prefer to keep an eye on Upstream's testing of this, as it seems to cause inconsistent behavior.

**Comment by francinum** [comment]
May cause issues if there are constant, large updates, otherwise I don't see major issues with this,

**Comment by francinum** [comment]
Part of me believes that this will only end poorly.

**Comment by Jalleo** [comment]
This PR is going to be revisited at a later date as there are apparently issues with it at this time.

**Pull request closed without merging**
