### PR TITLE
New Hammerhead medbay, removal of arms depot, disposals to brig

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request

This pull request reworks Hammerhead medbay. See mapdiffs to see changes.
Also apparently this PR removes Arms Depot, placing HoS office into brig and moving MaA office close to hangar.

## Why It's Good For The Game

less awful mapping = more happy players
"""slight changes""" to disposals system, too.
Tested, worked. Should continue working.

## Changelog
:cl:
tweak: Hammerhead medbay has been redesigned.
rscdel: Hammerhead Arms Depot is no more! MaA office is now in hangar, HoS and execution room in brig and ferry dock is in evacuation hallway.

/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
I have no idea what's the problem and how to fix it.

**Comment by Kmc2000** [comment]
Heyo, the zebra landmarks are unecessary for windows, as they already spawn there.

**Comment by Kmc2000** [comment]
That green console to the far left, with the IVs in it, will severely impede traffic. I'd recommend shoving it on the top left corner of that little 2x2 hallway, so people don't get blocked by it

**Comment by Firefox13** [comment]
> 
> 
> Heyo, the zebra landmarks are unecessary for windows, as they already spawn there.

Zebra landmarks?

**Comment by Vasily2013** [comment]
ALRIGHT, let's do this... 

- [] Move the air alarm that's on the paramedic door to somewhere else.
- [] Put a firelock (directional or full tile) on the chemistry desks and (assuming the chem dispensers are on open turfs) under those as well.
- [] Add some red floor decals inside the sec office, it makes it look a little better. 
- [] There are a lot of roller beds around. I'd suggest replacing the two by the main door with some chairs, then move the IV drip there into surgery.
- [] Add some chairs to the medbay lobby. I'ts REALLY tiny considering the ship's size. 

We'll start with that, that's what I can see on mapdifbot. Once those fixes are in i'll actually open the map and take a look.

**Comment by Firefox13** [comment]
>     * [ ]  Move the air alarm that's on the paramedic door to somewhere else.

Done

>     * [ ]  Put a firelock (directional or full tile) on the chemistry desks and (assuming the chem dispensers are on open turfs) under those as well.

Smartfridges are on wall turfs. As for tables, done.

>     * [ ]  Add some red floor decals inside the sec office, it makes it look a little better.

Made it a little bit shorter, like the other sec offices.

>     * [ ]  There are a lot of roller beds around. I'd suggest replacing the two by the main door with some chairs, then move the IV drip there into surgery.

Done.

>     * [ ]  Add some chairs to the medbay lobby. It's REALLY tiny considering the ship's size.

Took a bite from sec checkpoint size, made the lobby a little bigger.

**Comment by Cenrus** [comment]
I noticed the centcom ferry shuttle dock is gone, where has it been relocated?

**Comment by Firefox13** [comment]
>     * [ ]  Ensure that the ferry shuttle works, and has sufficient space to exit into a public hallway.
> 
> I noticed the centcom ferry shuttle dock is gone, where has it been relocated?



Added in emergency hallway.


>     * [x]  You've deleeted the master at arms office, please ensure that a new one is placed.

Hangar.


>     * [ ]  The 3x3 random maint room's south door is not compliant with door placement for 3x3 random maint rooms.

Adjusted accordingly.

**Comment by Firefox13** [comment]
Grug has limited brain capacity.
Grug deletes his builds folder and makes it again.
Grug also makes a new PR thing again, too.
Please stand by.

**Pull request closed without merging**
