### PR TITLE
Adds sprites for burnt nsv floors and cleans up unneeded base code changes [Ready]

### LINKED ISSUE #820: Bad icon_state icon combination: Monogrid tiles.
## Round ID:
766

## Testmerges:
#814: 'Autofire that isn't objectively terrible. We truly live in a society.' by Kmc2000 at commit a9beb05543
#818: 'Okay but what if you could just build constrictors and they'd connect to pipes' by Bokkiewokkie at commit a6aaf4ef4d
#819: 'NSV Pegasus - The battleship' by Kmc2000 at commit 3d2e7b9bfb

## Reproduction:
Spawn a room of `/turf/open/floor/plasteel/grid/mono`

Set it on fire.

### Reason
(E) (C) (M) icon = /icon (nsv13/icons/turf/floors.dmi)

icon_state = "floorscorched1"
icon_state = "floorscorched2"
burnt_state list contains invalid iconstates.
```
(E) (C) (M) burnt_states = /list (2)
1 = "floorscorched1"
2 = "floorscorched2"
```

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request
Monotiles got merged upstream so I removed their //nsv13 tags together with the stuff in floors.dmi that we already had in the nsv13 folder.

fixes #820 

## Changelog
:cl:
add: Added burnt durasteel floor sprites
/:cl:

preview of a few burned tiles idk why you'd need it but here it is
image

### CODE REVIEW

**Comment by francinum** [comment]
Can we get ingame pictures of things working?

**Comment by Bokkiewokkie** [comment]
Here's a picture of em in the wild. (after a plasmafire)
image

**Comment by Bokkiewokkie** [comment]
got one more update for this coming up with a ton more progressively burnt ones so hold off on merge til that comes through

**Comment by francinum** [comment]
Aye.

**Comment by Bokkiewokkie** [comment]
the "burnt floor 3.3" commit was actually the one that added it but for some reason it showed up before my message in the timeline so uh, it should be ready. (Also Travis encountered some runtimes but idk what that error actually was so if you do please tell me)

**Comment by Bokkiewokkie** [comment]
hnnnnng merge conflicts

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
