### PR TITLE
update auxmos to 2.2.2 and byond to 514.1589

### PR DESCRIPTION
**Pull request by red031000**
## About The Pull Request

ports BeeStation/BeeStation-Hornet#7959

needs extensive testing, may also need BeeStation/BeeStation-Hornet#8264 ported to work properly, unsure

## Why It's Good For The Game

(theoretically) faster atmos, and 1589 support, should fix issues with 1589 as well

## Changelog
:cl:
server: Bumps auxmos to 2.2.2
server: Bumps the maximum BYOND version to 514.1589
/:cl:

### CODE REVIEW

**Comment by red031000** [comment]
I'll update it tonight when I get home

**Comment by covertcorvid** [comment]
Right now it seems like explosive decompression's working but the firelocks aren't automatically closing in response to the pressure change.

**Comment by covertcorvid** [comment]
plasma

**Comment by covertcorvid** [comment]
github no that was just a comment

**Comment by covertcorvid** [comment]
Added adjacency updates from https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15864 to get the hooks for border firedoors to trigger

**Comment by covertcorvid** [comment]
Okay, the Tycoon ceiling is just the result of an optimization DeltaFire made that reduces the total number of turfs we'll try to process at once for lag reasons. So that's working as intended.

**Review by covertcorvid — APPROVED** [review]
Initial testing looks good.

**Review by Bokkiewokkie — APPROVED** [review]
Code looks good 👍

**Pull request merged**
