### PR TITLE
[PORT] Flavor Texts/Flavour Text

### PR DESCRIPTION
**Pull request by Bobbanz1**
## About The Pull Request
Ports the following PRs from various sources:
* Beestation: https://github.com/BeeStation/BeeStation-Hornet/pull/2472
* Whitesands: https://github.com/Whitesands13/Whitesands/pull/491

## Why It's Good For The Game
Flavor Text is good for roleplaying as it shows character appearances and minor roleplay quirks!

## Changelog
:cl:
add: Flavortext can now be set to be shown to anyone who examines you.
fix: Clicking the "cancel" button will no longer reset your flavor text to nothing.
/:cl:

### CODE REVIEW

**Comment by Bobbanz1** [comment]
To answer the questions some might have about this feature.

1. Is it mandatory to fill in the flavor text?

No it’s not mandatory (required) to fill in the flavor text in order to be allowed to join the round. It’s purely optional. 

2. Can you port this to Beestation?

As I’d like to point out, they tried to port it once and then the OP (Original Poster) closed the PR, I’d also like to point out that theirs wouldn’t have been saved to the player’s save file as they had forgotten to give the code the ability to read the save file and import the saved flavor text. 

3. Can you change the text mid-round?

No, I don’t know what magic I’d have to pull off in order to make the code capable of doing that.

**Comment by Bokkiewokkie** [comment]
I can't wait to have to refactor this to work with the upcoming preferences update!

**Comment by Bobbanz1** [comment]
> I can't wait to have to refactor this to work with the upcoming preferences update! (If you can update it to work on the latest Beestation version that would be greatly appreciated)
@Bokkiewokkie I'll have to figure out how their new preference system works before I can give a definitive answer, but probably yes.

**Comment by Bokkiewokkie** [comment]
Note: will need to update the database schema accordingly

**Comment by Bobbanz1** [comment]
> Note: will need to update the database schema accordingly

Could you explain?

**Comment by Bokkiewokkie** [comment]
> > Note: will need to update the database schema accordingly
> 
> Could you explain?

I was under the impression flavor text was a seperate character variable, though after looking at it I realized it isn't. I think it's best if we do make it one.

**Review by covertcorvid — APPROVED** [review]

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
