### PR TITLE
Galactica fixes

### PR DESCRIPTION
**Pull request by Pontenerd**
## About The Pull Request

fixes some bugs I had reported to me, and one from #1444 

## Why It's Good For The Game

fix mna good

## Changelog
:cl:
add: wires to robo's office, allowing for power
tweak: swapped control room and CE office
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
Do note I have not tested this yet as it is late and I am about to go to bed, will correct test and correct potential issues when I get home tomorrow

**Comment by Karmic-Skink** [comment]
> Do note I have not tested this yet as it is late and I am about to go to bed, will correct test and correct potential issues when I get home tomorrow

Please ensure you test before you make PRs. Being tired isn't a good excuse, in future; just push to your branch and wait if it is late.

**Comment by Vasily2013** [comment]
Is this still a draft, or is it ready?

**Comment by Vasily2013** [comment]
closing as stale and redundant.

**Pull request closed without merging**
