### PR TITLE
[Map] NSV Galactica... 3 + Ship combat reworks!

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

* The following rebalances are in:
* Flak is back, but weaker. It's a decent defensive screen for larger, less maneuverable ships
* Torps & missiles have been merged. You can make torps with the missile factory, and fire torps from the VLS
* The VLS is now gunner aimed. You can still set it to autofire if you so wish
* 50cal has been nerfed to have less armour pen, but has received a damage buff to compensate
* NACs have been buffed, the UI reworked, and a new shell type added: homing
* Ramming is now in! Larger ships can decimate fighters by ramming them, sweep aside your enemies with the force of many millions of tonnes of ship.

Credit to Tetrazeta for the cool NT earth logo that appears in the map!

NSV Galactica is an out an out battleship. You won't find any speed, manueverability, or grace here. Only guns.
The flagship of the Nanotrasen fleet, it's filled with NT's most advanced weapons research to date.

Experimental:
* NT has been experimenting with shield technology... try out the defense screen reactor

image

image

## Why It's Good For The Game

WIP

## Changelog
:cl: Kmc2000 with Bokkiewokkie, Aerwhisp & Karmic Skink
add: NSV Galactica has been redesigned! It's an all out battleship, trading any maneuverability for crushing firepower
add: Torpedoes now use the VLS system
add: Nanotrasen is experimenting with shield tech... Try it out on our newest map, Galactica
add: Ramming is now in! Larger ships can plow through hoardes of fighters, but watch out for hull damage!
tweak: NACs have been buffed and the UI tweaked to be more useful
tweak: VLS is now gunner aimed. Autofire functionality still exists if you so choose to use it

/:cl:

### CODE REVIEW

**Comment by TheKillerbot09** [comment]
- Ce's office lacks any scrubbers or vents
- A cell charger in the engineering locker room would be nice

**Comment by SerynEngi** [comment]
CE first test round. Initial thoughts. 
Coolant lines for the AGCNR are given insufficient gas to actually work, and their inputs are extremely far from the active points. 
There is also not any way to vent the coolant, fuel or nucleum lines safely. 
Signage for evac or even towards the main passageways would be appreciated.
The CE office does actually need standard distro and reclaimation.
There is no point in connecting anything other than plasma or O2 to the fuel lines, as they don't benefit as much and just eat time.

**Comment by SerynEngi** [comment]
Another note. It would be nice to have a separate place to fire cargo torps when people load the VLS so i dont have to either unload 15 missiles or fire them.

**Comment by Kmc2000** [comment]
> * Ce's office lacks any scrubbers or vents
> * A cell charger in the engineering locker room would be nice
> * Tcomms seems to be lacking a NT Net relay for the modular computers
> * A hole in the floor, in maintenance behind the morgue

I can't find this hole in the floor of which you speak, can you elaborate?

**Comment by TheKillerbot09** [comment]
> > * Ce's office lacks any scrubbers or vents
> > * A cell charger in the engineering locker room would be nice
> > * Tcomms seems to be lacking a NT Net relay for the modular computers
> > * A hole in the floor, in maintenance behind the morgue
> 
> I can't find this hole in the floor of which you speak, can you elaborate?
It's up the stairs inside medical, just right a tile or two from the top of the stairs

**Comment by Kmc2000** [comment]
> > > * Ce's office lacks any scrubbers or vents
> > > * A cell charger in the engineering locker room would be nice
> > > * Tcomms seems to be lacking a NT Net relay for the modular computers
> > > * A hole in the floor, in maintenance behind the morgue
> > 
> > 
> > I can't find this hole in the floor of which you speak, can you elaborate?
> > It's up the stairs inside medical, just right a tile or two from the top of the stairs

Oh wow so it is!

**Comment by Grabovvski** [comment]
One complain that I have about ramming, any cool it is, is that it is either
a) way too easy to gain speed, making accidental rammings very damaging for both you and the enemy
b) ramming deals too much damage to your ship - albeit it was the Galactica, so it may be tied to the ship itself
One of these caused us to hit Czanek Corp shipyards, and go into SSCrit

**Comment by Jeff-jefferson-jeffery** [comment]
imo if youre going to keep the insane missile tracking, speed up 50 cal projectiles and give someone in CIC access to one so they can shoot down missiles
this is because you basically cannot dodge them - multiple times i would sidestep a nuke as a pilot only to have it 180 and hit me regardless

**Comment by bluey89962** [comment]
CMO's office doesn't seem to have the thingy to make announcements

**Comment by TheKillerbot09** [comment]
- Lack of a prototype hardsuit?
- No R&D console near the Exosuit fabs to update them.

**Comment by bluey89962** [comment]
A few more notes about medbay:
-It has no sinks even though SOP states that we should clean hands and tools before surgery 
-You can't reach all the machines from the left spot in chem, I'd suggest moving it one tile to the left and making the center table 4 tiles wide 
image
-The treatment room feels a little... empty and the machines seem a tad too close together. It has a little too much open space, it's odd. I don't know what I'd do with it but I might think of something later
image

**Comment by MacBlaze1** [comment]
It is practically impossible to run the PDSR without causing emission because it doesnt ever cool down except through coolant cycling, and you can only do that every 60 seconds. Not to Mention it is quite hard to keep containment up to prevent emission because of the temperature among other things.

**Comment by jonathan123700** [comment]
there is no cryo on the ship

**Comment by Florbman** [comment]
The Bridge needs a safe for the captains's spare

**Comment by TheKillerbot09** [comment]
GalacticaBug
This door connecting xenobio the the main hallway can't be accessed by either a scientist or the RD.

**Comment by Bokkiewokkie** [comment]
> @Kmc2000 Stop it. Get some help.
> https://user-images.githubusercontent.com/22532898/119454440-c7cc5a80-bcf5-11eb-96cf-a39e06cb3856.mp4

I did that one :), I'll make sure to fix it by putting a console that has density 1 under the camera console :).

**Comment by Kmc2000** [comment]
Merging to allow work on boarding branch. Subsequent bug fixes can be pushed separately :)

**Pull request merged**
