### PR TITLE
Balatant FTL Buffs

### PR DESCRIPTION
**Pull request by Cenrus**
FTL works faster now and automatically spools after each use.

## Why it's good for the game

Auto spooling removes the need to stop whatever you're doing, run all the way to the FTL drive, and press a single button.

As Starmap 2 has made the universe bigger, It now takes less time to travel between systems, It took the crew around an hour to even reach combat on the first shift.

These changes hope to improve the quality of current rounds and get the ship into action faster so that pilots, bridge assistants and munitions can do their thing without as much needless waiting. Auto spooling can safely be removed when the FTL drive update comes, but it could be some time until it's finished.

### CODE REVIEW

**Comment by theboy6545** [comment]
speedmerge this shit

**Comment by Kmc2000** [comment]
I'm not really against this, tbh, but want it testmerged beforehand

**Comment by francinum** [comment]
you *shouldn't* be running all the way across the ship. you *should* be telling engineering to do it for you.

**Comment by Cenrus** [comment]
Asking over common is usually my first option, but if it doesn't happen I do it myself. Engineers tend to be busy fixing breaches, and hate needing to run back to their department to spool it.

**Comment by Vivalas** [comment]
inb4 astrogation department

**Comment by Autisem** [comment]
Engineers usualy are buzzy too though, especialy with limited crew size having engineers drop everything to flip a switch is pretty annoying

**Comment by Karmic-Skink** [comment]
Disagree with auto spool.

**Comment by Kmc2000** [comment]
I'm doing an FTL buff on the PVP branch, thanks for the submission anyway!

**Pull request closed without merging**
