### PR TITLE
Post Tortilla Shrike Update

### PR DESCRIPTION
**Pull request by Karmic-Skink**
## About The Pull Request
This PR addresses a couple issues with Shrike and Lazy Lifts

## Why It's Good For The Game
Shrike is objectively the worst map ever, so its not good for the game.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: Shuffled Shrike Cargo Crates
add: Added Processor Board to Shrike Tech Storage
add: Added Generic Vendor Board to Shrike Tech Storage
fix: Fixed damaged sections of Shrike maint having incorrect turfs
fix: Moved errant light in Shrike mining maint
tweak: Silenced the Shrike cargo lift
add: Added Cargo Shuttle Timer to Shrike cargo lift
tweak: Lazylift Blast Doors will now automatically open when the lift arrives, and stay open
add: Added block out in space to catch the ejected SM on Shrike
/:cl:

### CODE REVIEW

**Comment by Kenionatus** [comment]
I think the Lazylift change should be its own PR. It looks to me like a map independent change that's only mildly related to the other ones, which are all Shrike specific.

**Comment by Karmic-Skink** [comment]
> I think the Lazylift change should be its own PR. It looks to me like a map independent change that's only mildly related to the other ones, which are all Shrike specific.

This fix is specific to the doors that get used in this map.

**Comment by williamcll** [comment]
Will this fix how sometimes cargo gets randomly spaced because the doors don't close on their own?

**Comment by covertcorvid** [comment]
> Will this fix how sometimes cargo gets randomly spaced because the doors don't close on their own?

Can you specify which doors you mean? The elevator doors should now animate correctly and close properly. The blast shutters in front of the cargo shuttle are operated by a button.

**Pull request merged**
