### PR TITLE
Start amount TC is now set to 25

### PR DESCRIPTION
**Pull request by GoatMonarch**
## About The Pull Request
Increased the starting amount of TC, and balanced 20TC cost objects around it. (It hurt increasing clown car costs)
Random kits box kits were left at 20 TC, so you can customize it slightly with 5TC.
Surplus crate cost was increased, since it does not follow a gimmick set.
Romerol was increased to 30 from 25.

## Why It's Good For The Game
In short, security's two disarm instant stun and constraints are kind of strong. You can't counter it like you would someone with a stunbaton, or gun.
Balacing around TC amount is a first go-to for bettering how traitors are handling themselves, and it's always possible to tweak it around the numbers, rather than implementing code bloat, or more item bloat for the uplink.

## Changelog
:cl:
tweak: Traitors now start the shift with 25 tc!
tweak: contractor kit is now 25 tc
tweak: ancient jumpsuit is now 25 tc
tweak: surplus crate is now 25 tc
tweak: clown car is now 25 tc
tweak: his grace is now 25 tc
tweak: chaplain cult kit is now 25 tc
tweak: syndie baloon is now 25 tc
tweak: romerol now costs 30 tc
/:cl:

### CODE REVIEW

**Comment by WhyIsCaeciliusTaken** [comment]
Reduce clown car to 20 because there are like 3 or 4 hardcounters, one of which is inherent to everyone roundstart.

**Comment by GoatMonarch** [comment]
> Reduce clown car to 20 because there are like 3 or 4 hardcounters, one of which is inherent to everyone roundstart.

I'll mayhaps look into geting the clown car fix from beestation first. This is not really about balancing traitor items, I may do a PR simmilar to [this Beestation PR](https://github.com/BeeStation/BeeStation-Hornet/pull/1703) in the future, if this is merged.

**Comment by BeloneX** [comment]
BeeStation/BeeStation-Hornet/pull/2078

**Comment by GoatMonarch** [comment]
> [BeeStation/BeeStation-Hornet/pull/2078](https://github.com/BeeStation/BeeStation-Hornet/pull/2078)

In reference to this, seems like Bee is going to pass the vote. _I ma just PR it a little earlier than usual tho._

**Comment by eLeCtrOssSnake** [comment]
Why?

**Comment by francinum** [comment]
This is a bit more of a delicate issue than just adding more money.

**Pull request closed without merging**
