### PR TITLE
Adds the design disk for railgun ammo to the prototype fighter

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request
Does what it says

## Why It's Good For The Game
Being able to make ammo for your gun makes it a lot more useful.

## Changelog
:cl:
balance: Prototype fighters now come with railgun ammo blueprints
/:cl:

### CODE REVIEW

**Review by Karmic-Skink — DISMISSED** [review]
This weapon is stupid.

**Review by DeltaFire15 — CHANGES_REQUESTED** [review]
Uh... Are you *sure* you want to put a design disk in the *Fighters'* components (aka the installed equipment)? It should be seperate, not in a var of the fighter.

**Comment by Karmic-Skink** [comment]
> Uh... Are you _sure_ you want to put a design disk in the _Fighters'_ components (aka the installed equipment)? It should be seperate, not in a var of the fighter.

It is effectively sitting as a disk inside the fighter that can be removed in maint mode.

**Comment by TheFakeElon** [comment]
Delta is right. The smallcraft component list is not designed to hold arbitrary contents

**Comment by TheFakeElon** [comment]
Code example
image
anything craft with non-component type "components" will runtime on initialization (and very likely elsewhere too)

**Comment by Karmic-Skink** [comment]
vOv superiority fighter is obsolete anyway

**Comment by Bokkiewokkie** [comment]
> Uh... Are you _sure_ you want to put a design disk in the _Fighters'_ components (aka the installed equipment)? It should be seperate, not in a var of the fighter.

My bad I thought that was the list of items sold by the trader item (I just looked at the first list I saw like a dumbass)

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
