### PR TITLE
[Map update] Eclipse newnitions upgrade.

### PR DESCRIPTION
**Pull request by Ansome101**
## About The Pull Request
Brings the Eclipse up to Newnitions standards by removing all of the old weapons, replacing them with 4 pompom turrets and 2 deck guns, adds a roof Z-level, and changes the sprite of the Eclipse to the new Kestrel sprite.

## Why It's Good For The Game
Returns the Eclipse to the game for low/deadpop operations, allowing the crew to once again complete patrols at a minimum of 3 pop.

## Changelog
:cl:
add: Added one new deck, 4 pompom turrets, and 2 deck guns.
del: Removed the legacy weapons aboard the ship
tweak: Rerouted maintenance and moved some parts of the map to compensate the space required for the new weapons.
code: Added a new "airless" variant of the pure black tile for the Eclipse's paintjob.
/:cl:

### CODE REVIEW

**Comment by Ansome101** [comment]
Eclipseplusphoto
Eclipseplusphoto2

Yeah, I know, that top deck looks god awful. Duly note, however, that it was either an ugly top deck or an entirely pointless basement level. I did my best but mind you, I had a time limit to get this thing out, we can't stay on Jeppison forever on lowpop!

**Comment by Kmc2000** [comment]
I actually really like that roof deck design, just ensure it’s airless turf’d!

**Comment by Ansome101** [comment]
> I actually really like that roof deck design, just ensure it’s airless turf’d!

I added the airless variant of the black tiles just for that concern.

**Comment by Vasily2013** [comment]
Active turfs on current variant.
image
image
image
image
image
image

Test Areas 
image

**Comment by Vasily2013** [comment]
MERGE CONFLICTS

**Review by Kmc2000 — APPROVED** [review]

**Review by Vasily2013 — APPROVED** [review]
I'll make a follow on to clean some things up.

**Pull request merged**
