### PR TITLE
[WIP] Automation 101

### PR DESCRIPTION
**Pull request by Bobbanz1**
## About The Pull Request
Sprites pulled from the following PRs: 
[Skyrat-SS13/Skyrat-tg/pull/10267](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10267) 
[Skyrat-SS13/Skyrat-tg/pull/8959](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8959) 

Ports the Conveyor Belt Sorter from Skyrat: [Skyrat-SS13/Skyrat-tg/pull/8790](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8790) 

Also adds a new object and item, the Conveyor Belt Splitter, this device is capable of splitting an input into one direction, two directions or three directions! 

This PR is dependent on one other PR: [BeeStation/NSV13/pull/1965](https://github.com/BeeStation/NSV13/pull/1965) 

## Why It's Good For The Game
Automation of sorting and conveyor buggery

## Changelog
:cl:
add: Added the Conveyor Splitter, this device is capable of splitting inputs into either one direction, two directions or three directions! 
add: Added the Conveyor Sorter, this object is capable of sorting out whatever you tell it to sort out from a conveyor belt!
/:cl:

### CODE REVIEW

**Comment by sunofang** [comment]
Automation my beloved.

**Comment by Karmic-Skink** [comment]
What are the intended or perceived use cases for this?

**Comment by Bobbanz1** [comment]
@Karmic-Skink 
It would be used by both Cargo and Munitions. 

The splitter specifically would be used by Munitions to…probably split a line of gunpowder onto 3 new conveyor belts to allow an easier time of feeding the gunpowder slot thingies. 

The Sorter would primarily be used by Cargo and possibly Munitions to sort out crates/shells/gunpowder from conveyor lines.

**Comment by Karmic-Skink** [comment]
> @Karmic-Skink It would be used by both Cargo and Munitions.
> 
> The splitter specifically would be used by Munitions to…probably split a line of gunpowder onto 3 new conveyor belts to allow an easier time of feeding the gunpowder slot thingies.
> 
> The Sorter would primarily be used by Cargo and possibly Munitions to sort out crates/shells/gunpowder from conveyor lines.
> 
> The intended usage is to sort and split conveyor belt lines into multiple additional lines.
> 
> Additional future usage could be to allow an easier time to recycle stuff, in the event such a rework is done.

We'll see how much it ends up being used and in what manner I guess. Ideally, we don't automate player jobs out of existence or cause situations where people insist that an automation setup needs to be completed before commencing objectives.

**Comment by kiVts** [comment]
> @Karmic-Skink It would be used by both Cargo and Munitions.
> 
> The splitter specifically would be used by Munitions to…probably split a line of gunpowder onto 3 new conveyor belts to allow an easier time of feeding the gunpowder slot thingies.
> 
> The Sorter would primarily be used by Cargo and possibly Munitions to sort out crates/shells/gunpowder from conveyor lines.
> 
> The intended usage is to sort and split conveyor belt lines into multiple additional lines.
> 
> Additional future usage could be to allow an easier time to recycle stuff, in the event such a rework is done.

IMG_20220913_125823

Everyone knows where this is from

**Review by TheFakeElon — COMMENTED** [review]
Undocumented TGUI additions and uncredited port of BeeStation/BeeStation-Hornet#3366

Your PR isn't reliant on #1965 if you've included everything required from it in this PR

**Comment by Bobbanz1** [comment]
Closing this as I haven't worked on it for months and my last attempt at making it work in the way TheFakeElon wanted just resulted in the code simply ceasing to work entirely, even without making the changes, the code doesn't work in the way I want it to work and it's a literal mess of absolute chaos that fails half the time to perform what it's supposed to be doing. 

Maybe someone else will pick this up or maybe I'll give it another try in the future once I learn more about DM code, but for the foreseeable future, I'm closing it.

**Pull request closed without merging**
