### PR TITLE
Gungnir Class Battlecruiser- Initial testing

### PR DESCRIPTION
**Pull request by SerynEngi**
## Gungnir Class Battlecruiser

This ship was designed as a gun-based brawler, its tougher than the Tycoon, and much more heavily armed. It comes built with 4 NAC and 6 gauss to start with.

-NOTE: this map is not yet completely done: things filling the maintenance tunnels, lighting, cameras, elevators and detail passes have not been completed, as well as the initial coding passes to make the thing actually work.

## Why It's Good For The Game

This ship occupies a middle-ground between the massive pop required to run the Galactica, and the carrier that is the Tycoon. It is designed for a crew of around 25 (full operational) with the capacity to usefully operate with much more crew, and is almost entirely gun based.

## Notable Features

-Torpedo Gulag: make your prisoners do something useful if they want to go back to their jobs

-Xenobiology and Virology Purge: Press a button to purge the associated pens in fire, press another one to safely vent the pens.

-Weapons Department Secure Storage: Replacements for your guns may be found here, as well as a few

-Engineering Secure Storage: Toxins has been deleted on this map, toxins supplies may be found in engineering secure storage across from the CE office

-Officer Staterooms: All department heads (and the QM) have full staterooms with attached restrooms/showers

-Bridge ATC: The ATC station has been relocated to the bridge, and all functionality is available there, no more waiting for that ATC that doesn't want to show up

-Protected Hangars: both the Mining and Combat hangars are protected by a series of blast-locks consistent of blast doors that protect the inner hull at all times, these may be activated at the ATC station as well as multiple locations at the magcats

-Cargo Mail room- Quickly mail things to all departments (except for command) via a set of disposal tubes

-Cargo Yeeters- Quickly deliver things to the mail room and the cargo hold via a set of disposal tubes.

-Zaun Armaments- Armor Deterioration Grenades: 4 of these certified non-lethal grenades may be found in the armory. Be warned: they will destroy almost all machinery within their radius as well.

-Triple Redundant Power and Atmospherics: There are 3 main power and atmospherics lines leaving engineering, and no less than 6 Z-level penetrations for those lines. Interrupting power for this ship is exceedingly difficult.

https://cdn.discordapp.com/attachments/413455580988964865/983147899657527356/Gungnir1.PNG
https://cdn.discordapp.com/attachments/413455580988964865/983147899988873226/Gungnir2.PNG

### CODE REVIEW

**Comment by williamcll** [comment]
Can we have 3 NACs and 4 gausses instead.

**Comment by Karmic-Skink** [comment]
I take it we are leaving Gladius for dead.

Also, what is the intended population for this map?

**Comment by SerynEngi** [comment]
> I take it we are leaving Gladius for dead.
> 
> Also, what is the intended population for this map?
> 
> Also also, care this behavior:
> 
> > -Weapons Department Secure Storage: replacements for your guns may be found here, as well as another two sets of NAC cards that were not installed initially
> 
> We deliberately do not have this in any ship due to the tendency of crews to delay until they are all setup, amongst other things.

The Gladius is now a free project for anyone new looking at becoming a mapper, much like I started with it.

Intended population is around 20-25 for full functionality of ship. Much like the Tycoon, it is both technically operable with much less, and capable of using much more. I estimate an absolute bare minimum of 9 people to actually run the ship assuming they're in the right jobs, and it has provision to run considerably more crew and benefits from it.

If told to remove the spare NAC cards, I will do so, weapons department secure storage will remain for replacement cards for destroyed weapons.

**Comment by SerynEngi** [comment]
> Same as Tycoon, I'd suggest 25-40+ with this size.

I should clarify- it is intended for that number. If I get my way, it wont show in the rotation at anything less than 20 people.

**Comment by SerynEngi** [comment]
Closing to remake with updated branch. Will recreate when ready for experimental testing. 
Remaining Issue for full mapping functionality: Shuttle-code

**Pull request closed without merging**
