### PR TITLE
Test Fighters PR Please Don't Merge

### PR DESCRIPTION
**Pull request by Karmic-Skink**
## About The Pull Request
Fighter stuff I guess.
Use Tycoon.
Space Battle Management Console not included in this PR, which is supposed to bridge a number of gaps in the refactored comms.

## Why It's Good For The Game
If it hasn't been made clear, I haven't been actively developing this branch in quite a while. This has just been PR'd as Bokkie wanted to see the fighter content.

## Testing Photographs and Procedure

<details>
I haven't tested this in over 6 months.
</details>

## Changelog
:cl:
refactor: Refactored fighter UI
refactor: Refactored fighter startup
refactor: Refactored fighter comms
add: Added Medium Fighter
add: Added support for two seater fighters
add: Added 2x Gunship Designs
add: Added Super Gauss Cannon Weapon
add: Added Wire Guided Torp for Medium Fighter
/:cl:

### CODE REVIEW

**Comment by BlueHNT** [comment]
issues I found

- [ ] Gunship UI dead
- [ ] Gunship X and Y solidity is flipped where the length is sideways
- [ ] Gunship spawns weird tungstens which can be moved by box and knocked around, but dont show up and cannot be used
- [ ] The power monitor and FTL monitor on the gunship don't work either
- You can't boxload the gunship ammo [MIGHT BE INTENTIONAL?]

Community feature req - make wizo do more than missiles and fix the wiring
- [ ] wizo missile wiring is currently wonky and just goes as it pleases
- [ ] wizo got bored

**Comment by someone543** [comment]
Found a bug where the DRADIS on the menu cannot have zoom adjusted, or be used to hail allies.

**Comment by Karmic-Skink** [comment]
> issues I found
> 
> * [ ]  Gunship UI dead
> * [ ]  Gunship X and Y solidity is flipped where the length is sideways
> * [ ]  Gunship spawns weird tungstens which can be moved by box and knocked around, but dont show up and cannot be used
> * [ ]  The power monitor and FTL monitor on the gunship don't work either
> * You can't boxload the gunship ammo [MIGHT BE INTENTIONAL?]
> 
> Community feature req - make wizo do more than missiles and fix the wiring
> 
> * [ ]  wizo missile wiring is currently wonky and just goes as it pleases
> * [ ]  wizo got bored

Denied due referencing "wizo" instead of the true master "RIO".

**Comment by Karmic-Skink** [comment]
> Found a bug where the DRADIS on the menu cannot have zoom adjusted, or be used to hail allies.

Zoom is bug.
Hail is intentional as it was being moved to a different feature that wasn't finished.

**Comment by BlueHNT** [comment]
>
> Denied due referencing "wizo" instead of the true master "RIO".

Bruh, also adding a button for active scanning and switching between TARGETING/HAILING would make it so you don't need the dradis popup at all

**Comment by Karmic-Skink** [comment]
> > Denied due referencing "wizo" instead of the true master "RIO".
> 
> Bruh, also adding a button for active scanning and switching between TARGETING/HAILING would make it so you don't need the dradis popup at all

That UI was written before targeting was added to dradis, also read above about hailing.

**Comment by Karmic-Skink** [comment]
You win.

**Pull request closed without merging**
