### PR TITLE
Adds a QM locker to the jolly sausage

### PR DESCRIPTION
**Pull request by theboy6545**
## About The Pull Request

Adds a QM locker to the jolly sausage.

## Why It's Good For The Game
fix: #984

## Changelog
:cl:
add: adds a QM locker in the sorting room
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Remove the fix: #984 from the CL and move it up to why this is good from the game.

**Comment by francinum** [comment]
The QM spawn is mostly there as error handling if the job selection system fails to respect the removal. The QM does not exist on Sausage, and their access has been redistributed to cargo techs in general.

**Comment by theboy6545** [comment]
> The QM spawn is mostly there as error handling if the job selection system fails to respect the removal. The QM does not exist on Sausage, and their access has been redistributed to cargo techs in general.

So should i just put all the stuff on a table or a locker with CT acsess?

**Comment by francinum** [comment]
No, CTs have access to the locker if they want to elect their own QM or something, this is fine.

**Review by Vasily2013 — APPROVED** [review]
YEET

**Pull request merged**
