### PR TITLE
Adds jetpacks back to the mining vendor

### PR DESCRIPTION
**Pull request by bluey89962**
## About The Pull Request
Decided to split my last PR in two, this one is only regarding the jetpack upgrade.

## Why It's Good For The Game
quoting from the original PR:

> Bee mining is very different from NSV mining, the rebase was bound to have some changes that are unecessary in here. Jetpacks, while useless in Bee's Lavaland, are incredibly useful to fly around asteroids.

in other words jetpack make miner go :)

## Changelog
:cl:
add: Jetpack upgrade is back on the mining vendor. Rejoice!
/:cl:

### CODE REVIEW

**Comment by AU518987077** [comment]
:)

**Comment by Karmic-Skink** [comment]
Expect us to do a full review of that list when we do the salvaging update.

**Comment by covertcorvid** [comment]
Current opinion from the team is that this isn't necessary for the asteroid cage, but we will be adding jetpacks for the rework with Sabre docking.

**Comment by bluey89962** [comment]
> Current opinion from the team is that this isn't necessary for the asteroid cage, but we will be adding jetpacks for the rework with Sabre docking.

miners are quite possibly the most oppressed minority

**Pull request closed without merging**
