### PR TITLE
Adds Purge and Freeform boards to Hammerhead upload

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Title. Added inside the harmful enclosure.
Also adds a mechanical toolbox beside the foam tanks in the teleporter room.
image

## Why It's Good For The Game

It's reaaal annoying when you can't purge and upload a law to make the AI let you use the nuke.

## Changelog
:cl:
add: Added the Purge and Freeform boards to Hammerhead's upload.
add: Added a mechanical toolbox beside the foam tanks in the Hammerhead service ship.
tweak: Service room in the Hammerhead's support ship now has flooring. No more mouse'd wires!
/:cl:

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
I did a bad

**Comment by MarkSuckerberg** [comment]
???

**Comment by Shadow-Quill** [comment]
Will do tomorrow

**Comment by Shadow-Quill** [comment]
it took far too long to get the githook workin on my laptop.

good going windows

**Pull request merged**
