### PR TITLE
Squad armors and pulse armor tweaks

### PR DESCRIPTION
**Pull request by Evie7056**
## About The Pull Request

This PR scopes two different things from same shelf. Firstly, it allows all squad armors take to it's exoslot every sec items that can wear regular sec vest or mp armor. I didn't include Marine Rifle or Pulse Rifle since they weren't of the list in the first place. Feel free to say something about it if you think rifles should be able to be placed on armor.

The second thing this PR does is rebalances Pulse Rifle that was nerfed to the ground. Both lethal and non-lethal mag sizes are up to unholy 75 rounds turning the gun into mobile machine gun with the purpose of suppression of anything that stands in the way. Note that the damage of the rounds is still low, only 10 damage. I've also lowered guns AP since 60 was too much for me. 60 AP is equivalent of making bulletproof vest and elite syndie hardsuit a paper. Note that it's most possible level of bullet defense you can get. 
Those changes making the gun is something viable for it's price (still much pricier than MR), but not straight better that regular marine rifle since it has higher damage.

And in the last I would say that all numbers are adjustable. Maybe 40 AP (equivalent of 9mm AP rounds if they can be even obtained normal way) is too high, or 75 clip is just too much. 

## Why It's Good For The Game

Makes squad guy's easier.
Makes Pulse Riffle actually worth it's price.

## Changelog
:cl:
tweak: Squad items can take on it all sec items
balance: Pulse rifle now has 75 rounds mag size
balance: Lower it's AP to 30
fix: Pulse rifle related crates can now be found in "Armory" section instead of "Security"
/:cl:

### CODE REVIEW

**Comment by Evie7056** [comment]
PR opened but now I think that 40 should be lowered to 35 since 40 is amount of protection of squad armor *and* captain carapaces'.

**Comment by Evie7056** [comment]
Map label because of replacing old 30 rounds sized lethal mags from galactica.

**Comment by TheScienceOfKSP** [comment]
High Mag, low DMG

Yeah, that's actually something i agree could even out the Pulse Rifle.

**Comment by Evie7056** [comment]
I forgot to mention that I moved pulse rifle crates to armory

**Review by Bokkiewokkie — APPROVED** [review]
We'll see if the mag size needs to be changed after testing

**Pull request merged**
