### PR TITLE
Removes Bees ~~apids~~

### PR DESCRIPTION
**Pull request by GoatMonarch**
## About The Pull Request
I went through all prs related to apids, and removed their relevant code.

## Why It's Good For The Game
[Because fuck them](https://www.youtube.com/watch?v=8CvqmD0CZao)

Dumb ass, slightly more dark vission, less breathing but 1.5x of brute and cold/burn bees. Hate them! 

## Changelog
:cl:
del: Removed apids.
/:cl:

### CODE REVIEW

**Comment by DrSirKnight** [comment]
replace them with a torp race so we have a race related to NSV

**Comment by DatBoiTim** [comment]
Uh oh someone didn’t follow Beestation repo contribution guidelines 😳

**Comment by GoatMonarch** [comment]
> replace them with a torp race so we have a race related to NSV

I'll **totaly** do this after this PR is merged, and not forget about it. Like any good code changer man would do

**Comment by Tennessee116** [comment]
Creator of apids here. Don't incentivize this race. I approve.

**Pull request closed without merging**
