### PR TITLE
Hungry gunpowder bag

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

Adds a very hungry gunpowder bag, a chef exclusive craftable. His power grows the more you feed him, be careful not to feed him too much though or he might get cranky

## (He is a very good boy)
goodboy1
goodboy2

## Why It's Good For The Game

This motherfucker can eat metric fuck tons of food. Nobody could stop this absolutely badass gunpowder bag from literally eating gigantic fucking pears, strawberries, even fucking sandwiches and ice cream, like holy fucking shit what kind of bad ass gunpowder bag fucking eats ice cream like it’s no big fucking deal

## Changelog
:cl:
add: Adds the hungry gunpowder bag
/:cl:

### CODE REVIEW

**Comment by red031000** [comment]
out of curiosity, why chef?

**Comment by TheFakeElon** [comment]
Mostly because it requires a lot food and it'd suck if other jobs started stripping the station of food to feed it, especially if there's no chef. It also limits the meta potential of the hungry bag, though the idea of a chef-munitions is quite funny

**Review by Bokkiewokkie — DISMISSED** [review]
Very cute

**Comment by red031000** [comment]
needs a way I can beg an admin to let me be one, control it, and eat the entire crew during combat

**Comment by TheFakeElon** [comment]
wiki updated

**Comment by Bokkiewokkie** [comment]
> wiki updated

Our policy is to only do that after fullmerging something, but I'll allow it having been done earlier because of how cute it is

**Review by Bokkiewokkie — APPROVED** [review]

**Pull request merged**
