### PR TITLE
Fixes vehicles not being able to go down z-levels

### LINKED ISSUE #364: Clown cars can't move down open space.
## Round ID: 
Last test, last of the rounds.

## Reproduction:
Enter clown car, you're capable of driving up stairs, but imcapable of going down again. The object seemingly can drive over open space like nothing.

### LINKED ISSUE #433: Mechs cant go downstairs
Issue reported from  Round ID: 140 (NSV 13 | Official | "MRP" | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1517

Mechs cant go downstairs or fall down an open space.

### PR DESCRIPTION
**Pull request by TheChaser212**
## About The Pull Request
Anchored objects aren't able to go down z-levels and for some reason mechs and cars were anchored rather than just being unpullable.
Fixes #433
Fixes #364

## Why It's Good For The Game
Going down is nice

## Changelog
:cl:
fix: mechs and cars can go down
/:cl:

### CODE REVIEW

**Comment by GoatMonarch** [comment]
There may be a simmilar issue with the clown-car and other viechles, like the adminspawn car. Would be great if you could see if there's a simmilar issue with both of them.

**Comment by TheChaser212** [comment]
Yeah looks like cars have the same problem so I'll change them too

**Comment by Cenrus** [comment]
Nice, that's a simpler fix than /TG/ implemented. https://github.com/tgstation/tgstation/pull/47741

**Comment by francinum** [comment]
Does this allow them to be shoved? That was another reason they were anchored, to act all blockers

**Comment by TheChaser212** [comment]
> Does this allow them to be shoved? That was another reason they were anchored, to act all blockers

You'd need an absurdly high amount of move force to push them around

**Pull request merged**
