### PR TITLE
[UPSTREAM] Ports Genpop from NSV to BeeStation to NSV

### PR DESCRIPTION
**Pull request by someone543**
## About The Pull Request
Ports the PRs below from BeeStation: 
- https://github.com/BeeStation/BeeStation-Hornet/pull/10166
- https://github.com/BeeStation/BeeStation-Hornet/pull/10494
- https://github.com/BeeStation/BeeStation-Hornet/pull/10569
- https://github.com/BeeStation/BeeStation-Hornet/pull/10502

Moves Genpop from the NSV13 folder and adds the new holodeck workshop and other features from BeeStation to the Gladius and Hammerhead (See screenshots). 

**Workshops**
From the original PR, 
Prisoners can make donuts or ~~bots~~ plushes and scan them to get reduced sentences. 
Currently, only donut and plush workshops are available, and either can be loaded in using the holodeck console in the Warden's Office.

**Other Features**
- Prison grilles have been added to genpop windows. Break one, and blast doors from every other window will close. 
- Genpop interface has been updated (See screenshots) choose a severity and it will show what crimes are applicable
- Plushes can now be crafted using cloth

## Why It's Good For The Game
Keeps our code up to date with BeeStation, and improves our own genpop with new features
Also fixes https://github.com/BeeStation/NSV13/issues/2619

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Updated Genpop Interface 

GenpopNewInterface

Gladius (Execution room has been moved to the firing range for more space)

WorkshopGladius1

Hammerhead 

WorkshopHammerhead1

</details>

## Changelog
:cl: Haliris, BriggsIDP, Powerfulbacon, TsunamiAnt, PestoVerde322
add: Added workshop area to brig based on the holodeck code, where prisoners can make donuts or plushes and scan them to get reduced sentences. Adds secure floors and prison grilles to help secure the prison area better. Adds crafting method for plushes to support the prison plushes sweatshop.
add: Added genpop workshops to Hammerhead and Gladius
tweak: Changed the path of the previous prisoner id used for gulag (now id/gulag). Updated paths of the current holodeck templates to holodeck/recreational to allow for easier subtypes implementation. Removed holographic flag preventing the crafting menu from working.
tweak: Genpop code and icons moved out of nsv13 folder
/:cl:

### CODE REVIEW

**Comment by Bokkiewokkie** [comment]
Currently on hold because the laws in here are still bee laws and not NSV ones

**Comment by someone543** [comment]
> Currently on hold because the laws/punishments in here are still bee laws and not NSV ones

Just the ones in config/space_law.json or should I also change the backup in code/modules/security/crimes.dm?

**Comment by Bokkiewokkie** [comment]
> > Currently on hold because the laws/punishments in here are still bee laws and not NSV ones
> 
> Should I change just the ones in config/space_law.json or should I also include the backup in code/modules/security/crimes.dm?
> 
> Also it looks like that our Space Law is missing some laws like possession of contraband, and has fine evasion as a infraction rather than a minor crime (Infractions aren't included in the interface)

The crimes.dm file is the more important one because it's hardcoded and can't be changed in the server

**Review by Bokkiewokkie — CHANGES_REQUESTED** [review]
Not a full review, but some things I saw

**Review by Bokkiewokkie — CHANGES_REQUESTED** [review]
Mapping review:
Can you revert the changes on Atlas (don't forget the top deck) and Tycoon (except where necessary for the typepaths) I'd like to rework those seperately later.
Also please put the grilles in space closer to the windows again similar to how the rest of the ship has it on the Gladius.
On Hammerhead you've put down a newscaster in front of the armory on accident, and the red tile decals at the holoroom door should match the rest of the ship's style. There are also some firedoors in the brig hallway which could use a northern side if you'd like to add em in this too.
Also remember to put in a fire alarm and air vents in the rooms you've added.

**Review by Bokkiewokkie — DISMISSED** [review]

**Comment by SerynEngi** [comment]
Additional request, since you're mass map changing anyway, mind fixing this?
https://github.com/BeeStation/NSV13/issues/2619

**Comment by someone543** [comment]
I don't think changing the area of a single tile is supposed to cause this

TestFailed

**Review by Bokkiewokkie — APPROVED** [review]

**Pull request merged**
