### PR TITLE
Ports The Multi-Cell Charger

### PR DESCRIPTION
**Pull request by Bobbanz1**
## About The Pull Request
Ports the following PRs
Partially ports [BeeStation/BeeStation-Hornet/pull/3366](https://github.com/BeeStation/BeeStation-Hornet/pull/3366)
Partially ports [tgstation/tgstation/pull/54989](https://github.com/tgstation/tgstation/pull/54989)
Ports [Skyrat-SS13/Skyrat-tg/pull/4867](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4867)
Ports [Skyrat-SS13/Skyrat-tg/pull/4896](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4896)
Ports [Skyrat-SS13/Skyrat-tg/pull/4914](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4914)
One thing from [Skyrat-SS13/Skyrat-tg/pull/4900](https://github.com/Skyrat-SS13/Skyrat-tg/pull/4900), allows you to Ctrl+Shift click the machine to dump the cells
One line of code from [Skyrat-SS13/Skyrat-tg/pull/6265](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6265)

## Why It's Good For The Game
Allows you to charge 4 Cells, in a multi-cell charger, in the same span of time it takes to charge 1 cell in a regular fully upgraded cell charger.
Duct-Taped Cell Chargers equals more efficiency!

## Changelog
:cl: Watermelon914, jupyterkat, zxaber, Gandalf2k15, ZephyrTFA, tf-4
add: Added tgui lists
add: A multi-cell charger for all your charging needs. Can hold up to 4 cells! That's 3 more than the normal one, amazing!
qol: Multicell chargers are now better because you can remove the specific cell you want.
fix: NanoTrasen engineers found an issue where Multi-Cell Chargers could only use one of their capacitors, this has been fixed!
/:cl:

### CODE REVIEW

**Comment by Bokkiewokkie** [comment]
Can you make a double of this PR on Beestation as well? It's obviously not required since most of this is in the nsv13 folder, but at least the TGUI changes would be good to keep up to date. (unless bee already has those TGUI elements and it's nothing we need to worry about in a rebase of course)

**Comment by Bobbanz1** [comment]
> 

Bee doesn't have the TGUI element, they had it before and then somebody reverted it

**Comment by Bobbanz1** [comment]
See PR [BeeStation/BeeStation-Hornet/pull/3980](https://github.com/BeeStation/BeeStation-Hornet/pull/3980)

**Comment by Bobbanz1** [comment]
Do you still want me to try making a PR for it upstream?

**Review by Bokkiewokkie — APPROVED** [review]

**Pull request merged**
