### PR TITLE
Gives MaA locker a munifab board

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

yeah 

## Why It's Good For The Game

All other heads get a techfab board in their lockers, also a temp fix for aetherwhisp not having a munitions lathe.

## Changelog
:cl:
fix: The Master at Arms now has a munitions lathe board in their locker.
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
Time to watch people get upset about the muni fab again

**Comment by Karmic-Skink** [comment]
Explain why this is important for the MAA to have in their locker.

**Comment by Pontenerd** [comment]
> 
> 
> Explain why this is important for the MAA to have in their locker.

Because every other department head has a fab board in their locker?

**Comment by Karmic-Skink** [comment]
> > Explain why this is important for the MAA to have in their locker.
> 
> Because every other department head has a fab board in their locker?

Then it should be written on the PR in the relevant sections rather than trying to be 'funny'.

**Review by Kmc2000 — APPROVED** [review]
For consistency, sure

**Pull request merged**
