### PR TITLE
Hammerhead fixes and stuff

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
I put it the wrong way around the first time lol

### CODE REVIEW

**Comment by theboy6545** [comment]
fool

**Review by Vasily2013 — APPROVED** [review]

**Comment by Vasily2013** [comment]
@francinum travis stuck

**Comment by Bokkiewokkie** [comment]
merge conflict? who in their right mind would update Hammerhead?

**Comment by Bokkiewokkie** [comment]
aight this is fully done now (unless it doesn't get merged soon cause then I might add more things to it)

**Comment by Bokkiewokkie** [comment]
travis only died because of a random maint room thing, it should be good

**Comment by Vasily2013** [comment]
Are there any issues to link to this that are specifically on the github? I'm going to try and start looking at pull requests in my spare time.

**Comment by Bokkiewokkie** [comment]
I've looked and there's no actual git issues

**Review by Vasily2013 — APPROVED** [review]

**Pull request merged**
