### PR TITLE
Adds a crewmate plushie

### PR DESCRIPTION
**Pull request by RemervKeberb**
## About The Pull Request

Adds an amogus to the game that can only be spawned in by admins. It has a vent sound effect when used.
vented
## Why It's Good For The Game

Ansome being able to terrorize us with more amogus is good

## Changelog
add: amogusplush

### CODE REVIEW

**Comment by Pontenerd** [comment]
Among

**Comment by RemervKeberb** [comment]
ah, thank you. Will do

**Comment by Karmic-Skink** [comment]
No.

**Comment by Cenrus** [comment]
Among us

**Comment by TheFakeElon** [comment]
sus

**Comment by triplezeta** [comment]
amogus is awesome but this sprite is not

**Comment by RemervKeberb** [comment]
Looking at it now, yeah. It really is. Just made it to figure out how all this stuff works.

**Review by Kmc2000 — APPROVED** [review]
My final message.. change the world. Goodbye

**Comment by Bokkiewokkie** [comment]
🚬 If it gets merged on upstream we'll merge it here.

**Pull request closed without merging**
