### PR TITLE
Gladius- Mail Mapping fix [Ready] Fixes issue #1182

### PR DESCRIPTION
**Pull request by SerynEngi**
## About The Pull Request

Fixed the Gladius Mail system. Fixing issue #1182. Refined routing of piping to more efficient route.

## Why It's Good For The Game

People might like to mail things to other departments. Engineers might like it to be less complicated to repair.

## Changelog
:cl:
add: Mailing outputs/inputs to primary departments.
tweak: Rerouted disposals/mail piping into a more efficient routing.
fix: Fixed destination tags so that things headed to departments will arrive there.
fix: Issue #1182 
/:cl:

### CODE REVIEW

**Comment by SerynEngi** [comment]
So as not to crowd the thing, here are the destinations as of the time of the PR. Labeled in order of their functional location on the line. All departments with an input into the line received a destination tagger and wrapping paper nearby said input.

Disposals (output only)- receives: disposals
Engineering (input/output)- receives: Engineering, CE Office
Atmospherics (input/output)- receives: Atmospherics
Cook (output only) receives: Kitchen
Security (Output only) receives: Security, HOS Office, Law Office, Detectives Office
Medbay (input/output) receives: Medbay, CMO office, Chemistry, Genetics/ and Virology
Science (input/output) receives: Research, RD Office, Robotics, Toxins, Xenobiology
Cargo (input/output) receives: Cargo, Quartermaster. (untagged/incorrectly labeled non-waste items)

If its not mentioned here, it will return to its destination. The lines associated with munitions were left untouched.

**Comment by SerynEngi** [comment]
Note- its ready, but it requires PR#1245 to be merged in order to function.

**Comment by Vasily2013** [comment]
During one of the gladius rounds last weekend I noticed that distro didn't start connected. Can you please just double check this really quick?

**Comment by SerynEngi** [comment]
> During one of the gladius rounds last weekend I noticed that distro didn't start connected. Can you please just double check this really quick?

Aerwhisp brought it to my attention awhile back. It was the first thing I fixed when I looked at this, and was part of the first commit. Apologies for not noticing your comment earlier. If I don't respond within a day or so to something you think needs done, please ping me.

**Comment by Bokkiewokkie** [comment]
Should probably add "Fixes #1182" to the PR text so it autocloses the issue

**Review by Vasily2013 — APPROVED** [review]
movealong

**Pull request merged**
