### PR TITLE
Jeppison Service Rework

### PR DESCRIPTION
**Pull request by Omppusolttu**
## About The Pull Request

This PR reworks the jeppison's service department, fixes 2 wide corridors on deck two, reorganizes command and adds a ton of maintenance corridors

## Why It's Good For The Game

A lot of the playerbase dislikes the Jeppison, this is my attempt to remedy that

## Changelog
:cl:
add: Added maintance corridors and modern firelocks onto the jeppison
tweak: Changed command and service on the jeppison
/:cl:

### CODE REVIEW

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
image
Shuttle dock should be changed to nearstation. I don't mind the lights for the weapons areas having the area different, but that massive section of exposed plating needs to be changed.

My primary concern is that the walk from the bar to security is now significantly longer since you can no longer cut through the cafeteria. So if you could find a way to cram a walkway to the security hallway from the bar that'd be excellent in my opinion.

Otherwise this will need a test merge.

**Comment by Omppusolttu** [comment]
The fixes have been made

**Comment by Vasily2013** [comment]
there's an emergency patch that I had to make to the jepp. I had to reconnect pipes going into the bridge, and add a carpet turf under the Captain's door. Here is the section that is affected. 
image

**Comment by Omppusolttu** [comment]
> there's an emergency patch that I had to make to the jepp. I had to reconnect pipes going into the bridge, and add a carpet turf under the Captain's door. Here is the section that is affected.
> image

I'm sure I fixed that already? What the hell?

**Comment by Omppusolttu** [comment]
Oooook, something is REALLY fucked with this PR then, because that captain's office shouldn't even **be** there I shifted it into the spot where the HoP's is right now.

**Comment by Vasily2013** [comment]
So what you need to do is just push a commit with your map in it again to overwrite the merge conflicts.

**Comment by Omppusolttu** [comment]
> So what you need to do is just push a commit with your map in it again to overwrite the merge conflicts.

should be good now

**Comment by Vasily2013** [comment]
push your commit

**Comment by Vasily2013** [comment]
if you use gitkraken what you can also do is press the "resolve conflicts" thing and just keep all the changes from your branch.

**Pull request closed without merging**
