### PR TITLE
SOP book update

### PR DESCRIPTION
**Pull request by Karmic-Skink**
## About The Pull Request
Puts the icon dmi in the correct location.
Matches the style guide of the munitions book.

## Why It's Good For The Game
Doing it properly so is good for game.

## Changelog
:cl:
tweak: Moved the DMI to the proper folder
imageadd: Updated Munitions SOP to use the style guide
/:cl:

### CODE REVIEW

**Comment by GoatMonarch** [comment]
Imma just gonna give this a certified **bruh**

**Comment by Karmic-Skink** [comment]
> Imma just gonna give this a certified **bruh**

This is 2021. Puce isn't funny.

**Comment by GoatMonarch** [comment]
> > Imma just gonna give this a certified **bruh**
> 
> This is 2021. Puce isn't funny.

Oh yeah? We'll see about that

**Comment by theboy6545** [comment]
> 
> 
> > Imma just gonna give this a certified **bruh**
> 
> This is 2021. Puce isn't funny.

lies

**Comment by triplezeta** [comment]
BOOOO CRINGE

PUCE IS STILL FUNNY 2021

**Review by Jalleo — APPROVED** [review]
I will let Kmc decide which to merge.

**Pull request closed without merging**
