### PR TITLE
Minor interstitial upstream pull

### PR DESCRIPTION
**Pull request by francinum**
Minor interstitial update.

### CODE REVIEW

**Comment by francinum** [comment]
SQL stuff needs a check over, BSQL's removal still has a few pretty deep wounds.

**Comment by Jalleo** [comment]
Remove the Do not Merge once you are a okay with it.

**Comment by francinum** [comment]
After talking with Crossed, assuming that we have no custom SQL interactions (we don't), there should be no issues with it.

On the bright side we can use all of rust-g's stuff.

**Comment by francinum** [comment]
We'll be here all fucking day if I wait for the map diff bot to wake up from it's eternal slumber

**Pull request merged**
