### PR TITLE
NSV13 clown specific sub sprites are renamed. Updated all pathing

### PR DESCRIPTION
**Pull request by GoatMonarch**
## About The Pull Request
Our specific clown uniform and the vanilla clown uniform used to only pick one of the sprites for both. Now the icon states have different names. Tested it myself and I grant this the *WorksOnMyMachine* award.  

Fixes: #792 

## Why It's Good For The Game
Fixing bugs is good. I also get to pat myself on the back for I fixed one of my oldest git issues.
*Update
Forgot to share screenshots, but it stops this from happening in the job setup screen:
Skärmklipp

## Changelog
:cl:
fix: Clown uniforms now use the proper sprites! HONK!
/:cl:

### CODE REVIEW

**Review by Kmc2000 — DISMISSED** [review]
Essential PR

**Comment by GoatMonarch** [comment]
Played a couple rounds with this PR test merged. Seen zero issues so far with it.

**Comment by GoatMonarch** [comment]
Gonna fix this later today. Remain calm.

empty within

**Comment by GoatMonarch** [comment]
Making a single push, by merging upstream took me hours of time to actually get to work. Hours of errors messages, and for what? Just to fix a clown sprite. I am genuinely tired. I am not relieved, only upset. Github is the worst thing to happen to humanity throughout our relatively short lifespan. This is the kind of torture, that countries of our time, would not force uppon even the worst of crimminals. I would take anything over suffering what Github is as a whole. This PR turned from a fast fix, into an existential dread. If this is what coding for SS13 is like, what comes next? I do not wish to open my eyes, to see what the future may hold.

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
