### PR TITLE
[Port] Printer TGUI, Printer Forms and Species specific rear printer photos 

### PR DESCRIPTION
**Pull request by Bobbanz1**
## About The Pull Request
Ports the following PRs from TG:
[52831](https://github.com/tgstation/tgstation/pull/52831)
[54336](https://github.com/tgstation/tgstation/pull/54336)
[55379](https://github.com/tgstation/tgstation/pull/55379)
[61323](https://github.com/tgstation/tgstation/pull/61323)
[63287](https://github.com/tgstation/tgstation/pull/63287)
[67258](https://github.com/tgstation/tgstation/pull/67258)
[69005](https://github.com/tgstation/tgstation/pull/69005)

## Why It's Good For The Game
Introduces a bit more bureaucracy to the photocopiers. 

## Changelog
:cl: SteelSlayer, actioninja, uomo91, twilightwanderer, Ghilker
refactor: Photocopiers now use TGUI
tweak: You can insert any type of toner cartridge into photocopiers, and regardless of the currently inserted toner's charge level.
tweak: Toner cartridges can be ejected from photocopiers at any time
add: Increased photocopier accuracy aka ADDED MORE BUTT PHOTOCOPIES
add: Added a system of forms and the ability to print them
fix: Hints in bureaucracy forms
imageadd: adds the podpeople photocopy ass
add: Added new VOID stamp
fix: Photocopier paperforms
/:cl:

### CODE REVIEW

**Comment by red031000** [comment]
where's the moth ass smh

**Comment by Bobbanz1** [comment]
> where's the moth ass smh

Go make one and I’ll add it in

**Review by covertcorvid — COMMENTED** [review]
Appears functional. I was unable to work out how to test the forms/blanks section of the copier, since writing one of them on a piece of paper with a pen didn't seem to do the trick. It's totally possible that I made a typo when de-JSONing it though.

**Comment by covertcorvid** [comment]
Also why did actions bot put the SQL tag on this?

**Comment by Bobbanz1** [comment]
> Also why did actions bot put the SQL tag on this?

Possibly something to do with the asset cache maybe?
Could be malfunctioning as well

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
