### PR TITLE
[READY] NSV Galactica fixes and service redo

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Fixes issues with the NSV Galactica, The mess area has been remapped and now features a larger kitchen and a better theatre area. See mapdiffbot for changes.

Fixes multiple issues. Cargo + engineering sec posts.

## Why It's Good For The Game

Galactica needs some TLC

## Changelog
:cl:
fix: Fixes multiple issues with the NSV Galactica.
add: Galactica service has been redone.
add: Galactica now has Engineering/Cargo security posts
/:cl:

### CODE REVIEW

**Comment by GoatMonarch** [comment]
> See mapdiffbot for changes.
Implying that map-diff bot has worked once durring my time here. hehe xd

**Comment by Vasily2013** [comment]
Point the first: Please relate in the changelog what fixes you did/what you changed. Mapdifbot doesn't show everything and 145k line changes is a lot to sift through by hand.

Point the second: This PR is embargoed until Starmap is merged unless there are major issues that need to be immediately rectified.

**Comment by Jalleo** [comment]
Placed a do not merge as something is incorrect with this PR at the time.

**Comment by Kmc2000** [comment]
Looks pretty nice!
I'm sad to lose the direct access that botany had to the bar, though, as that's nice for more complex drinks

**Comment by Cenrus** [comment]
Finished and ready for merge/testmerge.

**Pull request merged**
