### PR TITLE
Overhaul999

### PR DESCRIPTION
**Pull request by Vasily2013**
## About The Pull Request

From: Doesnt.Do.Much @AbassiFltYrd.nt
To: FA.Gosse @seegnet.nt
We have finished overhauling the Vago class hulls that were in the fleet yards. We stripped out as much material we could and we've been drawing from that resource pile to keep Jeppison class ships in service. At this time we can perform no further actions with the Vago hulls without removing combat capability or spaceworthiness, which would be a violation of NT.SO.506571804. We are thus returning these ships to service.

Doesn't-Do-Much
Sector Shipyard and Training Oversight Officer 

## Why It's Good For The Game

The memes mainly, also fixes Vago to a playable state.

## Changelog
:cl:
tweak: Vago now has a different feel.
/:cl:

### CODE REVIEW

**Comment by theboy6545** [comment]
oh no

**Comment by Tennessee116** [comment]
You forgot to remove all the floor decals. Not sure that's noteworthy or that it matters, just wanted to point that out.

**Comment by Tennessee116** [comment]
image
Even for memes this is a little sketchy.

**Comment by Kmc2000** [comment]
Well, fuck it why not

**Review by Kmc2000 — APPROVED** [review]
What could possibly go wrong

**Pull request merged**
