### PR TITLE
fixes the hammurabi asteroid cage

### PR DESCRIPTION
**Pull request by athena413**
## About The Pull Request

someone made the hammurabi asteroid cage be half the size it needs to be which means that if you pull an asteroid in it'll destroy the top deck.

i brought the asteroid cage to its normal size so it shouldnt do this anymore

image

## Why It's Good For The Game

fix man good

## Changelog
:cl:
tweak: hammurabi asteroid cage is now large

/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
#1583

**Comment by athena413** [comment]
> 
> 
> #1583

Pain.

**Comment by Karmic-Skink** [comment]
Leave it here until its resolved, the conflicts if any will be easy to address.

**Comment by TheOneAndMightyRed** [comment]
Might also be worth putting a mining dradis console at the helm instead of a normal one since you can't see asteroids otherwise.

**Review by Bokkiewokkie — APPROVED** [review]

**Pull request merged**
