### PR TITLE
Adds ability for AI to lead targets

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
The AI can now aim at moving targets, with a default 5% chance (we can play with this) to be off target in a random direction.
**Admins** if the AI is too good at shooting while this is getting tested you can increase the ai_miss_chance and ai_max_miss_distance variables.

## Why It's Good For The Game
Makes flying a little more interesting. This will also allow us to potentially make player ships less brick-like while still being able to be hit.

## Changelog
:cl:
add: Aimbot for the AI ships
/:cl:

### CODE REVIEW

**Comment by skigear** [comment]
Bridge staff piloting is a lot more interesting with this.

**Comment by covertcorvid** [comment]
> 
> 
> Bridge staff piloting is a lot more interesting with this.

Glad to hear it!

**Review by Karmic-Skink — APPROVED** [review]
Definitely a sorely needed addition.

**Review by Bokkiewokkie — APPROVED** [review]

**Comment by Demoxide** [comment]
Good addition, will make fighter piloting more movement rather than finding a solid strafing trajectory and spamming out rounds.

**Pull request merged**
