### PR TITLE
Overhauls the SSV Hammurabi to be Monstermos compliant and makes declaring war ops work.

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## Changes
Improves the SSV Hammurabi map in various ways which make the Hammurabi less of a pain to play on in general.
I also added an autolathe to the map, something which I have heard many people ask for. Please don't make me regret putting it there.
There's also now air scrubbers, fire alarms, fire extinguishers and hull repair juice on the ship.

## Changelog
:cl:
fix: You can now properly declare war as the Syndicates during PVP.
fix: Makes the SSV Hammurabi Monstermos and Nuke Torpedo compliant.
add: Syndicate Telecommunications operators now get a voice changer to confuse the crew!
add: The Syndicate Captain now has a sweet new office!
add: Gives the Syndicate an autolathe on their ship.
/:cl:

I thought people may wanna see the changed things in a nice picture so I'll add some here:
Captain's room:
image
Tool storage with autolathe
image
New and improved telecomms center with paper for writing notes, intercom for actually communicating and a gas mask voice changer to be an actual comms agent.
image
Reworked engineering, now with: welding mask, rpd, electrical toolbox, atmos and power monitors, a valve for plasma to the reactor and emergency Co2!
image
(also some cheecky hull juice and welding tanks, of which there are more at the airlock just in case)

### CODE REVIEW

**Comment by theboy6545** [comment]
looks good, not that i have any swing here, but i just wanted to say i like it

**Comment by Vasily2013** [comment]
- [ ] Replace the windows with window spawners used on the main ship. They include window firelocks, which are good for monstermos and how often we blow holes in our ship.
- [ ] Additionally to the point above, if you use the spawners you don't need to include firelocks under exterior windows.
- [ ] You'll need to instal an actual airlock controller and test it to make sure it works for the reactor room.
- [ ] There is a non-compliant airlock in the hangar bay.
- [ ] I'd say a few more tanks of air or a o2 gas miner would be appropriate given how fast decompression tend to drain atmos.

Overall this looks good. Just a couple hiccups to work out and she'll be good to go.

**Comment by francinum** [comment]
For a ship this small and the purpose it is a gas miner is perfectly acceptable.

**Comment by Bokkiewokkie** [comment]
well I don't seem to be able to tick the boxes on your message so you'll just get an upthumb, but I changed the windows around, made a little atmos area, fixed the airlock(s) and also the railings in the bridge which were a bit funky.
I didn't add an airlock controller into the SD one and actually replaced the vent with a regular one too, cause having an airlock controller for something with the same pressure on both sides seemed a bit pointless.

**Comment by francinum** [comment]
Not tested during the testmerge period due to horrifying physics bugs not related to this PR.

**Review by Vasily2013 — APPROVED** [review]
Looks okay from a mapping perspective.

**Pull request merged**
