### PR TITLE
Changes traitor steal objective: reflector vest to riot suit

### LINKED ISSUE #637: [Hammerhead] No reflective vest in armoury
## Round ID:
405

## Testmerges:
irrelevant

## Reproduction:
doesn't exist. can appear on traitor objectives, though. path: `/obj/item/clothing/suit/armor/laserproof`

### PR DESCRIPTION
**Pull request by Corsaka**
## About The Pull Request
title

## Why It's Good For The Game
means traitors can actually complete their objectives
fixes #637 

## Changelog
:cl:
tweak: change antag objective from reflector vest to riot suit
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Can't we just... Put reflector vest in the armory?

**Comment by francinum** [comment]
Then maybe having to conceal a big fuckoff armor vest will make it more difficult an objective.

**Comment by francinum** [comment]
Also at the moment no, maps are super frozen for the rebase

**Comment by Corsaka** [comment]
Reflector vests only work on lasers. We don't have lasers.

**Comment by Jalleo** [comment]
This PR likely conflicts with the update.

**Comment by Karmic-Skink** [comment]
Why was this merged without an //NSV13 tag?

**Pull request merged**
