### PR TITLE
 Resprites the CC Official's uniform and adds a CC Official cloak. 

### PR DESCRIPTION
**Pull request by Bamhalazam**
(TRAVIS, DON'T CRY PLEASE)

## About The Pull Request:
Resprites the CC uniform. Adds a cloak.
(FRONT: https://cdn.discordapp.com/attachments/723875082295836722/780799861842247690/cc1.png)
(BACK: https://cdn.discordapp.com/attachments/723875082295836722/780799880078950440/cc2.png)

(SIDE: https://cdn.discordapp.com/attachments/723875082295836722/780799902271275038/cc3.png)
(CLOAK FRONT: https://cdn.discordapp.com/attachments/723875082295836722/780799950740389939/cc6.png)
(CLOAK BACK: https://cdn.discordapp.com/attachments/723875082295836722/780799927722049566/cc7.png)
(CLOAK SIDE: https://cdn.discordapp.com/attachments/723875082295836722/780800038384435220/cc9.png)
 

## Why It's Good For The Game

New sprites, updating it from the old 2000s stuff we had. Better palette, and maybe CC bureaucrats will get some love. As I've said, everyone can't be an admiral.

## Changelog
:cl:
add: Added new things
add: Added more things: Adds CC cloak.
tweak: tweaked a few things: Tweaked CC uni.
imageadd: added some icons and images: cloak.
code: changed some code: Added item, added the item to the CC Official spawnlist.
admin: messed with admin stuff: Changed CC uniform that only admemes can access
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Looks pretty nice! We'll testmerge it

**Comment by Bamhalazam** [comment]
@Kmc2000 if you'd like, I'll return to this along with a new map of CC.

 It's just a pet passion project but you could pick off the best parts of it.

**Comment by Bamhalazam** [comment]
> 
> 
> @Kmc2000 if you'd like, I'll return to this along with a new map of CC.
> 
> It's just a pet passion project but you could pick off the best parts of it.

also will merge less shitty commits, back in that time I didn't know how to use github

**Comment by Kmc2000** [comment]
> @Kmc2000 if you'd like, I'll return to this along with a new map of CC.
> 
> It's just a pet passion project but you could pick off the best parts of it.

Oh nice! Wow that's my bad for not getting to this, must've got lost in the backlog!
If you'd like to re-open the PR i'll address it more fully

**Pull request closed without merging**
