### PR TITLE
adds hk plushes

### PR DESCRIPTION
**Pull request by triplezeta**
i did it

## About The Pull Request

adds 3 new plushes, all available in the metacoin shop
image

## Why It's Good For The Game

its not

## Changelog
:cl: tiramisuapimancer & triplezeta
add: 3 new marketable plushies
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
Pride moth? Don't be so silly jack, shits gay all year round!

**Comment by Karmic-Skink** [comment]
Core files need an //NSV13 tag.
Additional code not required to be in core files should be located in the NSV13 subfolders.

**Comment by TheFakeElon** [comment]
Back in my day it was the rainbow flag 
image

**Comment by triplezeta** [comment]
its modularized now

**Comment by Karmic-Skink** [comment]
So how exactly is this relevant to NSV13?

**Comment by triplezeta** [comment]
Frankly, it isn't. I did this because someone else showed interest in porting over the plushies to here and I was bored.

**Pull request closed without merging**
