### PR TITLE
Slugcats!

### PR DESCRIPTION
**Pull request by sunofang**
## About The Pull Request
Not much to say. Ports 3 types of slugcats from the server we shall not name.
1 : Deathsquad slugcat.
2 : Nukie slugcat.
3 : Ordinary slugcat.

(ported from vorestation, only sprites tough, code is jsut a copy paste of standard NPC code)
## Why It's Good For The Game
More pets is always good. And slugcats are cute.
## Changelog
:cl: SunoPerson
add: Added slugcats to the game.
imageadd: Ported the icons for slugcats from vorestation.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
> Ports 3 types of slugcats from the server we shall not name

You should always credit ported code

**Comment by TheFakeElon** [comment]
and you *must* credit ported sprites

**Comment by sunofang** [comment]
Credited.

**Comment by Bokkiewokkie** [comment]
Please consider porting this upstream first, if you don't want to you'll have to change the image file

**Comment by sunofang** [comment]
Alrighty

**Pull request closed without merging**
