### PR TITLE
More new tool sprites while hopefully not breaking anything

### PR DESCRIPTION
**Pull request by bluey89962**
## About The Pull Request
This is the first time I do one of these so I hope everything works fine
Changes more tool sprites to the ones made by @SomeAngryMiner that were missing in another recent pull request (#1097) such as multitools and analyzers. Also changes engi belts so they look nicer

## Why It's Good For The Game
Not only do they look nicer than the current ones but they also fit with all the other new sprites. It's weird to have the old multitool while simultaneously having the new tools

## Changelog
:cl:
imageadd: New sprites for items that were missing such as multitools, analyzers, geiger counters, t-ray scanners, and a few others
imageadd: New sprites for engineer and CE belts
tweak: Made so the jaws of life and the drill show up as white instead of yellow in the belt sprite
/:cl:

### CODE REVIEW

**Comment by SharkeeByond** [comment]
Please post images of the sprites.

**Comment by bluey89962** [comment]
Some of the tools
sprites
Belts
belts
Belt w/ tools
fullbelt
Flamethrower
flame
Plunger
plunger

These should be most if not all of them

**Review by Jalleo — APPROVED** [review]
I personally approve but I will wait for another with authority to merge it as there might be something they notice which is a issue.

**Comment by Karmic-Skink** [comment]
Change the CL to reflect images rather then features please, ie imageadd

**Comment by bluey89962** [comment]
> 
> 
> Change the CL to reflect images rather then features please, ie imageadd

done

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
