### PR TITLE
Comments out wallstuns

### PR DESCRIPTION
**Pull request by Cenrus**
Rebalances tazers by removing wallstuns. People have complained about them and they cause bugs (Hulks/Xenos endlessly wallslamming).

:cl:
del: disabled wallstuns
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Define the bugs with hulks and such

**Comment by PowerfulBacon** [comment]
Wallstuns removed entirely? Rest in peace space lube.

**Comment by GoatMonarch** [comment]
> Define the bugs with hulks and such

I theorize that given hulks are stun immune, if they walk into a wall it'll just repeatedly cause them damage. Or it completely breaks the single cause as to why hulk is good, by stunning you anyways.

As for the PR, I am kind of on the mix. I think wallstuns from confusion are really dumb, but you ought to also re-enable simple stuns from sources like space lube (so it isn't a lethal and deadly tool like how it is currently, and actually returns to it being fun to use), and make the HoS' gun taser shot more than just a very short stun that you can't do anything with.

**Comment by Kmc2000** [comment]
I think the core issue with this is confusion and this kinda just bandaids over the problem

**Pull request closed without merging**
