### PR TITLE
New fob map and .json

### PR DESCRIPTION
**Pull request by theboy6545**
the new bits for the new fob for the jeppison

## About The Pull Request

 Replaces the jeppisons old FOB with a new slightly new fob which hopefully is less hated  

## Why It's Good For The Game

i've heard a lot of complaints about the old FOB, so i make new one 

## Changelog
:cl:
add: new fob
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Should consider a more appropriate file name than "new_fob".

**Comment by covertcorvid** [comment]
Why did you delete one of the random rooms?

**Comment by covertcorvid** [comment]
- Remove hull armor from under the walls for the airlocks
- Consider adding flak
- Consider adding showers
- Is that gibtonite on the table?
- What's the pill bottle?
- Consider adding a shower
- What's the pinpointer in space?
- You should probably add a SMES
- Equal numbers of lockers and suits are nice
- On that note, wood for more boxes
- An O2 canister for refilling tanks is nice
- Welders and a welding fuel tank are good for repairing the hull. Or hull repair foam if you want to be really nice.
- Is there anywhere they can get glasses for the bar from?
- Is there a tcomms relay that I'm missing?

**Comment by theboy6545** [comment]
> * Remove hull armor from under the walls for the airlocks will do
> * Consider adding flak will do
> * Consider adding showers 
> * Is that gibtonite on the table? Yes (was a named piece named rock johnson)
> * What's the pill bottle? Floorpills
> * Consider adding a shower Will add
> * What's the pinpointer in space? The shuttle spawner
> * You should probably add a SMES
> * Equal numbers of lockers and suits are nice
> * On that note, wood for more boxes Will add
> * An O2 canister for refilling tanks is nice Will add
> * Welders and a welding fuel tank are good for repairing the hull. Or hull repair foam if you want to be really nice. Will add.
> * Is there anywhere they can get glasses for the bar from? There is a box of glasses at the bar, and the booze o mat in the kitchen
> * Is there a tcomms relay that I'm missing? No

**Comment by theboy6545** [comment]
alright, made some of the suggested changes, and the name has been changed to the pequod

**Comment by francinum** [comment]
Changelog has no closing tag

**Comment by Vasily2013** [comment]
Okay, this is separate from a change request because it's more subjective than objective. This still seems really open and spacious. There's not a lot of flavor to it, and for the most part moving from one room to another feels rather uniform. I really want to see some more detail, items, tables, or decals put to use to bring this thing to life.

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
- [x] Air alarms do not go in the walls. If they are in the walls they will properly detect the issue with the air you can not breathe. Use the directional subtypes that fit on the walls like all the other ships use.
- [x] The airlocks leading out to the mining platform are not configured properly. Please see the main ship for examples.

**Comment by theboy6545** [comment]
> * [ ]  The airlocks leading out to the mining platform are not configured properly. Please see the main ship for examples works for me?
> * [ ]  Air alarms do not go in the walls. If they are in the walls they will properly detect the issue with the air you can not breathe. Use the directional subtypes that fit on the walls like all the other ships use. didnt know this, will fix it.

**Comment by theboy6545** [comment]
ive made the walls into the iron ones to fit the industrial vibe, and some other stuff

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
- [x] Your scrubbers to distro line still double pipes with the air tank.
- [x] you use area/ruins/space/has_grav/onehalf/dorms_med. Don't use ruin areas in your map.
- [x]  Your areas mix and match between nostromo and rocinante. Please correct this to only use one set of areas.
- [x]  Remove the tiny fan under the mining shuttle dock airlock. If you think the mining team is so stupid they need it there it should be an airlock.
- [x] The wall under the epi poster that leads to dorms there is a titanium wall. This is true of all posters that I look at. Is this intentional?
- [x] add /area/space/nearstation to the asteroid cage.
- [ ] Add an air alarm to the weapons/kitchen room.
- [ ] Add Fire Alarms to the main shuttle dock and the weapons room.
- [ ] The airlock piping still does not fit the standard configuration used on the main ships and all other fob maps.
- [ ] You have a couple stripes of distro piping that are completely disconnected from anything in the middle of the ship.

Once again, the main areas look fairly bland. The crew quarters area is fine, but otherwise it's very **very** grey, and in some areas is very open in terms of space.

**Comment by theboy6545** [comment]
> * [ ]   Remove the tiny fan under the mining shuttle dock airlock. If you think the mining team is so stupid they need it there it should be an airlock. I stole the airlock area from the FOB itself because i didnt understand the shuttle controller thing, tinyfan and all.

**Comment by Bastian0930** [comment]
Only a few suggestions from me. 
- The current iron walls are the ugliest sprites I've ever seen, and I really really suggest changing walls.  
- Cargo lathe isn't hooked to the ore silo.
I'll continue adding as I go. I'm gonna circle a few things on my phone, then add the picture.

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
Still changes the Jepp's .Json

**Comment by theboy6545** [comment]
> Still changes the Jepp's .Json

That's because it is a replacement for the FOB

**Comment by theboy6545** [comment]
@Vasily2013 fixed the json being changed

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
Okay, maybe I was unclear.

I'm not going to establish this as the new FOB for the Jeppison, regardless of if you use a different .dmm or if you just copy paste your fob into the old one and overwrite what was there. Here's the reasoning.

The Jeppison fob is supposed to not be ideal, it's supposed to feel tight and cramped, it's supposed to make miners want to do their jobs, slip back to the ship, and deliver goods and perhaps help out when populations are dwindling. Are there ways to increase the flow? Sure, probably, but a lot of those can likely be done in-game, or they could be specifically referenced in fixes rather than ripping out the entire map. I'm Jeppison's creator, and until I see good evidence that it's not feasible to fix the fob currently in place then I'm not changing it. Unless you want me to change it to the original FOB for Vago...

**Comment by triplezeta** [comment]
image

**Comment by theboy6545** [comment]
Im gonna close the PR even though I disagree with what Clerical has said, because it is clear that I cannot change his mind on this. Thanks to everyone who helped me make it, lets hope next time works out better.

**Pull request closed without merging**
