### PR TITLE
le crackpipe

### PR DESCRIPTION
**Pull request by BootlegBow**
## About The Pull Request

adds a crackpipe

## Why It's Good For The Game

image

## Changelog
:cl:
add: crackpipe
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
Today on how to code crackpipes, you get someone else to do it

**Comment by athena413** [comment]
luqnf2opx6fub6apceix

**Comment by RemervKeberb** [comment]
Sigma god the 2th

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
Administrative veto

**Review by Karmic-Skink — CHANGES_REQUESTED** [review]
No.

**Comment by Pontenerd** [comment]
Is there any reason this wasn't closed by maintainers? I assumed a adminstrative veto would mean that the PR will be closed

**Comment by BootlegBow** [comment]
so should i close the pr orrrrr

**Comment by RemervKeberb** [comment]
Remember what they denied you

**Comment by BootlegBow** [comment]
this pr is still fucking open?

**Comment by Bokkiewokkie** [comment]
> this pr is still fucking open?

It's your PR, you can choose to close it whenever you want. But I'll do it for you this time.

**Pull request closed without merging**
