### PR TITLE
Fighter fuel changes + nsv reagents cleanup

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request
Lore buff

Renames "hydrocarbon" to methane and changes it's description. Before it sounded exactly like oil

Hydrocarbon/Methane now requires 4 parts hydrogen and one part carbon instead of 1:1, formation temperature has been increased to fix morphine recipe conflict

Cleans up NSV reagents, everything has been moved into folders and files corresponding with bee's layout, instead of everything being dumped in recipes.dm

## Why It's Good For The Game

Hydrocarbon was a functional clone of oil, methane opens up more recipes. 
(Lore)

## Changelog
:cl:
tweak: Renames hydrocarbon to methane
tweak: Changes hydrocarbon/methane reaction temperature to 520k
tweak: Hydrocarbon/methane now uses 3 hydrogen and 1 carbon
code: Cleans up NSV reagent files
fix: Morphine no longer conflicts with hydrocarbon/methane recipe
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
Will make wiki changes if approved

**Comment by Bokkiewokkie** [comment]
[Comment about methane actually consisting of 4 parts hydrogen and 1 part carbon]

**Comment by TheFakeElon** [comment]
BRAIN FART

**Comment by TheFakeElon** [comment]
wiki updated <3

**Review by covertcorvid — APPROVED** [review]

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
