### PR TITLE
Ports oozelings and several oozeling fixes from upstream [READY]

### PR DESCRIPTION
**Pull request by DrSirKnight**
## About The Pull Request
Ports: https://github.com/BeeStation/BeeStation-Hornet/pull/3322 and https://github.com/BeeStation/BeeStation-Hornet/pull/3483
This doesn't port the medibot fix as I find that medibots shouldn't heal oozelings, just like they don't heal slimepeople.

## Why It's Good For The Game

A lot of people want to play as slimes

## Changelog
:cl:
add: Added a new race called Oozelings
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
CL is misleading as this won't add them as round start due to gameconfigs being set on individual boxes, not via PRs.

**Comment by ro5490** [comment]
Still mid-patching, as some of the things I added to fix things, are redundant
Theres also several bugs still it seems, which I'll be working on over the next few days.

**Review by Jalleo — COMMENTED** [review]
I personally dont need more roundstart races that are memes. If we end up getting it from a general update from Bee so be it. If there is a majority of the players that want it or Kmc wants it that's fine.

**Comment by DrSirKnight** [comment]
> 
> 
> I personally dont need more roundstart races that are memes. If we end up getting it from a general update from Bee so be it. If there is a majority of the players that want it or Kmc wants it that's fine.

The reason I ported this is because we got several players who want a roundstart slimepeople race. We could have someone hold a vote in talkpoints to see how many players actually want this race?

**Comment by GoatMonarch** [comment]
> > I personally dont need more roundstart races that are memes. If we end up getting it from a general update from Bee so be it. If there is a majority of the players that want it or Kmc wants it that's fine.
> 
> The reason I ported this is because we got several players who want a roundstart slimepeople race. We could have someone hold a vote in talkpoints to see how many players actually want this race?

I mean, it's just a cosmetic choice, with minor gameplay diferences. Adding new species leads to a couple of players being more happy with what they play as. Nothing wrong with that.
Then there's just the part of every SS13 community that thinks that adding new races are a bad thing. Muh human supremacy and so on. This group of players are just actively shunning the fun of others for little to no reason, so having a vote about it is kinda unecesary.

**Comment by Pontenerd** [comment]
I personally don't see the harm of introducing oozelings, it gives medical a new race to learn how to treat, and gives players more options for races to play, the only actual complaints I have heard is people not wanting xeno races

**Comment by Kmc2000** [comment]
Thanks for the effort, but this is now obsolesced by the rebase
o7

**Pull request closed without merging**
