### PR TITLE
ATC Comms for miners

### PR DESCRIPTION
**Pull request by SerynEngi**
## About The Pull Request

Adds an ATC key to miner default spawn equipment

## Why It's Good For The Game

We like miners on ATC comms, but we hate it when everyone has ATC comms. This ensures that miners spawn with ATC comms and don't have to go hunting for it, and its not found anywhere else (such as a mining headset).

</details>

## Changelog
:cl:
add: Pilot encryption key to shaft miner starting equipment
/:cl:

### CODE REVIEW

**Comment by SerynEngi** [comment]
So, I tossed this up because I thought it reasonable for miners to have this here (on NSV) after someone suggested it, and it was pointed out that doing it this way is easier than mapping it.

If the team thinks this should go into miner conscription kits and/or mining radio headsets, I'll do so, but I thought it more reasonable to just keep it in the spawn equipment.

**Comment by Karmic-Skink** [comment]
This should hopefully soon be made redundant by an overhaul to overmap comms systems.

**Comment by SerynEngi** [comment]
> > This should hopefully soon be made redundant by an overhaul to overmap comms systems.
> > Note for headcoder: This aspect is actually fully complete ^.
> 
> Cool stuff. Once the rework arrives we can remove the keys again, naturally.

Hell, I'll even do so myself. It wasn't exactly very difficult to add.

**Comment by Karmic-Skink** [comment]
Yeah I'd already flagged it as an issue, just haven't finished the rest of the features in that PR.

I'll just need to remember the key got added here.

**Review by covertcorvid — APPROVED** [review]

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
