### PR TITLE
Jolly Sausage REEEWorks

### PR DESCRIPTION
**Pull request by Reziro**
## About The Pull Request
This is my first PR ever so please bear with me.

Hoo boy, this has been my project for like a month. A lot has been changed to hopefully make the sausage a little bit less hated. I collected a list of changes people wanted and tried to implement them to the best of my current abilities. I've never mapped anything before so I don't doubt that I messed something up.

List of changes:
Moved Cargo to be across from Munitions
Moved Medbay to be next door to Science and Cargo
Put Security where Medbay used to be because it made the most sense?
Expanded Munitions upwards slightly to fit in a MAC Cannon
Fixed the Cargo Conveyors
Wired the armor pumps to the engine instead of the grid
Gutted and altered Atmospherics without ending up in the psych ward
Moved the plasma tank near RD's office to be less exposed since it gets blown up every round. The cooling loop is still exposed.
Added the Happy Hotdog arcade! I didn't know what to put in the empty space, suggestions welcome.

## Why It's Good For The Game
If people are complaining it's broken every time it gets selected then clearly something needs to be changed. The changes I've made are all based on direct feedback I've seen in game, on Discord and on Github. Even if there are problems with my changes this should at least give people a starting point to work from. I 100% welcome any feedback.

## Changelog
:cl:
add: Added the Happy Hotdog arcade to Jolly Sausage
add: Added a MAC cannon to the Munitions department on Jolly Sausage
tweak: Increased the size of Munitions on Jolly Sausage
tweak: Moved Cargo, Medbay and Security on Jolly Sausage
tweak: Replaced Atmospherics on Jolly Sausage
tweak: Moved the RD toxin tank
fix: Connected Jolly Sausage armor pumps directly to engine
fix: Corrected Cargo conveyor directions on Jolly Sausage
/:cl:

### CODE REVIEW

**Comment by Reziro** [comment]
Not sure why Travis is being slow but I think this should be ready for an actual review.

**Comment by Vasily2013** [comment]
@francinum I would like your take on this. 

I'd also appreciate it if you could add some gas miners to the atmos system, specifically Plasma, N2, and O2.

**Comment by francinum** [comment]
...this is all fucking great
really
you fixed like a majority of my problems with my own map

Please. Get rid of the hull plates though, they're unnecessary and only serve to clutter the outline of the ship.

**Comment by francinum** [comment]
Travis isn't used anymore, that's our fault, you'll need to update your repo to master.

**Comment by Reziro** [comment]
Roger, I'll work on the changes and push an update.

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
