### PR TITLE
Port tail entwining from tg, skyrat, citadel etc.

### PR DESCRIPTION
**Pull request by red031000**
## About The Pull Request

Ports tgstation/tgstation#54991 and Skyrat-SS13/Skyrat-tg#1702

Allows any player with a tail to entwine them with another player's tail to pull them

## Why It's Good For The Game

Flavour good, extremely based PR

## Changelog
:cl:
add: Adds tail entwining
/:cl:

### CODE REVIEW

**Comment by Absolutely-Steph** [comment]
This is a meme, absolutely based.

**Comment by Bokkiewokkie** [comment]
You will not the tails

**Comment by DeltaFire15** [comment]
:pensive:

**Comment by red031000** [comment]
tragedy

**Pull request closed without merging**
