### PR TITLE
Mining Ship Tweaks

### PR DESCRIPTION
**Pull request by TheChaser212**
## About The Pull Request
Replaces a bunch of references to the nostromo so they're more generic and makes the mining ship's FTL computer speak on the supply channel rather than engineering.

## Why It's Good For The Game
The nostromo isn't really used anymore and having more generic names allows for different mining ships. Having the FTL computer speak on the engineering channel just confuses people and doesn't let miners know when the ship is ready to jump.

## Changelog
:cl:
tweak: Mining FTL now talks on the supply channel
tweak: Removed a bunch of references to the Nostromo
/:cl:

### CODE REVIEW

**Comment by Vasily2013** [comment]
@Kmc2000 considering you built the mining system I'd like your okay before test merging this. When it's good in your eyes for testing let me know and I can throw it on.

**Comment by Kmc2000** [comment]
Yup this should be fine

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
Signal boost on the merge conflicts. I'll be looking at this again on or about the 27th and will close it at that time if it hasn't been updated.

**Comment by TheChaser212** [comment]
Ok I'm pretty sure that fixed the conflict.

**Review by Vasily2013 — APPROVED** [review]
Based, might cause problems for #999 but likely won't be too bad to recrtify.

**Pull request merged**
