### PR TITLE
Removes lag-machine from Galactica

### PR DESCRIPTION
**Pull request by Corsaka**
## About The Pull Request
removes radiant dance machine from being present roundstart on galactica
it lag bad

## Why It's Good For The Game
lag bad

## Changelog
:cl:
del: Removed radiant dance machine on Galactica
/:cl:

### CODE REVIEW

**Comment by Corsaka** [comment]
I, uh, don't know what a map merger is.

**Comment by GoatMonarch** [comment]
This is peak github, given you deleted one object, and somehow caused 6412 additions, and 145,585 removals.

Also in it's defense: The dance machine requires theatre access. Only the clown, mime, XO and captain are able to activate it. Or requiring an engineer cyborg in terms of silicons.

The only place lag comes from is your client quickly getting the music file. Possibility of the particles if you're somehow running the server on a potatoe.
The mining ship has a music machine as well, that's less obnoxious, but ship wide.



> I, uh, don't know what a map merger is.

Serverfork>tools>mapmerge2>dmm2tgm
Make sure you got java/c++ (forgot what code language. Think it was java) installed through vissual studios for it to be active. Start the file, select the map you edited and it should be converted.

**Comment by Jalleo** [comment]
Its python that you need for it.

**Comment by francinum** [comment]
@GoatMonarch Do realize that this pretty much causes lightmaps to recalculate *constantly*, plays a seriously large amount of effects, uses timers to force mobs into strange animations (which comes with a stun), and was coded by an absolute idiot.

**Comment by GoatMonarch** [comment]
> @GoatMonarch Do realize that this pretty much causes lightmaps to recalculate _constantly_, plays a seriously large amount of effects, uses timers to force mobs into strange animations (which comes with a stun), and was coded by an absolute idiot.

Well shid. All up for the removal then, may have to look into if jukeboxes are a suitable replacement. For the future. :thonk:

**Comment by Cenrus** [comment]
Has been removed so this PR can be closed.

**Comment by Vasily2013** [comment]
Closing due to this being fixed through another PR.

**Pull request closed without merging**
