### PR TITLE
renames ranks

### PR DESCRIPTION
**Pull request by captainwiseguy**
## About The Pull Request
changes ranks

## Why It's Good For The Game
ranks were bad before, now they are ok

## Changelog
:cl:
config: changed ranks
/:cl:

### CODE REVIEW

**Comment by covertcorvid** [comment]
Please just make a new config file instead of changing the existing one

**Comment by captainwiseguy** [comment]
i made a new config file

**Comment by covertcorvid** [comment]
Was looking at the descriptions on the first commits sorry 👍

**Comment by captainwiseguy** [comment]
all good

**Comment by captainwiseguy** [comment]
> Isn't this meant to be under config/ranks?

it is under config


> Out of curiosity, why are all heads listed as officers except MAA? Additionally, why do the CE and CMO outrank HOS? RD I can understand, just curious on the reasoning there.

being a space engineer or space surgeon would require a lot of knowledge in their field, and when the crew is getting bombarded by syndicate ships and infected with xenomorph larvae, im sure CC would like to make sure they know their shit. anyways, what good star trek CE and CMO wasnt at least a lieutenant commander

also HOS is a junior officer because junior officers are (usually) in their prime, considering theyre in the age range of 20 - 35, so if push comes to shove the HOS can realistically bend some ass

**Comment by francinum** [comment]
Dirty changelog.

Please put rank lists on the forums at https://nsv.beestation13.com/phpBB3/viewforum.php?f=20

**Pull request closed without merging**
