### PR TITLE
Renames Station Engineers to Ship Engineers

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Renames all instances of "Station Engineer" to "Ship Engineer".
Welcome to FTL13 2

## Why It's Good For The Game

Renames Engies to a name that's more suitable for the theme of the server.

## Changelog

:cl:
tweak: Station Engineers are now called Ship Engineers, because they aren't on a station.
/:cl:

### CODE REVIEW

**Comment by Corsaka** [comment]
Has same issue as HoP rename with integration from upstream - do we want to go to the effort of renaming a few things every update

**Comment by Cenrus** [comment]
Fortunately this PR doesn't nearly have as many changes as the XO conversation. I didn't need to change any clothing typepaths.

**Comment by Jalleo** [comment]
I honestly would like to go the route of children in the NSV code section that replaces all the names with ship. Just for ease of upstream.

**Comment by Corsaka** [comment]
@Jalleo How does upstream merges work if it finds differences that weren't changed in a recent commit? Will it go into merge-conflict mode? If so, we can easily solve that on a case-by-case basis.

**Comment by Karmic-Skink** [comment]
> Has same issue as HoP rename with integration from upstream - do we want to go to the effort of renaming a few things every update
> @Karmic-Skink ; how is this related to mapping, or is the freeze on every single map until something changes?

The freeze is on anything that changes a map file until the starmap PR is merged.

**Comment by Karmic-Skink** [comment]
Also can you please confirm you have regenerated the landmarks via the ingame debug tool?

**Comment by Jalleo** [comment]
I have put a do not merge tag on this PR and https://github.com/BeeStation/NSV13/pull/518 because I honestly believe it will cause headaches for every attempt we do afterwards for upstream merges. This codebase needs to investigate a better method to handle this instead of a simple and "easy" direct rewrite of every instance of those names.

**Comment by Jalleo** [comment]
I am closing this PR because it edits maps and we are planning to update right now its going to conflict one way or another when we merge all the newer code in.

**Pull request closed without merging**
