### PR TITLE
NSV Jolly Sausage: Hammerhead 2

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request

Low-Medpop ship.

I can't believe it's not a flavor of Vago

## Why It's Good For The Game

Hammerhead 2: Vago Boogaloo

## Remaining Checklist

- [x] Firedoors

- [x] Intercom Checks

- [ ] Detailed Cameras 

## Changelog
:cl:
add: NSV Jolly Sausage, a new low-med pop ship with reduced facilities.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Actual merge blocked by rebase.

**Comment by Firefox13** [comment]
I just stumbled upon this PR and now you're going to listen to my feedback.
**INHALES**
Don't we have different type of windows for exterior windows?
изображение
Looks empty, add chairs/vendor/decals and stuff
изображение
.
**No R-walls at all.**
.
**what**
изображение
Add better chairs, they deserve it.
изображение
Where's captain chair. Also we use shuttle chairs there, not office chairs.
изображение
This "appendix" not required at all, just make XO office bigger. XO office looks empty, lacks PDA painter. Take an example from metastation HoP office, it's glorious.
изображение
изображение
Please don't, detective equipment will get quickly looted. Also he needs sunglasses.
изображение
Fire hazard, replace it with usual tiles. Looks gross as fuck.
изображение
Don't we use different tiles for hallways?
изображение
No, please.
изображение
Just make a normal airlock, without bolting behind a table.
изображение
wow so much empty space, add a small office
изображение
What is this even for?
изображение
**Fuck you.**
изображение
**Fuck you.**
изображение
Where's reflective vest?
изображение
Unnecessary labyrinth. Every maintenance tunnel on this codebase looks very fucking empty. Enterprise maint tunnels has LIGHTS in them. Why?!
изображение
Add a maintenance entry, make service break room smaller, make freezer&kitchen bigger. Why the fuck service break room is so big in the first place?
изображение
Make it bigger. Add actual tables for eating.
изображение
I don't even want to fucking think what that ammo box is for.
изображение
Autolathe is unnecessary, relocate crate and whatever it contains to atrium, make atrium smalles, remove those sick consoles from Galactica.
изображение
Linoleum will get dirty with that ash from crematorium.
изображение
I can't fucking hear chaplain from the last bench.
изображение
**I just want to fucking snap your neck for this medbay entry.**
изображение
Switch chemistry desk and "actual" entry places. Remove that gross fucking airlock double doors I HATE THEM.
*exhales.*
*inhales.*
*scream
Hey, you lost some floor tiles under those tables.
изображение
Decals.
изображение
Too fucking big office, makes it dark tiles/blue carpet. Lacks fucking CMO LOCKER. What are those book shelves even for? For storing WGW?
изображение
nice placement
изображение
No atrium, add plasteel in atrium, maybe a console and a table.
изображение
sad no curator desk
изображение
Are you kidding me?
изображение
I think we will port R&D point generation so I'll snap your neck once more. Where's fucking AI board? Where's fucking CHAIR for sitting on? Add some protection, remove shitload of wooden tiles everywhere, replace them with metal/checkered tiles.
изображение
Wow nice empty hallway.
изображение
.
**No xenobiology, at all. That will be another neck snap.**
>
I'm sorry? What is this for?
изображение
Add more tables. Add metal&glass&plasteel&flashes&powercells. Please remove that console from that airlock because people will get pushed.
изображение
You either struggle with toxins or you hate TTVs. I hope it's the first one and I'm willing to assist you with it. But this toxins room fucking too big and it sucks, like at every other map.
изображение
big empty room
изображение
no starting resources, batteries, some basic stock parts, but a memorial plushie in missing xenobiologist. RIP, xenobiologist.
изображение
*silence*
изображение
Where's warehouse???
you lost cyclelink airlock helper there.
изображение
Can't you fucking use one type of airlocks? Add decals under showers.
изображение
What the fuck.
изображение
I'm sorry?
изображение
Hey mister, you lost atmospherics somewhere. That will be another neck snap.
изображение
Can't you fucking stack them near the wall?
изображение
:disappointed: :gun: 
изображение
You lost normal patient rooms, beds, tables, lockers. They aren't used, but they're nice to have. You're removing the comfort and RP from the game.
изображение
Can't you fucking merge those two rooms together or atleast make them near each other.
изображение
Where are EOD suits. Vault doors?
изображение
Appendix.
изображение
Too big, either add stuff or halve the room.
изображение
Can't you just NOT USE ANOTHER COMMAND HALLWAY FOR IT?
изображение
That's arrivals/ferry I guess. Add some "recreating stuff", a table or two, maybe a fire safety closet. Just move those windows one tile north and add some stuff in resulting place.
изображение
Shouldn't they have red&greed decals? They look better and they are on meta or delta I think.
изображение
Add a fucking indestructible wall, not some rip-off plastitanium, Also, missing lights.
изображение
Nice.
изображение
That's very fucking big corridor. Just make it like on meta.
изображение
изображение
Pinpointer.
изображение
NOT HERE, JOHN, NOT HERE, IN THE CAP'S ROOM.
изображение
You're not supposed to make rooms for it, just strap them right onto the hull.
изображение
We get TWO surgery tables by default. Where's the second one?
изображение
You like corridors, don't you. It's very long and really tight.
изображение
Gonna push that geneticist over there to get to my workplace... Hey, why you're injecting hulk into yourself? OH GOD N-
изображение
Nice empty hallway.
изображение
Hey... I don't see any brig medbay here.
изображение
Big, LACKS HIS FUCKING CLOSET, replace wooden the metal, because our HoSs are BRUTAL.
изображение
nice.
изображение
*"hey... Where did the bodies go?"* No morgue.
изображение
OXYGEN, NOT AIR. JUST SACRIFICE THOSE ONE MAIN USELESS HALLWAY TILE TO ADD SPACE FOR CANISTERS GODAMMIT.
изображение
Awful core.
изображение
Tech storage really isn't supposed to have tech entry. Where's hi-security tech storage? It should be finished, not half-done by default(tiles).
изображение
Hey yo you lost some O2 canisters.
изображение
Hey yo you lost some AIR canisters.
изображение
Fire axe supposed to be in ATMOSPHERICS. It's fire axe for a reson.
изображение
Getting to that light fighter going to be a headache.
изображение
Blast doors.
изображение
Blast doors.
изображение
:cry: :gun:
изображение
Medbay lacks latex gloves boxes and sterile masks gloves, as every other medbay on this codebase does. Fun.
изображение
Why the fuck there are firelocks on O2 and plasma canisters? It's not supposed to be like that.
изображение

You actually like space corridors, aren't you
изображение

**Comment by Firefox13** [comment]
Put vault here.
изображение
Put atmospherics here, make the cargo bay bigger, make the mining shuttle point other direction.
изображение

**Comment by francinum** [comment]
oh thank fuck finally some fucking feedback.

**Comment by francinum** [comment]
> Don't we have different type of windows for exterior windows?
Yes. They're awful so I elect not to use them. Fight KMC over making their sprite not godawful first.
> Looks empty, add chairs/vendor/decals and stuff
It's a storage closet?
> No R-walls at all.
yeah I need to actually do a security pass.
> what
suffer
> Add better chairs, they deserve it.
no they don't
> Where's captain chair. Also we use shuttle chairs there, not office chairs.
The captain doesn't need to be involved in flying the ship at all times. Might switch the chairs.
> This "appendix" not required at all, just make XO office bigger. XO office looks empty, lacks PDA painter. Take an example from metastation HoP office, it's glorious.
It's oversized and grossly wasteful already.
> Please don't, detective equipment will get quickly looted. Also he needs sunglasses.
If they make off with the closet and break it, fair game. They don't have roundstart access to it.
> Fire hazard, replace it with usual tiles. Looks gross as fuck.
you try detailing a horribly boring hallway that has to exist for consistency reasons. I might throw some carpet in in a vague attempt to care.
> Don't we use different tiles for hallways?
No.
> No, please.
Tool storage doesn't exist. Give me a better place to put it then.
> Just make a normal airlock, without bolting behind a table.
I completely forgot to remove that actually.
> wow so much empty space, add a small office
I went over this with KMC. There's no way to do that that doesn't make this place a fucking bitch to navigate.
> What is this even for?
the armory.
> Fuck you.
**suffer**
> Fuck you.
( ͡° ͜ʖ ͡°)
> Where's reflective vest?
Hell. Where it belongs. I plan to merge the PR that replaces it's objective.
> Unnecessary labyrinth. Every maintenance tunnel on this codebase looks very fucking empty. Enterprise maint tunnels has LIGHTS in them. Why?!
Haven't done a maintenance pass.
> Add a maintenance entry, make service break room smaller, make freezer&kitchen bigger. Why the fuck service break room is so big in the first place?
Sure. The service break room is big because it's either that or I make maintenance wideboye.
> Make it bigger. Add actual tables for eating.
No. Get the fuck back to work.
> I don't even want to fucking think what that ammo box is for.
It's a stylistic replacement for the box of beanbags the bartender normally gets.
> Autolathe is unnecessary, relocate crate and whatever it contains to atrium, make atrium smalles, remove those sick consoles from Galactica.
Autolathe sure. The crate stays. I'll replace the consoles.
> Linoleum will get dirty with that ash from crematorium.
h o w u n f o r t u n a t e
> I can't fucking hear chaplain from the last bench.
radio televangelism is the future anyways.
> I just want to fucking snap your neck for this medbay entry.
*your suffering fills me with joy*
> Switch chemistry desk and "actual" entry places. Remove that gross fucking airlock double doors I HATE
No.
> Hey, you lost some floor tiles under those tables.
you realize you never put tiling under tables, right?
> Decals.
I'm not okand. Sorry.
>Too fucking big office, makes it dark tiles/blue carpet. Lacks fucking CMO LOCKER. What are those book shelves even for? For storing WGW?
OH FOR FUCKS SAKE. It's called flavor.
> nice placement
It's fucking fine.
> No atrium, add plasteel in atrium, maybe a console and a table.
hah. what other map gives them the luxury. and that *is* the atrium.
> sad no curator desk
`MAP_REMOVE_JOB(curator)`
> Are you kidding me?
it deserves no respect and exists purely because events reference it.
> I think we will port R&D point generation so I'll snap your neck once more. Where's fucking AI board? Where's fucking CHAIR for sitting on? Add some protection, remove shitload of wooden tiles everywhere, replace them with metal/checkered tiles.
AI board sure. The rest? No.
> Wow nice empty hallway.
wow useless fucking feedback. You want me to make this like the hammerhead and give you another dead end hallway to nowhere?
> No xenobiology, at all. That will be another neck snap.
*they have no imperial right to existence*
> I'm sorry? What is this for?
To segment the bomb range from the rest of toxins. Like every other map does?
> Add more tables. Add metal&glass&plasteel&flashes&powercells. Please remove that console from that airlock because people will get pushed.
you try fitting that in and making it not violently cramped. you really shouldn't be at that console for longer than 5 seconds anyways.
> You either struggle with toxins or you hate TTVs. I hope it's the first one and I'm willing to assist you with it. But this toxins room fucking too big and it sucks, like at every other map.
take the RPD and do it yourself fuckboy.
> big empty room
yes and?
> no starting resources, batteries, some basic stock parts, but a memorial plushie in missing xenobiologist. RIP, xenobiologist.
sure.
> silence
explain.
> you lost cyclelink airlock helper there.
sure.
> Can't you fucking use one type of airlocks? Add decals under showers.
No. Sure.
> What the fuck.
die
> I'm sorry?
see above
> Hey mister, you lost atmospherics somewhere. That will be another neck snap.
`MAP_REMOVE_JOB(atmos)`
> Can't you fucking stack them near the wall?
you act like wallspace isn't very clearly at a fucking premium
>😞 🔫
k
> You lost normal patient rooms, beds, tables, lockers. They aren't used, but they're nice to have. You're removing the comfort and RP from the game.
monke go brrr
> Can't you fucking merge those two rooms together or atleast make them near each other.
No.
> Where are EOD suits. Vault doors?
The vault doors are busted as fuck. I'll add EOD suits
> Appendix.
like this particular feedback, utterly useless.
> Too big, either add stuff or halve the room.
I'm tempted to cut it entirely but it needs to exist because of the way overmap docking is coded.
> Can't you just NOT USE ANOTHER COMMAND HALLWAY FOR IT?
No.
> That's arrivals/ferry I guess. Add some "recreating stuff", a table or two, maybe a fire safety closet. Just move those windows one tile north and add some stuff in resulting place.
don't linger in a literal appendix of an area. Get the fuck back to work.
> Shouldn't they have red&greed decals? They look better and they are on meta or delta I think.
Completely nonstandard.
> Add a fucking indestructible wall, not some rip-off plastitanium, Also, missing lights.
They are... /turf/closed/indestructible/shuttle/dark
> Nice.
Cool.
> That's very fucking big corridor. Just make it like on meta.
How to make the HoP office look stretched and distended: follow this suggestion.
> Pinpointer.
No.
> NOT HERE, JOHN, NOT HERE, IN THE CAP'S ROOM.
Maybe someone will actually fucking take it if I put it here.
> You're not supposed to make rooms for it, just strap them right onto the hull.
Entirely personal choice. Bite me.
> We get TWO surgery tables by default. Where's the second one?
my god I spoiled you with hammerhead didn't I...
> You like corridors, don't you. It's very long and really tight.
oh hey it's medbay round two.
> Gonna push that geneticist over there to get to my workplace... Hey, why you're injecting hulk into yourself? OH GOD N-
you have words. use them.
> Nice empty hallway.
*GET THE FUCK BACK TO YOUR DEPARTMENT*
> Hey... I don't see any brig medbay here.
`MAP_REMOVE_JOB(brig_phys)`
> Big, LACKS HIS FUCKING CLOSET, replace wooden the metal, because our HoSes are BRUTAL.
Closet, sure, the rest? f u c k y o u
> nice.
has shutters. close them bitch.
> "hey... Where did the bodies go?" No morgue.
the chef would appreciate your business.
> OXYGEN, NOT AIR. JUST SACRIFICE THOSE ONE MAIN USELESS HALLWAY TILE TO ADD SPACE FOR CANISTERS GODAMMIT.
It works.
> Awful core.
yeah it kinda is. I'll redesign it.
> Tech storage really isn't supposed to have maint tunnel entry. Where's hi-security tech storage? It should be finished, not half-done by default(tiles).
have you seen pubby? Secure tech storage is in the gravgen atrium. Fight me on that last one, have you *seen* box tech storage?
> Hey yo you lost some O2 canisters.
if you fuck up that bad order them from cargo. otherwise tap the main gas tank yourself you lazy fuck.
> Hey yo you lost some AIR canisters.
make your own.
> Fire axe supposed to be in ATMOSPHERICS. It's fire axe for a reson.
atmos doesn't exist. CE acquires it by seniority.
> Getting to that light fighter going to be a headache.
you have one pilot. you have time to play plane jenga.
> Blast doors.
Sure.
> Blast doors.
sure
> 😢 🔫
you're repeating yourself.
> Medbay lacks latex gloves boxes and sterile masks gloves, as every other medbay on this codebase does. Fun.
Fair cop.
> Why the fuck there are firelocks on O2 and plasma canisters? It's not supposed to be like that.
Would you prefer I just hand you boxstation with thrusters or do you want at least an attempt at originality?
> You actually like space corridors, aren't you
I find them an interesting balance idea.
> Put vault here.
No.
> Put atmospherics here, make the cargo bay bigger, make the mining shuttle point other direction.
Atmospherics is staying integrated. Mining can have the space I don't plan to do anything with.

**Comment by GoatMonarch** [comment]
> MAP_REMOVE_JOB(clown)		//Rest in peace child.
0/10 worse than vago.

**Comment by Firefox13** [comment]
> It's a storage closet?

Then why it is so empty?

> It's oversized and grossly wasteful already.

yes I agree, make airlock one tier south and move corgi and filing cabinets too, like on the image.
изображение

> you try detailing a horribly boring hallway that has to exist for consistency reasons. I might throw some carpet in in a vague attempt to care.

I'm trying not to make a boring wooden-tiled that looks even more awful-ler. You might swap the wooden tiles and metal tiles in there, try adding some "recreation area", a few tables, or maybe A FUCKING TOOL STORAGE.
изображение

> your suffering fills me with joy

It's just going to be bitch-ass to navigate, really.

> It's fucking fine.

Put Runtime bed one tile south-er, and chair one tile west-er and it will be fucking fine.

> they have no imperial right to existence

Just put a grey extract and a xenobio boards somewhere, if *some person* actually decisive enough to go xenobio.

> you try fitting that in and making it not violently cramped. you really shouldn't be at that console for longer than 5 seconds anyways.

Tables here and here, go on, put resources there. Or racks with toolboxes and welding helmets?
изображение

> big empty room
yes and?

I thought it's LoWpOp MaP, StOp MaKiNg BiG UnNeCeSsArY rOoMs, reeeeeeeeee

> explain.

Discord.
изображение

> like this particular feedback, utterly useless.

I mean, three tile long one tile wide corridor isn't really useful, as this whole conversation.

> don't linger in a literal appendix of an area. Get the fuck back to work.

Sure, get a swift death from a fire/hi pressure/low pressure. Just add a fire safety closet, dammit.

> They are... /turf/closed/indestructible/shuttle/dark

Everyone puts centcom indestructibly walls there usually.

> How to make the HoP office look stretched and distended: follow this suggestion.

I followed this suggestion and made this. It's even smalled than your current HoP office!
изображение

> oh hey it's medbay round two.

Just add another airlock at the other end of medical storage, it will make it easier to navigate.

> the chef would appreciate your business.

People usually have ethics and don't eat each other, even if they are dead.

> if you fuck up that bad order them from cargo. otherwise tap the main gas tank yourself you lazy fuck.

Show me connection port.

> make your own.

Show me connection port.

> Would you prefer I just hand you boxstation with thrusters or do you want at least an attempt at originality?

Elaborate.

**Comment by Firefox13** [comment]
Also, if we're ballistic gang, why you can print AEGs?

**Comment by Firefox13** [comment]
Ahem!
Part one: ~~Botanics~~ Hydroponics.
http://prntscr.com/t1l30u
I'll use metastation hydroponics as exampl:
http://prntscr.com/t1l4s5
Problems:
Only 9 trays. It's really not enough, even for two botanists.  I suggest you should rearrange them, for easier movement and bigger amount of trays.
Suggested arrangement:
http://prntscr.com/t1l6oz
It brings amount of trays to whopping **14**, which is more than enough for two botanists.
**Zero** buckets. As far as I remember, botanists don't get them in their lockers/vendors. Please, add atleast one on watertank and another one on the table.
Missing hydroponics watertank, plant-b-gone spray bottle.
Missing all-in-one grinder.
Missing box of beakers and syringes.

Part two: Kitchen.
http://prntscr.com/t1lach
For example, we're going to use the sole logic.
Missing entry to hydroponics. If botanists are missing, chef is usually grows their own food. Please, add an entry from freezer or kitchen.
Food processor is located in freezer. It's usually used a lot in simple recipes, please relocate it to kitchen.
Missing meat spikes. Duh.
*Awful, labyrinth-like* placement in freezer, It's going to be pain in the ass to navigate in there. Relocate oil tank to service room.
Missing clothes vendor.

Part three: bar.
http://prntscr.com/t1lc7z
The whole problem is booze and soda dispensers located in backroom, they shouldn't be there.

**Comment by Firefox13** [comment]
~~I still wonder why these rooms exist.~~
http://prntscr.com/t1ldrr

**Comment by Firefox13** [comment]
Pete is going to beat shit out of monkey. Please move Pete back to her place, freezer.
http://prntscr.com/t45rut
L-light floor? Are you sure you don't want to put a sane gateway room?
http://prntscr.com/t45sdw
wallpiping wallpiping
http://prntscr.com/t45swf
R&D:
Missing cell charger, few batteries, lack manipulators and capacitors to start with...? Oh, and 50/50/20 metal/glass/copper to start with, too.
http://prntscr.com/t45tjt
I don't know, but those two glass sheet stacks just look... Awful.
http://prntscr.com/t45u0v
I just hope diagnostic HUD got actually that awful sprite or you just added diagHUD sunglasses there.
http://prntscr.com/t45ull
Still no chair.
http://prntscr.com/t45uxe
>no igniters in toxins rooms.
http://prntscr.com/t45v3z
>igniter in mix tank
http://prntscr.com/t45vb3
That AI anterchamber looks... Empty. Maybe a small office or turrets there?
http://prntscr.com/t45vrq
.
Just thought of stating that brig lacks training bomb, remembered about this thing.
изображение
.
Usually robotics surgery room has a usual/tinted glass and a windoor to separate rooms. And a morgue tray, too.
http://prntscr.com/t45xa6
~~that AI chamber looks neat, honestly.~~

**Comment by Vasily2013** [comment]
Please address all further issues with the map at the forum post linked below. 
https://forums-nsv.beestation13.com/t/jolly-sausage-superthread/177

**Comment by francinum** [comment]
Map will require further changes at a later date, but this fixes a few pretty noticeable issues as well and it's getting stale.

**Pull request merged**
