### PR TITLE
Monstermos compliance cleanout

### LINKED ISSUE #641: No prototype hardsuit
It says I should include round ID if I played tgstation servers.. I didn't.

## Testmerges:

Irrevelant

## Reproduction:

Go into toxins area
Open suit storage unit
Notice usual EVA suit, not the prototype.
Cry.

### LINKED ISSUE #644: [Enterprise] Door access bad
## Round ID:
Not relevant
## Testmerges:
Not relevant
## Reproduction:

Several service maintenance doors (and the incinerator) are all access or only have the maintenance access set.
Doors that have wrong access marked with a red box below:
image

One door in the flak/guass room should also be converted to a maintenance door since there's two maintenance doors leading into that area:
image

### LINKED ISSUE #683: Double medical firelock.
## Round ID:
Any

## Testmerges:
Fastmos reeee

## Reproduction:
There's a double fire south directed firelock in the medbay lobby. Beneath the airlocks leading towards the genetic's viewing area.

### LINKED ISSUE #692: Enterprise Kitchen temp differences
High temperature differences in the coldroom result in lockers moving and chef flying backwards when opening the airlock. Consider raising the temperature to -20C

### PR DESCRIPTION
**Pull request by Vasily2013**
## About The Pull Request

THIS PR REMOVES MAPS! This PR removes multiple maps that have not been held up to monstermos or other system compliance standards. It also removes maps that have been replaced by other maps.

## Why It's Good For The Game

These maps have not been maintained, and are code bloat.

## Changelog
:cl:

removes: Aegis
removes: Enterprise
removes: Galactica

/:cl:

closes #641
closes #644
closes #683
closes #692

### CODE REVIEW

**Comment by Jalleo** [comment]
Update travis please its trying to find the maps that you removed.

**Comment by Cenrus** [comment]
I like the Enterprise and it's monstermos ready, I much prefer it over tycoon

**Comment by GoatMonarch** [comment]
F onlyprise
Sad penguin

**Comment by francinum** [comment]
@Vasily2013 Remove the entries referencing these mapfiles in `basemap.dm` so we can merge this already.

**Comment by francinum** [comment]
@Vasily2013 Do you still have plans to support Vago or should I leave it out of the unit tests and leave it on the chopping block?

**Comment by Vasily2013** [comment]
Vago will, at some point in the not extremely distant future, get an overhaul.

**Review by Jalleo — APPROVED** [review]
I am ready for this to be merged when your ready.

**Pull request merged**
