### PR TITLE
tweaks hammerhead botany a bit and removes the 3 million botanist spawn flags

### PR DESCRIPTION
**Pull request by BeloneX**
## About The Pull Request

image

makes botany 1 extra tile wide so the trays are all lined up.
## Why It's Good For The Game

it's just a small thing that really bothered me when i played a lot of botanist on the hammerhead, also why do we need so many spawnflags?
## Changelog
:cl:
tweak: Tweaked hammerhead botany a bit, the botany trays now allign.
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
While you're at it, add disk compartmentalizer near DNA machine.

**Comment by BeloneX** [comment]
> compartmentalizer

sure thing, done.

**Comment by francinum** [comment]
Please fix the floor decals as well.

**Comment by BeloneX** [comment]
> * [ ]  Please note that you've removed several public vendors and a disposals chute from the hallway. Please place new ones nearby.
> * [ ]  Also don't move the airlock controllers, they are fine where they are. Also this change is not noted anywhere in the PR other than mapdifbot.

i moved airlock controllers?

**Comment by PowerfulBacon** [comment]
> 
> 
> > * [ ]   Please note that you've removed several public vendors and a disposals chute from the hallway. Please place new ones nearby.
> > * [ ]   Also don't move the airlock controllers, they are fine where they are. Also this change is not noted anywhere in the PR other than mapdifbot.
> 
> i moved airlock controllers?

Airlock controllers are super buggy and get their pixel values changed when using fast DMM I have found, so they have to be manually reset.

**Pull request closed without merging**
