### PR TITLE
Removes doubledoors

### PR DESCRIPTION
**Pull request by theboy6545**
## About The Pull Request
Removes all doubledoors from our maps and replaced them with normal doors.
#
## Changelog
:cl:

del:removed doubledoors

/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Doubledoors add to the a e s t h e t i c so much more than your lame single doors

**Comment by Demoxide** [comment]
fix the atmos on it and then we can keep them :gun:

**Comment by francinum** [comment]
Fix the EVERYTHING on them.

**Comment by theboy6545** [comment]
weh

**Pull request closed without merging**
