### PR TITLE
Another felinid PR, This one is serious for a change, Adds TG tail sprites

### PR DESCRIPTION
**Pull request by Absolutely-Steph**
## About The Pull Request
Adds TG tail sprites from 
-https://github.com/tgstation/tgstation/pull/56750

## Why It's Good For The Game
good sprites look good

107305796-a484e480-6a51-11eb-85d0-432534a07d8f

## Changelog
:cl:
tweak: Changes felinid tails to TG sprites
/:cl:

### CODE REVIEW

**Comment by bluey89962** [comment]
I personally don't like these sprites, but if somehow the playerbase is happy with them I don't think there's much I can do.
t. felinid player

**Comment by Absolutely-Steph** [comment]
how the hell is this horny trash, that label should be on the tail entwining PR😑

**Comment by Pontenerd** [comment]
> how the hell is this horny trash
Catgirls were added due to someone's fetish

**Comment by Bokkiewokkie** [comment]
Maybe make it a different emote? People seem to be pretty split on whether this is an upgrade or a downgrade

**Comment by Absolutely-Steph** [comment]
> Maybe make it a different emote? People seem to be pretty split on whether this is an upgrade or a downgrade

I very much doubt this, this is just the typical loud minority piping up, even fern changed their mind after seeing the new sprites.

**Comment by TheFakeElon** [comment]
Meh, it doesn't look great, the new animation moves more like a whip than a tail.

**Comment by Acer202** [comment]
I really loved this change on TG. The old tail looks too spastic in comparison while this new one looks "mesmerizing" as many have said.  Most people did end up liking the change.

**Comment by ta3370** [comment]
Too much movement too fast. Pretty much the only good tailsprites I've seen that don't immediately trigger a "this doesn't fit" response every time I see it, are ones where it moves only a couple pixels at a time slowly. This is rapidly and constantly moving basically 1/3rd of the player sprite (The entire torso and across into the arms) all the time and non-stop at basically projectile-speeds, so it feels overloaded.

**Comment by Absolutely-Steph** [comment]
> Too much movement too fast. Pretty much the only good tailsprites I've seen that don't immediately trigger a "this doesn't fit" response every time I see it, are ones where it moves only a couple pixels at a time slowly. This is rapidly and constantly moving basically 1/3rd of the player sprite (The entire torso and across into the arms) all the time and non-stop at basically projectile-speeds, so it feels overloaded.

tbh I thought that too, until seeing it in-game. I find it looks much better when it's actually on a character.

**Review by covertcorvid — APPROVED** [review]

**Comment by covertcorvid** [comment]
Someone can revert it later if they care

**Pull request merged**
