### PR TITLE
Gives Aetherwhisp a munitions techfab and adds techfab circuit board to master at arms lockers

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

Does that

## Why It's Good For The Game

Very important

## Changelog
No

### CODE REVIEW

**Comment by ta3370** [comment]
No, we're not giving them the haha funny "I never leave my department or talk to others" device.

**Comment by Bokkiewokkie** [comment]
It's already in the code my man...

**Comment by ta3370** [comment]
If the pop is low enough that there's no cargo, Munitions just raids cargo anyway. If there is cargo, we have the opportunity for teamwork and communication. People already do a bunch of other shit to avoid such a "horrible" experience as talking to others on a cooperative multiplayer ship, why give them even less reason?

**Comment by theboy6545** [comment]
> 
> 
> If the pop is low enough that there's no cargo, Munitions just raids cargo anyway. If there is cargo, we have the opportunity for teamwork and communication. People already do a bunch of other shit to avoid such a "horrible" experience as talking to others on a cooperative multiplayer ship, why give them even less reason?

It's already in the code, make a revert PR rather then just complaining on the PR that adds it to a map.

**Comment by ta3370** [comment]
>adds it to a map.

It adds it to *every* map.

**Comment by theboy6545** [comment]
> 
> 
> > adds it to a map.
> 
> It adds it to _every_ map.

It adds one to the Atherwhisp, and adds the board to the locker?

**Comment by ta3370** [comment]
> It's already in the code my man...
In a PR that hasn't been merged or even testmerged as far as I can see.

**Comment by theboy6545** [comment]
> 
> 
> > It's already in the code my man...
> 
> In a PR that hasn't been merged or even testmerged as far as I can see.

It was merged 4 days ago?

**Comment by Karmic-Skink** [comment]
Just because something is merged, doesn't mean it is good for game. Also why isn't this aerwhisp's PR, given its aerwhisp's map?

**Comment by Bokkiewokkie** [comment]
I mostly just did it because it was a 1 tile change and I didn't really have an ETA on your PR so I thought I'd just try to make sure people get a munilathe on the aetherwhisp. But I'll just make a new PR with the change in the locker.

**Pull request closed without merging**
