### PR TITLE
Turns the expanded lizard hiss regex from #2311 into a character pref

### PR DESCRIPTION
**Pull request by DeltaFire15**
## About The Pull Request
Title. Now you have a character-pref level option to toggle between s-only hissing (Legacy) and x- and s hissing (Expanded)
Defaults to the expanded version.
This also applies retroactively if you happen to turn into a lizard during a round for whatever reason.

Guh, DB prefs are scary, I sure hope this works and doesn't break anything!

## Why It's Good For The Game
Options good, especially when people tend to have different ideas of how their lizard's speech may show itself.

## Testing Photographs and Procedure

No.

## Changelog
:cl:
add: Lizard hiss is now handled by a character preference, permitting choice between and new- and old styles.
/:cl:

### CODE REVIEW

**Review by covertcorvid — APPROVED** [review]

**Comment by Crossedfall** [comment]
You should probably add an entry into the database changelog.

https://github.com/BeeStation/NSV13/blob/master/SQL/database_changelog.txt

**Comment by DeltaFire15** [comment]
> You should probably add an entry into the database changelog.
> 
> https://github.com/BeeStation/NSV13/blob/master/SQL/database_changelog.txt

Changelog talks about 5.9, has entries up to including 6.0 and the current NSV version before my changes is 6.1. Seems to lack attention in general.

**Comment by Bokkiewokkie** [comment]
> > You should probably add an entry into the database changelog.
> > https://github.com/BeeStation/NSV13/blob/master/SQL/database_changelog.txt
> 
> Changelog talks about 5.9, has entries up to including 6.0 and the current NSV version before my changes is 6.1. Seems to lack attention in general.

Did not know there was a changelog, definitely should be updated yeah.

V6.1 added the flavor text field to the ss13_characters table if you want to include that in there

**Review by Bokkiewokkie — APPROVED** [review]
We can do the changelog on the other pref PR

**Pull request merged**
