### PR TITLE
Fixes explosive unbuilt missile casing

### LINKED ISSUE #2376: Unbuilt missile casings are explosive
## Round ID:
Various

## Testmerges:

Various

## Reproduction:
1. Acquire missile or torpedo casings
2. Apply explosion or weapons fire
3. Casing detonates

### PR DESCRIPTION
**Pull request by someone543**
## About The Pull Request
Makes torpedo casings and missile casings not volatile. 

## Why It's Good For The Game
Fixes #2376 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: Unbuilt missile casings no longer explode
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Confirm that torp still go boom after construction please.

**Comment by someone543** [comment]
> Confirm that torp still go boom after construction please.
> 
> Also the more correct fix for this would be to make the casing volatile once the warhead has been added.
> 
> Unless we are considering the casing to already have propellant in it, and that is the volatile component?

Video added to Testing section, showing constructed torpedo exploding after being shot.
While it was easy to add the volatile components when a warhead is attached, I couldn't figure out a good way to remove the components if the warhead was removed.

**Comment by covertcorvid** [comment]
> > Confirm that torp still go boom after construction please.
> > Also the more correct fix for this would be to make the casing volatile once the warhead has been added.
> > Unless we are considering the casing to already have propellant in it, and that is the volatile component?
> 
> Video added to Testing section, showing constructed torpedo exploding after being shot. While it was easy to add the volatile components when a warhead is attached, I couldn't figure out a good way to remove the components if the warhead was removed.

Changing it to 0 when the warhead is removed would just be adding volatility = 0 to the crowbar_act state 7.

**Comment by someone543** [comment]
> > > Confirm that torp still go boom after construction please.
> 
> > > Also the more correct fix for this would be to make the casing volatile once the warhead has been added.
> 
> > > Unless we are considering the casing to already have propellant in it, and that is the volatile component?
> 
> > 
> 
> > Video added to Testing section, showing constructed torpedo exploding after being shot. While it was easy to add the volatile components when a warhead is attached, I couldn't figure out a good way to remove the components if the warhead was removed.
> 
> 
> 
> Changing it to 0 when the warhead is removed would just be adding volatility = 0 to the crowbar_act state 7.

That's the first thing I tried, it didn't work.

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
