### PR TITLE
Makes toolbelt tool sprites consistent

### PR DESCRIPTION
**Pull request by bluey89962**
## About The Pull Request
Advanced engineering tools have a blue and white palette but show up as yellow in belts. This PR fixes that
(new/old)
a

## Why It's Good For The Game
Small thing that bothered me a lot plus consistency is good

## Changelog
:cl:
tweak: Jaws of life and the drill show up as white instead of yellow in the belt sprite
/:cl:

### CODE REVIEW

**Comment by bluey89962** [comment]
alright hopefully it worked this time

**Comment by Karmic-Skink** [comment]
Hold off on merging this please, looking at restoring consistent engineering colour pallets.

**Comment by Kmc2000** [comment]
> Hold off on merging this please, looking at restoring consistent engineering colour pallets.

Holding

**Comment by bluey89962** [comment]
> Hold off on merging this please, looking at restoring consistent engineering colour pallets.

any update on this? If not I'll close this PR until further notice

**Comment by bluey89962** [comment]
closing this because it's going stale and because I want to fix my NSV fork. Might redo it later on

**Pull request closed without merging**
