### PR TITLE
[Map] NSV Atlas, somehow smaller than eclipse! :tm:

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

NSV Atlas is intended to compete with Jeppison, and supplement eclipse. The Atlas is built for 0-25 players and is a fully featured map in a tiny package. 

Why?
- As we know, the Jepp has issues. Jeppison is supposed to bridge lowpop gaps, however the ship cannot really function below ~10-15 players (feel free to correct me if I'm wrong). Atlas compresses this design into a smaller shell, compromising only on secondary, non-essential roles like Viro, Lawyer, Curator etc.
- Eclipse is super fun, but not at all antag friendly. There's no maint, and everyone has AA, while the Jepp has barely any maint to speak of. Atlas features a decent amount of maint, and alternate pathways / access points into departments for antagonists, which should help it fit into this lowpop role nicely.
- Due to the extreme lowpop nature of Eclipse, it foregoes a mining ship entirely in favour of its iconic asteroid cage; with Atlas I still wanted to allow miners to function independently, even if there's very low population.
- Eclipse entirely foregoes the engineering role in favour of generators, removing opportunities for engi mains to interact with ship content. Atlas features a fully fledged stormdrive and atmospherics bay to allow Engineers to function on extreme lowpop.
- Finally, I made Atlas as an instance ship, however loading those midround causes a lot of nasty issues. I thought the concept was cool, so I've revamped it into something more viable for general usage.

## Why It's Good For The Game

NSV Atlas features:

* A full munitions bay with room for improvement
* A full fighter hangar with a reduced wing of fighters
* Fully fledged departments with very few compromises, although some jobs like Virologist are not supported.

I'm welcoming feedback, please provide it here, I'm sure there'll be something I missed.

If all goes to plan, Atlas should bridge the population gap where you have _juuust_ too many players for Eclipse, but not enough for Tycoon. 

## Changelog
:cl: Kmc2000 with Bokkiewokkie
add: Added a new lowpop ship, Nsv Atlas!
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
Galley doors have strange acsess.

**Comment by Dovahkitt3** [comment]
Medical is missing a considerable amount of equipment

**Comment by Bokkiewokkie** [comment]
munitions needs an AMS console, there's no squad equipment vendors

**Comment by marka-0** [comment]
Hangar is missing extra fighter pilot lockers for transfers

**Comment by Vasily2013** [comment]
-Meters in atmos don't link. 
-Engineering does not start out with access to any holofans or atmos lockers in general.

**Comment by ilikesaying** [comment]
no ore silo

**Comment by Bokkiewokkie** [comment]
> no ore silo

this is a feature

**Comment by Dovahkitt3** [comment]
Medical seems to be missing prosthetics

**Review by Vasily2013 — DISMISSED** [review]
people seem to like it. No major fixes needed at this time. 
war

**Review by Vasily2013 — APPROVED** [review]
final_5bf6da178af63a001261a048

**Pull request merged**
