### PR TITLE
Upgrades to Jeppi, try two 

### PR DESCRIPTION
**Pull request by Omppusolttu**
## About The Pull Request

Upgrades to the Jeppison, making it compatible with Newmunitions

## Why It's Good For The Game

Making a ship in rotation fully compatible with Newmuni.

## Changelog
:cl:
add: Added maintance around chapel and evac in the jeppison
add: Added Newmunitions weapons to the Jeppison and increased the size of hangar
tweak: Changed around command to make space for Multi-Z guns in the Jeppison
/:cl:

### CODE REVIEW

**Comment by Omppusolttu** [comment]
Merge conflict comes from God's own Jeppison upgrade, please ignore until one has been added in.

**Comment by theboy6545** [comment]
> Merge conflict comes from God's own Jeppison upgrade, please ignore until one has been added in.

Clerical said he'd have a look at the two and decide, so yeah, ignore the conflicts

**Comment by Vasily2013** [comment]
You've got several type path conflicts whenever I try to open the map. This is likely why mapdifbot is failing.

**Comment by Omppusolttu** [comment]
> You've got several type path conflicts whenever I try to open the map. This is likely why mapdifbot is failing.

Well that sounds bad, but could you explain what any of that means? I know jack about code and shit about github

**Comment by Vasily2013** [comment]
> > You've got several type path conflicts whenever I try to open the map. This is likely why mapdifbot is failing.
> 
> Well that sounds bad, but could you explain what any of that means? I know jack about code and shit about github

Basically it means you have objects on the map that no longer have existing paths. This normally happens when an object path is changed.

**Comment by Omppusolttu** [comment]
> Basically it means you have objects on the map that no longer have existing paths. This normally happens when an object path is changed.

Ideas for fixing this? I've not had encounters with this sort of stuff before.

**Pull request closed without merging**
