### PR TITLE
Bridge staff SecHUD update

### PR DESCRIPTION
**Pull request by Corsaka**
## About The Pull Request
moves Bridge Staff SecHUD in line with Assistant's, where's it's 6x6 instead of 4x5.

## Why It's Good For The Game
bridge staff secHUD no longer acts as if it's city of london's piddly little piss runway

## Changelog
:cl:
tweak: Adjust Bridge Staff Icon
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
can we look at pictures please

**Comment by Corsaka** [comment]
@Firefox13  show all checks > diffs > details

**Comment by Jalleo** [comment]
@Corsaka you can make a second PR to put this into the update_branch using that code there as the base. This will mean it wont be lost by mistake for that branch when it actually can be used.

**Comment by Corsaka** [comment]
fuck you github i just want to use the latest file adsjfaskldfhjalksdjflkasdf

**Pull request closed without merging**
