### PR TITLE
SP, SS, SF Touchups

### PR DESCRIPTION
**Pull request by BetaCentari**
## About The Pull Request
The Beebase messed up how medicine patches healed people previously, this fixes that issue. 

## Why It's Good For The Game
Returns Synthflesh, Silver Sulfadiazine, and Styptic Powder to how they acted before the Beebase. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:

Tweak: Tweaked SF, SP, and SS behavior when applied through patches

/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Define "messed up".

**Comment by BetaCentari** [comment]
> Define "messed up".

It only applied to the specific limb you put it on instead of the entire body how it used to. I forgot to put NSV tags on the changes, hold on.

**Comment by BetaCentari** [comment]
Added NSV tags.

**Comment by Karmic-Skink** [comment]
> 



> > Define "messed up".
> 
> It only applied to the specific limb you put it on instead of the entire body how it used to. I forgot to put NSV tags on the changes, hold on.

Sounds better to me.

**Review by Karmic-Skink — CHANGES_REQUESTED** [review]
Changelog is inappropriate to the state of game and the changes.

**Comment by covertcorvid** [comment]
I actually don't totally mind the change because it lets bicardine, kelotane, oxandrolone, and salicyclic acid stand out as all-around healing. It gives them different use cases.
You probably still want to update the limb damage states though.

I'm going to have to disagree with @Karmic-Skink about the changelog not being appropriate. At most it should have the "balance" tag instead of "tweak", but it's not like the state of the game has really settled yet.

**Comment by BetaCentari** [comment]
Alright, I'll just go ahead and close it. I'm sure it'll be fine, encourage diversity in drugs used for treatment.

**Comment by red031000** [comment]
I actually dislike this change, given the difficulty in creating synthflesh from scratch (or the time taken to set up a factory)

with the state of NSV, either medical is extremely busy, dealing with almost the entire crew at once, or has nobody to treat, at any one time

during the extremely busy periods I genuinely think it's a good idea to have a "slap on and forget" chem so medical's time is more spent on those critically injured, and the crew gets up and running faster

I think it's important to remember NSV is not bee, and has a different game flow, so this needs to be taken into account

**Pull request closed without merging**
