### PR TITLE
Boardable Carriers

### PR DESCRIPTION
**Pull request by Omppusolttu**
## About The Pull Request

Adds a carrier boarding map, allowing crews to board both standard and elite carriers.

## Why It's Good For The Game

For now the ability to board as many vessels as possible is useful.

## Changelog
:cl:
add: Carriers are now boardable.
/:cl:

## Picture
carry

### CODE REVIEW

**Comment by Omppusolttu** [comment]
> Interim review:
> 
> Remove the floor line decals and any other non-essential decals in order to lower performance overhead please.

Requested changes have been made

**Comment by Karmic-Skink** [comment]
This needs mapper reviews at this point.

**Review by Vasily2013 — APPROVED** [review]
Baring any test issues this should be okay. It doesn't look too insane from the mapdiffbot.

**Review by covertcorvid — CHANGES_REQUESTED** [review]
The binoculars need to be repathed - should just be /obj/item/binoculars now
The crew was unable to use the captured vessel due to access restrictions on the stormdrive

**Comment by Omppusolttu** [comment]
Reopening this PR as I accidentally deleted this PR's branch when cleaning up my fork.

**Pull request closed without merging**
