### PR TITLE
Galactic Engineering Mk2

### PR DESCRIPTION
**Pull request by SerynEngi**
## About The Pull Request

Added escape pods to the aft end of the ship, and generally brought engineering into a state that doesn't require an engineering main to set up. I also tossed the training range onto the upper deck so that people know its actually there. Also, wiring fixes.

## Why It's Good For The Game

Piping spaghetti bad, fix man good. See above.

## Testing Photographs and Procedure

<details>
<summary>So, the section of the area near the atmos storage in the smaller screenshot is the more up-to-date version of the after, as I wasnt going to set up a whole other image after I made the original changes, and I didnt bother making before pictures of the upper deck, as it was mostly empty space that I changed. Yes, unless it was in engineering, the coffeemaker still exists here.</summary>

https://cdn.discordapp.com/attachments/1026662355918131200/1092515055662284921/Galactic_BSA_Before_and_After.png
https://cdn.discordapp.com/attachments/1026662355918131200/1092515055968452668/Galactic_Engineering_Before_and_After.png
https://cdn.discordapp.com/attachments/1026662355918131200/1092515056492761178/Galactic_range_below.PNG
https://cdn.discordapp.com/attachments/1026662355918131200/1092515056803135579/Galactic_range.PNG

</details>

## Changelog
:cl:
add: Escape pods and escape pod signage to Galactica
tweak: Reworked engineering and engineering maintenance access on the Galactica
fix: More efficiently routed wiring in some areas on the Galactica
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Looks good overall, but from what I can tell from the screenshots, is the marine training / assault course duplicated on both decks?

**Comment by SerynEngi** [comment]
> Looks good overall, but from what I can tell from the screenshots, is the marine training / assault course duplicated on both decks?

No, The marine training course has been moved entirely to the upper deck, I just didnt want to stitch together two entirely new screenshots for changing a relatively minor area of the ship. The "Galactica_Range_below" and "Galactica_range" screenshots should be considered the up-to-date version of that area.

**Review by Bokkiewokkie — CHANGES_REQUESTED** [review]
Looks good, I just ask that you update these areas to fit more nicely as well:
image
Both of those sections would fall under the maint area, and the door into the core should have a zebra interlock helper.

**Comment by SerynEngi** [comment]
Gungnir Error Correction

Issue corrected. Thanks for that. I also added directional signs to the escape pods now that I found where they were hidden in the files while working on the Gungnir.

**Review by Bokkiewokkie — APPROVED** [review]

**Pull request merged**
