### PR TITLE
Fixes some issues on the Tycoon

### LINKED ISSUE #1153: hanger maint access problem
## Round ID:
1641

## Testmerges:
N/A

## Reproduction:
go to hanger and as any role that shouldn't be allowed in the hanger, go into the hanger through maint, for some reason even assistants can get in!

### LINKED ISSUE #1156: Turbine fuel line connects to nothing in atmos
Capture

## Testmerges:

N/A
## Reproduction:

Go into atmos, look at reactor fuel line

### LINKED ISSUE #1157: [Tycoon] and [Gladius] are missing IFF cards in missile factory
## Testmerges:

#1152

## Description
Both on the Gladius and the Tycoon the missile factory is missing 3 IFF cards, in Gladius' case this makes making missiles roundstart impossible. Gladius also still has Railgun, flak and pdc ammo in one of the storage rooms and a ton of pre-assembled torps. So I think it might be better to give the gladius some more missile parts roundstart and remove a few of the (nuke/piercing) torps from the default setup.

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

I've right clicked every door on the Tycoon and everything is now (actually) monstermos compliant. Double doors are also all going to be purged, so that's a good thing.
Oh and don't smoke in munitions. 🚭

Fixes #1153
Fixes #1157 
Fixes #1156 

## Changelog
:cl:
fix: You can no longer get into the Tycoon hangar from maintenance without access.
fix: Fixes Tycoon service sector maint airlocks' access.
fix: Removes all double doors from the Tycoon.
balance: Moves ore silo on Tycoon from the Vault to Cargo.
tweak: Tycoon's comms relay is now in the teleporter.
tweak: Tycoon munitions has been given a new paintjob.
/:cl:

### CODE REVIEW

**Comment by GoatMonarch** [comment]
I for one support the double door genocide! Begone doors that take up two tiles, but technically acts like it's only one tile!

**Comment by Vasily2013** [comment]
You're going to hate what I'm about to tell you. The doors are auto-smoothing, and you don't have to set their dir vars.

**Comment by Vasily2013** [comment]
you fixed that door in sec, right?

**Review by Vasily2013 — APPROVED** [review]
image

**Pull request merged**
