### PR TITLE
Atlas Maintenance pass

### LINKED ISSUE #1592: Cannons deafen people in the XO office

### PR DESCRIPTION
**Pull request by Vasily2013**
## About The Pull Request

This PR is to perform map maintenance and quality of life improvements to Atlas, and to ensure that it meets mapping standards for the project.

## Why It's Good For The Game

Everything needs a good pass every once in a while.
fixes #1592 

## Changelog
:cl:
fix: XO office on atlas now starts with closed, independently operable shutters.
fix: Meters in atmos on Atlas now start connected to their pipes.
tweak: Most areas on atlas now have light switches, request consoles, and air alarms.
tweak: Atlas airlocks expanded so you can drag things through most of them.
tweak: Atlas engine now has airlock separating it from the rest of the engine room. Aka it's osha compliant now.
add: Atlas mining hangar.
/:cl:

### CODE REVIEW

**Comment by Vasily2013** [comment]
1, going to shoot myself because of debug tests.
2, mining hangar, because apparently that needs to be a thing soon.tm

image

**Comment by SerynEngi** [comment]
A thought about the SD area, perhaps extend it a bit and throw up a set of shutters for thermal protection instead of using atmos holofans as an engineering standard to prevent the room from being overheated. The firelocks do not apparently stop the temperature from passing through them over time.

**Comment by Absolutely-Steph** [comment]
i'd want a whole new look at the munitions/gun arrangement. I'm pretty sure felinid captains still get deafened inside their office.
Maybe move the nac forward and the vls backwards, maybe switch out the vls with 3 torp tubes, or the nacs with railguns?
and obviously have the whole mining hangar thing, maybe just add mining sabres to the normal hangar and give miners access?

**Comment by Vasily2013** [comment]
image

image

**Comment by Crus0** [comment]
> i'd want a whole new look at the munitions/gun arrangement. I'm pretty sure felinid captains still get deafened inside their office. Maybe move the nac forward and the vls backwards, maybe switch out the vls with 3 torp tubes, or the nacs with railguns? and obviously have the whole mining hangar thing, maybe just add mining sabres to the normal hangar and give miners access?

Atlas munitions most certainly one of the best there is. It is best to avoid radically altering it.
 The maintenance nearby the torp factory room can probably get converted into something more interesting. Perhaps a room with space and boards to create 1 or 2 railguns that are not yet assembled at round start?

**Comment by Vasily2013** [comment]
> A thought about the SD area, perhaps extend it a bit and throw up a set of shutters for thermal protection instead of using atmos holofans as an engineering standard to prevent the room from being overheated. The firelocks do not apparently stop the temperature from passing through them over time.

* Added airlock to SD.



> i'd want a whole new look at the munitions/gun arrangement. I'm pretty sure felinid captains still get deafened inside their office. Maybe move the nac forward and the vls backwards, maybe switch out the vls with 3 torp tubes, or the nacs with railguns? and obviously have the whole mining hangar thing, maybe just add mining sabres to the normal hangar and give miners access?

* This is out of scope, re-arranging the entire munitions department would have to be a separate PR.



> The stacking machine - in maint below engi, next to the recycler - is not linked to the stacking machine console roundstart. Plus the conveyor belts there do not have a switch, and thus dont work

* conveyor now has switch, and should work.
* I'm not sure how linkage functions. I checked Meta and there weren't any specific variables set.

> Also, in the brig, there are three consoles on top of each other. Okay, it looks a bit dumb, but one of them also does nothing. Its just a "computer". Maybe you could remove it, leave the crew monitor console there, and put the records console in place of one of the reinforced tables

* Computers adjusted. Useless computer removed.

**Comment by sunofang** [comment]
Hull juice in eng makes me wanna die. It blocks the door so fucking perfectly aaaaaah

**Comment by Vasily2013** [comment]
Function test complete. It works.

**Review by covertcorvid — DISMISSED** [review]
koala

**Comment by Koekiegast** [comment]
I believe i requested this before but i would enjoy it if there was a gas pump on the fuel line of the sd near the pa, it's easy to forget to put one there and it's really annoying to run between atmos and the engine room to adjust the fuel pressure.

**Comment by Vasily2013** [comment]
> I believe i requested this before but i would enjoy it if there was a gas pump on the fuel line of the sd near the pa, it's easy to forget to put one there and it's really annoying to run between atmos and the engine room to adjust the fuel pressure.

I considered this, but elected against it, as it is a minor quality of life change which can be easily implemented in-round, just like any engine.

**Comment by Koekiegast** [comment]
> 

I see, however mappers only have to do it once, not every round like the engineers. But it's your choice in the end.

**Comment by Vasily2013** [comment]
This is ready for merge as far as I'm concerned. If the HOP and Cap are in their offices during combat I sense there are more significant issues.

**Pull request merged**
