### PR TITLE
Battlestar Valkyrie 

### PR DESCRIPTION
**Pull request by Vasily2013**
## About The Pull Request

This PR is intended to change Valkyrie over to multiple .dmm files to follow the format of other maps. Additionally it brings Valkyrie to a state of near-completion, and readiness for peer review by other mappers. 

## Why It's Good For The Game

standardization is good. maps are good.

## Changelog
:cl:
map: moves Valkyrie towards a more completed state.
/:cl:
image
image
image

### CODE REVIEW

**Comment by Vasily2013** [comment]
Size wise there's not much I can do to reduce it without starting to cramp things down a decent bit, but in general this is meant to be a high-pop meme ship.

I'm not sure what the issue you're referencing with hallways is.

The cargo conveyor can be shifted around to reduce length, I mainly thought it would be an entertaining form factor for cargo to deal with. If you have a suggestion on what would best correct this I'd be happy to entertain this.

Empty areas around the ship are left there intentionally for the moment to fill in forgotten areas, and any remaining can easily be turned into maintenance areas for nefarious purposes. 

XO office is just west of the bridge

I'm not sure what you mean by bringing things to the table in a unique way. They layout itself is unique to my knowledge, as there have been no other maps with similar form factor or department layout. This comment befuddles me quite a bit, because if this behemoth doesn't bring its own unique style to the round then I don't know what will. 

As for the walled off section in engineering that can be opened up, the primary reason that it is walled off is the contents of what is directly above it on deck 2.

**Comment by GoatMonarch** [comment]
Side note: We got more options related to multi-z currently. Elevators and stairs are a thing.
Stairs of which are on equal level as ladders, but less clicking.

**Comment by Vasily2013** [comment]
Spawners in, maint filled, might do some re-areaing tomorrow, but as it stands i'm gonna go ahead and say this is ready for some sort of playtest once I put overmemes on it.

**Comment by GoatMonarch** [comment]
This is now looking like a good replacement for the Aegis now. Keep your eyes and ears open in the future incase the coding team makes any major changes.

**Pull request merged**
