### PR TITLE
Updates Hammerhead to be Monstermos compatible and have armor pumps + other fixes

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request
Adds munitions lockers, armour pumps, a new arms dump and changed atmos to be more stormdrive compatible and even less friendly to anyone who doesn't wanna use the stormdrive.

## Changelog
:cl:
add: Added Armour Pumps to the Hammerhead
add: Added Random Maints to Hammerhead
add: Adds lockers for munitions and bridge staff to Hammerhead
tweak: Re-piped a few parts of the stormdrive to make adding interesting mixes easier
balance: Overhauled the Arms Dump and moved the HoS Office
/:cl:

### CODE REVIEW

**Comment by Vasily2013** [comment]
Travis is failing because of pixel X/Y being defined and equal to zero at the same time. My advice is open the .dmm in something like notepad++ to find them.

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
- [x] HOS shutters don't work
- [x] HOS office has no holopad
- [x] There are buttons under windows in the HOS office that need to be dealt with. 
- [x] As well if you're using the window spawners you don't need to put window firelocks down under them. The firelock windows are included with the spawners.

**Comment by Bokkiewokkie** [comment]
yeah I can't fix everything right now cause I'm on a laptop and it's 4 am but I'm also noting down some other fixes I'll get to work on tomorrow:

- [ ] pipe at plasma constrictors is hidden
- [ ] RnD servers have no cooling
- [ ] Some department signs are pointing the wrong way
- [ ] Probably gonna compact science a bit as it has unecissarily long empty hallways
- [ ] Reworking certain parts of maint and outer grilles to protect better from meteor/bullet impacts

**Comment by Bokkiewokkie** [comment]
okay so I expected to have the fixes done by the end of today but due to also wanting to play the game I've decided to just put in the most vital hotfixes and I'll fully implement the other things either tomorrow or the day after

**Review by Vasily2013 — APPROVED** [review]
It works, it works, god bless, it works!

**Pull request merged**
