### PR TITLE
No-kill traitor option

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
This PR introduces a config option - MIN_POP_KILL_OBJECTIVES - for the minimum number of connected players for objectives where killing is likely or required. This means that if the number of ready players is above the minimum for traitors but below the new option, there can be traitors but they will have non-lethal objectives.
The following objectives will be disabled if the number of ready players is below the minimum:
- Martyr (Die a glorious death)
- Assassinate
- Destroy (Destroy AI)
- Maroon (Prevent target from leaving alive. The AI protect objective will still have this paired with it.)
- Block (No organics on the shuttle)
- Purge (No mutant humanoids on the shuttle)

## Why It's Good For The Game
Antags add variety, but we can't have them on lowpop because they often have to kill people and we need warm bodies to operate the ship. This is an attempt to fix that.

## Changelog
:cl:
balance: Modified traitor antag gamemode to support lower populations
config: Introduced a pop requirement for traitor objectives that often require death
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
Wouldn't this just further disincentivize people from playing lowpop, compounding on the problem

**Comment by covertcorvid** [comment]
> 
> 
> Wouldn't this just further disincentivize people from playing lowpop, compounding on the problem

How so? These would be population levels where normally we'd have no antags whatsoever, and people keep mentioning lack of antags as one of the reasons rounds lack variety

**Comment by williamcll** [comment]
Well, what objectives are left?

**Comment by covertcorvid** [comment]
> Well, what objectives are left?

It'll be steal and download for the humans, robot army and protect/maroon for the AIs, and the escape or survive objective as the end. Not a ton of options, but still opportunities for trouble.

**Comment by Bokkiewokkie** [comment]
> > Well, what objectives are left?
> 
> It'll be steal and download for the humans, robot army and protect/maroon for the AIs, and the escape or survive

And we can also add more (NSV specific) objectives if we want to increase the options, though from what I've seen plenty of people would also be perfectly content with no objectives as a traitor at all.

**Comment by covertcorvid** [comment]
> > > Well, what objectives are left?
> > 
> > 
> > It'll be steal and download for the humans, robot army and protect/maroon for the AIs, and the escape or survive
> 
> And we can also add more (NSV specific) objectives if we want to increase the options, though from what I've seen plenty of people would also be perfectly content with no objectives as a traitor at all.

I'm confused, what would be the point of a traitor without any objectives?

**Comment by Pontenerd** [comment]
> > > > Well, what objectives are left?
> > > 
> > > 
> > > It'll be steal and download for the humans, robot army and protect/maroon for the AIs, and the escape or survive
> > 
> > 
> > And we can also add more (NSV specific) objectives if we want to increase the options, though from what I've seen plenty of people would also be perfectly content with no objectives as a traitor at all.
> 
> I'm confused, what would be the point of a traitor without any objectives?

Antags can do a lot of neat stuff that normal crew cannot do, like set-up elaborate saw style traps in maint for example

**Comment by williamcll** [comment]
Thought of a new antag objective: Steal money

**Comment by covertcorvid** [comment]
Approved via discord

**Pull request merged**
