### PR TITLE
Makes the fourth wall drink sound more extreme

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

Makes the "Fourth Wall" drink actually seem like a big deal with big text as it causes brain damage and also fixes a spelling mistake.

## Changelog
:cl:
tweak: Makes the Fourth Wall drink's announcement bigger.
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Please add //NSV13 tags to core file changes.

**Comment by Bokkiewokkie** [comment]
> Please add //NSV13 tags to core file changes.

@Karmic-Skink Done

**Review by Jalleo — APPROVED** [review]
Just need the system to say yes and its merged.

**Comment by Bokkiewokkie** [comment]
Bruh

**Pull request closed without merging**
