### PR TITLE
New ship, Aetherwhisp 6

### PR DESCRIPTION
**Pull request by IndusRobot**
## About The Pull Request

The fabled Aetherwhisp 6 is finally here!

Deck 2 top deck
deck2

Deck 1 bottom deck
deck1

## Why It's Good For The Game

New ships are cool
## Changelog
:cl: IndusRobot
add: New ship, SGV Aetherwhisp
add: New carpets for mapmaking, courtesy of KMC
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Some issues I found

1. Chaplain doesn't have access to a cremator
2. The mime spawns in space outside the holodeck and dies a miserable death
3. Genetics doesn't belong in science unless you have changed the access on the nearby doors to allow geneticists.

**Comment by Cenrus** [comment]
Sounds good. Tell me if any of my finds are intentional, so I can remove them from the list.

**Comment by Cenrus** [comment]
image

Nearspace area in a wall here, near cryo.

**Comment by Cenrus** [comment]
cargo shuttle doesn't dock with the shutters.

**Comment by Cenrus** [comment]
sci/munitions pods face the wrong directions

**Comment by Cenrus** [comment]
The disposals problem was caused by the escape pod being in the wrong orientation, as it would spawn over a few disposals pipes.

**Comment by Cenrus** [comment]
tcomms should have a seperate SMES unit so it doesn't run out of power so easily

**Comment by Vasily2013** [comment]
Alright, let's do this.
- [ ] The floor under SM chamber outer door is carpet, not reinforced.
- [ ] Replace the siphon vents in the SM chamber with scrubbers so they're configurable and on at roundstart.
- [ ] SM Ejector does not function
- [ ] The outermost airlocks on the ferry shuttle don't actually lead into the shuttle. Is this intentional?
- [ ] Bridge maint lacks an APC.
- [ ] Science/server and aisat_interior have multiple APCs. 
- [ ] You have four roundstart active turfs in the singulo engine, they're the outermost plating turfs.
- [ ] The multi-deck adapter in atmos gives a not connected flag due to the north section not having a connected pipe. You can fix this with a connector port.
- [ ] Assume the players are dumb. The ATC booth scrubber and vent should be in a different area so they don't accidentally vent themselves.
- [ ] The gulag shuttle isn't needed considering we mainly use a mining support ship.
- [ ] Genetics is missing some carpet near the door.

This is just my first pass. Some of it may be repeated, but that's my observations thus far.

**Pull request merged**
