### PR TITLE
[EXPERIMENTAL] [UPSTREAM] Antag Preferences and Bans Rewrite 

### PR DESCRIPTION
**Pull request by Bobbanz1**
## About The Pull Request
FIRST OF ALL
**This seriously needs an Experimental testing because I don't know what might have broken or not**

Secondly:
This PR ports the following PR from Upstream at the request of ta3370 in the NSV13 Discord server:
* https://github.com/BeeStation/BeeStation-Hornet/pull/9229

What that PR does is it allows for antagonist preferences to be tied to the player character itself rather than the client, what this means is that you can have one character set to be able to roll traitor and have another character have it set to disabled without having to manually change it every single round you swap between the two characters. 

That PR does some other stuff but I think that was the primary reason why Ta wanted it ported.

Also this branch is forked off from this PR so it contains everything that was changed in that one as well, this is to prevent merge conflicts in the future and having to re-arrange the damn preference file again!
* https://github.com/BeeStation/NSV13/pull/2274

## Why It's Good For The Game
Antag Preferences tied to characters, rather than client!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/NSV13/assets/59128051/c46375b1-9458-422a-b39b-dc2927f5a7be

</details>

## Changelog
:cl:itsmeow, EvilDragonfiend
add: All non-ghost role antagonist preferences are now per-character. Global toggle buttons toggle the preference on all characters at once.
refactor: Rewrote antag preference internals to allow for better control of antag preferences and more distinct usages.
refactor: Cleaned up antag bans, with more distinct settings and new general categories.
tweak: All antag prefs will start on by default rather than off. The same applies to newly added ones.
fix: Fixed various antag bans being bypassable.
fix: Fixed various ghost polls using the wrong preference or ban types.
del: Removed BYOND account age checks from antag roles in favor of living hours.
del: Removed "Midround Antagonist" preference in favor of unique preferences per midround.
add: Added distinct role preferences for Antagonists (Roundstart/Latejoin) and Midrounds (Ghost/Living).
add: Almost all ghost antagonist polls have a "Never for this round" option now.
del: Removed the ghost notification preferences menu (poll ignore menu).
tweak: The lavaland beach bartender can now speak Stoner.
del: Removed some unused mob spawners from the code.
add: Added 4hr playtime checks to roundstart/latejoin antag roles. Wizard and nukeops are 8hr.
fix: Fixed a typo in the skeleton spawner description.
fix: Fixed unnecessary DB queries due to is_banned_from not properly ckey-ifying the ckey parameter and causing cache misses.
/:cl:

### CODE REVIEW

**Review by Bokkiewokkie — APPROVED** [review]
We ball

**Comment by someone543** [comment]
Capture

Ghost controlled ships seem to be missing here

**Comment by Bobbanz1** [comment]
> Capture
> 
> Ghost controlled ships seem to be missing here

Huh…hmmm, I’ll take a look later today

**Comment by EvilDragonfiend** [comment]
> > Capture
> > Ghost controlled ships seem to be missing here
> 
> Huh…hmmm, I’ll take a look later today

I don't know NSV roles, but if it's ghost free-spawn role like askwalker or lavaland roles, it's correct. If not, try to track `/datum/role_preference/midround_ghost`

**Comment by Bobbanz1** [comment]
> Capture
> 
> Ghost controlled ships seem to be missing here

Right, I've fixed this issue now.

**Comment by Bobbanz1** [comment]
Might have created a new problem although I'm not so sure, was the Stop Observe button there before for ghost ships or is that now recent, since pressing it just causes a runtime error and breaks stuff.

**Comment by Bokkiewokkie** [comment]
> Might have created a new problem although I'm not so sure, was the Stop Observe button there before for ghost ships or is that now recent, since pressing it just causes a runtime error and breaks stuff.

They shouldn't need one and I don't remember there being one... how did it get there though 🤔

**Comment by Bobbanz1** [comment]
> > Might have created a new problem although I'm not so sure, was the Stop Observe button there before for ghost ships or is that now recent, since pressing it just causes a runtime error and breaks stuff.
> 
> They shouldn't need one and I don't remember there being one... how did it get there though 🤔
> 
> I'm also not seeing boarders in the midround list yet

Was boarders even in the game preferences originally?

**Comment by Bobbanz1** [comment]
Boarders weren't an original setting to be toggled on or off like the rest of these were, I could include them if you want though?

**Comment by Bokkiewokkie** [comment]
> Boarders weren't an original setting to be toggled on or off like the rest of these were, I could include them if you want though?

Messed up but yeah I would like them in there

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
