### PR TITLE
515 compatibility

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
This PR ports changes from https://github.com/BeeStation/BeeStation-Hornet/pull/8648

Update all /type/.proc/name and /type.proc/name to TYPE_PROC_REF(/type, name)
`(/[^\s]*?)/?\.proc/(.*?)([,)])`
`TYPE_PROC_REF($1, $2)$3`

Remaining .proc/name to PROC_REF(name)
`\.proc/(.*?)([,)])`
`PROC_REF($1)$2`

moving standalone /proc/name to GLOBAL_PROC_REF(name)
`, /proc/(.*?)([,)])`
`, GLOBAL_PROC_REF($1)$2`

Additionally look for uses of /proc/procname as arguments, so check for = /proc =/proc and , /proc. Uses in the adminverbs lists are not converted.

Change all uses of call()() to external libraries to LIBCALL()()

Change static uses of NAMEOF to NAMEOF_STATIC

Update auxmos to at least 2.2.2

## Why It's Good For The Game
515 has very good performance upgrades

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: [itsmeow](https://github.com/itsmeow), [AnturK](https://github.com/AnturK), [RimiNosha](https://github.com/RimiNosha), [dwasint](https://github.com/dwasint)
code: Code should now compile on 515
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Got any graphs for performance improvements post testing?

**Comment by Bokkiewokkie** [comment]
Conflicting tgs api after the dmapi update moment

**Comment by covertcorvid** [comment]
> Got any graphs for performance improvements post testing?

I myself do not have beta access, and we have only tested this to make sure it doesn't break 514 yet, not tried loading 515

**Comment by Crossedfall** [comment]
> Got any graphs for performance improvements post testing?

It'd be lovely if you were in the Discord so I could more actively share details and charts with you. I was pushing Covert to make these changes so I could include you all in Bee's sendmaps beta. I need these changes in first and then a final follow-up PR (that'll be TM'd but not merged) that'll actually enable 515.

I can, however, offer NSV's current maptick and time dilation data. Unfortunately the data isn't _great_ due to the low frequency of rounds overall and the limited number of higher-population rounds available. 

A ratio of 1 is considered to be abysmal.

### 90-days

image

### 14-days

image

<details><summary>Same graphs but with the number of rounds included</summary>

### 90-days

image

### 14-days

image

</details>

**Pull request merged**
