### PR TITLE
Makes pilots not get deleted (Should fix uncloneability)

### LINKED ISSUE #407: Fighter ejection pods qdel pilot on kill instead of ejecting them
## Round ID:
121

## Testmerges:
#386 

## Reproduction:
Put a pilot in a locked canopy fighter
Shoot them with small arms until the fighter breaks
put like 3 bullets into the escape pod
bam, pilot qdels with all their shit.

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request
Stops pilots from getting deleted along with their fighters when they blow up, they are instead sent to (and murdered on) the empty space z level.
should fix: #666 and fix #407 

## Changelog
:cl:
fix: Stops fighter pilots' corpses from getting deleted upon ship death.
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
TBH I don't really like this as a solution.

**Comment by Bokkiewokkie** [comment]
I agree this isn't the best solution but right now it's the only solution I'm seeing. If you can make a better option I'd be glad to just close this and let your PR get merged. So I think the best solution for now would just be (test)merging this and reverting it when a better solution is made.

**Comment by francinum** [comment]
Currently this behavior is also applied to ships on valid dock z-levels.

It should not. It should drop them horribly dead on the spot.

**Comment by Bokkiewokkie** [comment]
> Currently this behavior is also applied to ships on valid dock z-levels.
> 
> It should not. It should drop them horribly dead on the spot.

Yep, I tried to implement that but decided not to because I'm not a very experienced coder. And I was already happy that the main part with the yeeting into space worked because it'd still allow them to get cloned even if the ship does explode on the Z level.
I'm willing to take another shot at making it drop them when they're on a z level with the station trait though.

**Comment by Vivalas** [comment]
I strongly believe that this PR is responsible for the bug earlier where a pilot had all his references to a deleted fighter intact and wasn't able to be interacted with at all.

If the fighter explodes, the references the pilot has to the fighter need to be handled. I think before that was being handle dby the pilot being deleted, but now without the pilot being deleted it's causing problems.

**Comment by Bokkiewokkie** [comment]
Okay so I've managed to fix (remove) all of the references to the player except for the one that keeps the camera locked in place 😔

**Comment by Kmc2000** [comment]
Use the unfuck_overmap() proc in a pinch

**Comment by Kmc2000** [comment]
Travis is failing due to that call()() usage.

I'd just use unfuck_overmap()

**Comment by Bokkiewokkie** [comment]
This should be completely finished now.

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
