### PR TITLE
Adds music attribution into the code comments for fleets & star systems.

### PR DESCRIPTION
**Pull request by athena413**
## About The Pull Request

Changes zero gameplay.
Puts comments beside each audio cue link telling the viewer what song it is and where's it from, so people can easily tell. 

## Why It's Good For The Game

Changes zero gameplay. Makes it easier for people to look at the tunes that are in the code,

## Changelog
:cl:
add: Added comments
del: Deleted FTL13
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Why is this necessary? The links can just be followed.

**Comment by athena413** [comment]
> 
> 
> Why is this necessary? The links can just be followed.

it isn't, but it's nice to have. for example, if i'm on a mobile device and can't remember exactly what song it was and i certainly don't want to use mobile website youtube

it doesn't harm anything but it can do a little bit of good. i'll personally fix any merge conflicts that come up.

**Comment by Karmic-Skink** [comment]
> > Why is this necessary? The links can just be followed.
> 
> it isn't, but it's nice to have. for example, if i'm on a mobile device and can't remember exactly what song it was and i certainly don't want to use mobile website youtube
> 
> it doesn't harm anything but it can do a little bit of good. i'll personally fix any merge conflicts that come up.

That really isn't the intention of code comments. A better idea would be to compile a master list somewhere else, such as text file.

**Comment by TheFakeElon** [comment]
Somewhat unrelated but music files should be downloaded, otherwise it's just putting needless stress on the server.

If it's of any concern, this is a copyright violation. Github could technically nuke the repo for this. I would _**highly**_ recommend keeping all non-licensed (to NSV) music server side

**Comment by Karmic-Skink** [comment]
> Somewhat unrelated but music files should be downloaded, otherwise it's just putting needless stress on the server.
> 
> Also, if it's of any concern, this is a copyright violation. Github could technically nuke the repo for this. I would _**highly**_ recommend keeping all non-licensed (to NSV) music server side

Unfortunate legacy of the previous project lead, I definitely would like to remove all copyright volitions from the code and hostbox.

**Pull request closed without merging**
