### PR TITLE
starsystem change - Dolos-B-Gone

### PR DESCRIPTION
**Pull request by Ansome101**
## About The Pull Request
Sets Dolos as "hidden" innately in the starsystem subsystem, preventing access without admin intervention.

## Why It's Good For The Game
Dolos was designed to be an incredibly difficult sector, which with our recent release has severely lost its edge due to shield technology, new strategies regarding MAC cannons, and excessive attempts by players leading it to be far less special and instead incredibly common in the gameplay loop. This PR disables Dolos to prevent crews from doing "Dolos runs" and allowing admins to once again use it for events or other theatrics at their leisure. It also helps to prevent 3+ hour rounds which have unfortunately continued after our initial attempts to stop them with the Armada.

## Changelog
:cl:
tweak: Set Dolo's hidden value to "TRUE"
/:cl:

### CODE REVIEW

**Comment by ta3370** [comment]
Ansome 2020 for returning it to the wormhole-based system it was meant to be.

**Comment by Ansome101** [comment]
SIDENOTE: It is technically possible for wormholes to allow access into Dolos. However, this requires the players to find one of several wormholes that spawn each round, located in a random sector, and enter it. It's a possibility, but one I'll allow - consider it a reward or a punishment for being curious. Depends on how you look at it.

**Comment by SharkeeByond** [comment]
> Dolos was designed to be an incredibly difficult sector, which with our recent release has severely lost its edge due to shield technology, new strategies regarding MAC cannons, and excessive attempts by players leading it to be far less special and instead incredibly common in the gameplay loop.

Why don't you just nerf MAC cannons or make Dolos more tanky and difficult?

**Comment by Ansome101** [comment]
> > Dolos was designed to be an incredibly difficult sector, which with our recent release has severely lost its edge due to shield technology, new strategies regarding MAC cannons, and excessive attempts by players leading it to be far less special and instead incredibly common in the gameplay loop.
> 
> Why don't you just nerf MAC cannons or make Dolos more tanky and difficult? Maybe add something new to counter-act the shields?

If we do that, the problem remains - Dolos is incredibly overdone. It could certainly use some retooling, as could the Fist of Sol, but for the time being the number one thing hurting Dolos is its mystique and danger vanishing due to rampant "Dolos runs".

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
