### PR TITLE
Adds Mining Shuttle Areas and Template

### PR DESCRIPTION
**Pull request by Vasily2013**
## About The Pull Request

This PR creates a mining shuttle capable of being used by coders later in the development process to enable ship mining operations rather than the stupid Idon'tknow whatever we have now. 

## Why It's Good For The Game

Mining is fun

## Changelog
:cl:
add: new map and areas for mining
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Please shrink the DMM down to the rectangle size of the shuttle.

**Comment by Vasily2013** [comment]
> Please shrink the DMM down to the rectangle size of the shuttle.

completed as requested.

**Comment by Vasily2013** [comment]
> Please use the template_noop for area and space where it is not specifically required as this reduces on load time of the ruins themselves as it skips making those turfs and areas. (This can save a lot of time)

I am aware of the template noop system, and highly suggest that in the future before offering reviews of Pull Requests that you coordinate with the author, as in this case there are some maps that are intended for use now, while others are still WIP.

**Comment by Jalleo** [comment]
Thats fine. I was merely stating it here so once its ready to merge the reviewer can confirm it is done for the maps just encase its accidentally forgotten.

**Pull request merged**
