### PR TITLE
Boardable Carriers 2

### PR DESCRIPTION
**Pull request by Omppusolttu**
## About The Pull Request

This PR gives carriers a boarding map. 

carrier

## Why It's Good For The Game

More boarding maps are useful for now.

## Changelog
:cl:
add: Carriers are now boardable.
/:cl:

### CODE REVIEW

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
I don't mind if you do or don't have an atmospherics system aboard, but please don't go half of one, half of the other. 

Additionally, there are multiple cable junctions that don't connect. If these are intentional that's fine, just wanted to make sure you're aware of them.

**Comment by Omppusolttu** [comment]
> I don't mind if you do or don't have an atmospherics system aboard, but please don't go half of one, half of the other.
> 
> Additionally, there are multiple cable junctions that don't connect. If these are intentional that's fine, just wanted to make sure you're aware of them.

Atmos system only exists for the SD, the cables are there for decoration since it's all an area that has infinite power.

**Review by Vasily2013 — APPROVED** [review]
image

**Comment by Vasily2013** [comment]
Covert said there weren't any major conceivable issues.

**Pull request merged**
