### PR TITLE
NSV Pegasus - The battleship

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

Titanwerks special project -304: Pegasus

Class: Atlantia class battlestar
Tonnage: 3,205,000
Point defense systems: 
-Octa-fed multi-vectored point defense cannon.
-Tri battery multi-target flak (with IFF identification to ensure its nukes hit the mark)
Primary armament:
-2 radial MAC cannon
-2 frontal railguns
-3 torpedo tubes, 8 thermonuclear warheads as standard
Secondary armament:
-Point defense cannon
-2 batteries of 6 "NT-BSG" dual bore gauss turrets
-Offensive flak
Notable features:
-Two inbuilt munitions factory areas, with one of them accessible by security as a gulag
-Inbuilt radiation bunker for non-essential crew
-Experimental ultra high yield stormdrive / TEG setup.

## Why It's Good For The Game

This PR adds in a brand new ship to fill a slot that was left open by the departure of the Galactica. 
Pegasus is an out and out battleship and flying her feels exactly that way. Armed with an excessive amount of guns, maneuverability is sacrified for raw power. In order to stay alive, Pegasus is armed with the unique ability to target up to _3_ enemy ships with flak at once, allowing for true area denial.

That being said, this is also the return of the NSV flying brick. To say that Pegasus handles poorly is an understatement. Clever usage of boost and ESPECIALLY kinetic turns will mean the difference between you ending up dead, or you destroying the opposition.

This ship is an out and out highpop map, and its job slots have been changed around to suit. Expect munitions tech mania on this beast.

## Changelog
:cl: Kmc2000
add: Added NSV Pegasus, a huge battleship with an excessive amount of weapons.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
fat

**Comment by Cenrus** [comment]
- [ ] tech storage apc not wired up
- [ ] bridge no Requests console

**Comment by Koekiegast** [comment]
The n2o tank isn't connected to the feul mixing line and atleast the particle accelerator room and the engineering break room are  open to the public

**Comment by Koekiegast** [comment]
The airlocks cycle to interior very slowly, yes there was enough pressure in distro.

**Comment by PowerfulBacon** [comment]
By biggest gripes with cargo is that the ship only has 2 tiles of space from the input to the output and there isn't enough space to build conveyor belts and automate the crates, maybe if cargo took some space above slightly and the ship was rotated 90 degrees there would be more space for fun automation thingies.
Areas could use a few more signs since there are a lot of deck 1 and deck 2 signs, but not a lot of departmental signs.
Maintenance is huge, but it feels so empty because there is a lack of things like maint loot in the crates so no floor pills, I think there should be more maint loot spawners around.
Also the disposals can be a little fucky wucky sometimes, the first round I played the disposals was broken, but that was fixed and the second our pacakges were not getting to their destination (Although this might have been because an engineer was breaking disposals, so not really an issue with the map but I'll try another round just to be sure)

**Comment by ikalpo** [comment]
science has no bio bags (ARGH, I NEED A BIO BAG!)

**Comment by DrSirKnight** [comment]
Nuclear silo has multiple air alarms for the same area
Locations that are missing cameras / need more cameras:
Both Gauss bays
Munitions sweat shop
Hallways outside of the gauss bays
Hallway outside of cargo
Cargo bay 
Hallway outside of lawyers office
CIC doors
Bar (The bar APC is in static so you can't use it as AI)

**Comment by Vasily2013** [comment]
> Nuclear silo has multiple air alarms for the same area

This isn't actually a problem. The only multiple thing in the same area problem is caused by APC's.

**Review by Jalleo — CHANGES_REQUESTED** [review]
More testing required.

**Comment by Cenrus** [comment]
no tool storage

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
- [x] Make sure you add fire lockers.
- [x] STOP RE-NAMING AREAS, JUST MAKE NEW ONES LIKE YOU'RE SUPPOSED TO!
- [x] Double check and make sure there's a tool storage on the map like Cenrus said.
- [x] Both cloning setups in medical are invalid at round-start. 
- [x] CMO's office has no shutters.
- [ ] CMO's locker is surprisingly hard to get to.

**Review by Kmc2000 — COMMENTED** [review]
Aerwhisp's offered to clean up any final issues with this. Keep it out of rotation until he's done there, I reckon.

**Comment by Vasily2013** [comment]
Have him make a PR to the branch then.

**Pull request merged**
