### PR TITLE
CC rework part 3

### PR DESCRIPTION
**Pull request by Absolutely-Steph**
## About The Pull Request
This reworks CC to be more civilian oriented.
additions include an airport style lobby, restaurant, giftshop, included hospital with triage area, checkpoint, emergency armoury, overhauled access/hallways, seperate hallways for civvilian and official use, quarters for civilians/officials/heads/admirals, and many smaller additions and overhauls.

Follow-on from https://github.com/BeeStation/NSV13/pull/1678

## Why It's Good For The Game
The old CC is simply a big arena for people to eotrg, this gives people things to do and RP. it also enhances the spaces used to prepare events marginally.

## Changelog
:cl:
tweak: tweaked CC
/:cl:

### CODE REVIEW

**Comment by ta3370** [comment]
Optionally, Pods could link through (or even better around) Thunderdome Admin instead of Security Checkpoint Smoking/Break table, would still need shutters, and should not link both, just one option or the other.

**Comment by Absolutely-Steph** [comment]
> ERT to Thunderdome shutter starts open? Why?
> 
> Brain Center of CC still has no space or anything gapping it's windows from an Airport Cafeteria, and should have some privacy shutters.
> 
> Deathsquad Shutter Button should be in Brain Center and/or Admirals Office instead of the desk.
> 
> Medbay is as far from the shuttle as simi-publicly possible for some reason.
> 
> Thunderdome Observation needs shutters to it's doors.
> 
> Security Checkpoint needs privacy/lockdown shutters on the windows.
> 
> Podbays are both not through security checkpoint, and have no lockdown method.
> 
> Are the middle dorms supposed to be Officials or for Airport usage? Could put medbay there, perhaps with a separate small triage accessible outside the secure area at the south of the dock/where the hallway above pods is.
> 
> Bar needs some public windoors or something of the sort sectioning behind the bartable to the common area, at the moment it feels a bit awkward open like that.

the next time you write something like this, please use the fancy tickboxes so i can show what i've done yet

**Comment by Absolutely-Steph** [comment]
I have:
- rerouted podbay and backupshuttle through the customs checkpoint
- added a shutter to the customs checkpoint
- added writing supplies to a bunch of places
- added shutters to the thunderdome entrance
- moved the emergency armoury button to the central control
- added railings and privacy shutters to central control
- replaced some of the fancy seating in the pod hallway with a warehouse
- Switched places of the officers lounge and medbay, added a triage area facing the shuttledock, sectioned off with shutters and CC doors.

**Comment by Vasily2013** [comment]
Remove the door circled in blue and replace it with an indestructible variant. If the admin needs that level of heavy firepower then it can be opened up by the admin using build mode.
image

**Comment by Vasily2013** [comment]
should be at least good for test merge

**Comment by Absolutely-Steph** [comment]
does this mean i can finally undraft it?

**Review by Bokkiewokkie — COMMENTED** [review]
So I've finally made some time to review this proposed Centcom rework. I will be comparing it to the original Centcom map (from Beestation) and the goals noted down on your original PR.

After walking around the map, and looking over it in a map editor, I can say that **this map seems to have failed in its attempts to improve upon the original Centcom map**.

Now I took a lot of notes, and am willing to share them when I have more time to properly explain them, but the main ones are:
- Your original PR stated you wouldn't touch certain areas of the map, but you have decided to change parts of these anyways (Some of the thunderdome's admin areas have become completely inaccessible for non-ghosted admins, the ERT areas have been modified heavily, the drop pod bays' hallway was overhauled for seemingly no reason, and you changed the floors in all of these places 💢)
- Your PR stated the current Centcom map is too hard to navigate (which I already find quite hard to believe), but your map is more confusing and harder to nagivate (as an admiral or CC intern) and seems to have a lot of extra (dead-ended) hallways which lack any indication of where they lead. Compared to the old Centcom map, which had a plus-shaped layout and admin/cc staff corridors next to civilian ones, and a courtroom next to its security area, this is much worse.
- The map itself looks a lot less friendly compared to the original one, featuring a massive security checkpoint front and center when you arrive, and still somehow seems to have less actual security measures (the security checkpoint does not have a desk to the east or west) than the original map, which featured two small customs desks, one of which controlled a relevant checkpoint and was accessible to CC staff from the main platform.
- Lastly, me and other staff have requested several things be done to ensure the map is of high enough quality, but several of these requests seem to have been ignored. If you were attempting to keep the map of the same size of the original, you've failed, since this version is actually _larger_ than the original, and still somehow lacking certain critical components (the removal of the courtroom, which you originally advertised as a feature, is not warranted at all)

For this reason I will not accept the map unless it gets a full redesign, and close the PR.
I hope you did learn some things about mapping while working on this, and suggest you try to practice with making (Centcom) map changes upstream (or on tg) before trying to work on Centcom (on NSV) again.

**Pull request closed without merging**
