### PR TITLE
Adds the black skirt and maid outfit to the torp shop

### PR DESCRIPTION
**Pull request by DrSirKnight**
## About The Pull Request

Adds the black skirt and maid outfit to the torp shop

## Why It's Good For The Game

Clothing variety is good

</details>

## Changelog
:cl:
add: Added a maid outfit to the torp shop
add: Added the black skirt to the torp shop
fix: Fixes suitbox slowdown not being removed for certain occasions
/:cl:

### CODE REVIEW

**Review by Kmc2000 — CHANGES_REQUESTED** [review]
🤨

**Review by Bokkiewokkie — DISMISSED** [review]
Essential navy equipment

**Comment by DrSirKnight** [comment]
I added a fix to the suitbox not removing the slowdown when it's made into cardboard (you will be stuck with the slowdown forever if you do that), someone should probably port the fix over to beestation as it's likely an issue for them aswell

**Comment by DrSirKnight** [comment]
> I added a fix to the suitbox not removing the slowdown when it's made into cardboard (you will be stuck with the slowdown forever if you do that), someone should probably port the fix over to beestation as it's likely an issue for them aswell

THESE THINGS ARE TERRIBLE, I added another fix related to them not removing slowdown when put into disposals, I need a more experienced coder to look over this and see if there's a better way to go about removing the slowdown

**Comment by DeltaFire15** [comment]
Doesn't dropped() fire after dropping the item so the check for if the user is holding it always ends up false? Don't exactly remember the item drop pipeline, will have to check when I'm back somewhere I can codedive.

**Review by Bokkiewokkie — APPROVED** [review]

**Pull request merged**
