### PR TITLE
SOP book update (but more of a chad)

### PR DESCRIPTION
**Pull request by GoatMonarch**
## About The Pull Request
This branch in essence is the same as #1201 in that we're moving the icon sprites to the nsv specific folder. But we're not removing the puce book like a total HACK.

I decided to just merge the sprite changes from #1201 into this PR. Now there's a compromise.
**How the hell was a book cover one of our most controversial PRs yet?**

## Why It's Better For The Game
Puce book is still big funny.

## Changelog
:cl:
tweak: Sop manual icons are now moved to the nsv specific folder
add: Sop manuals for muni, now with two covers!
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
You have dirty changes.

**Comment by GoatMonarch** [comment]
> You have dirty changes.

Frick I'll just redo it from the master.

**Comment by GoatMonarch** [comment]
There we go, ought to be clean now.

**Comment by Karmic-Skink** [comment]
You should spend that energy on destroying the crew's over reliance on stimflesh or something like that.

**Comment by GoatMonarch** [comment]
> You should spend that energy on destroying the crew's over reliance on stimflesh or something like that.

Coders only code grudge stuff they don't play. As a clown I use stimflesh alot. Instead I will just nerf lizard's sex apeal by giving them a chastity belt.

**Comment by Karmic-Skink** [comment]
> > You should spend that energy on destroying the crew's over reliance on stimflesh or something like that.
> 
> Coders only code grudge stuff they don't play. As a clown I use stimflesh alot. Instead I will just nerf lizard's sex apeal by giving them a chastity belt.

Yeah because I totally play for the ERP, right?

**Comment by GoatMonarch** [comment]
> > > You should spend that energy on destroying the crew's over reliance on stimflesh or something like that.
> > 
> > 
> > Coders only code grudge stuff they don't play. As a clown I use stimflesh alot. Instead I will just nerf lizard's sex apeal by giving them a chastity belt.
> 
> Yeah because I totally play for the ERP, right?

No, I do. I just think the lizards have it too easy.

**Comment by GoatMonarch** [comment]
Bless the ability to change files on a PR if you don't have any github software.

**Review by Jalleo — APPROVED** [review]
I will let Kmc decide which to merge.

**Pull request merged**
