### PR TITLE
New Map: NSV Gladius

### PR DESCRIPTION
**Pull request by Cenrus**
Introduces a new map called the NSV Gladius, for mid-to-high populations. 

- Feature complete as possible
- Many amneities for the crew so that there's more to do during combat downtime. 
- Maintenance was taken into consideration when designing the layout, so all departments have plenty of access to it. 
- Cargo is connected to munitions with a freight elevator to make cooperation easier and delivering supplies faster. 
- The hangar bay, instead of using launch tubes, uses a launch platform. This should help pilots launch without the help of an ATC if nobody signed up to be one.
- Cargo ship docks on the exterior rather than the interior, enjoy the space.
- Corporate Stateroom, an idea ~~stolen~~ borrowed from the elevator ship. It's only accessible to those with Centcom access and should lead to some interesting interactions between CentCom and the staff.
- Gauss guns can be accessed from an airlock and have public access
- Pool in dorms, have fun
- Stairs and a turbolift connecting the decks together, with the odd ladder in maintenance. there are also ladders on the exterior hull plates so that navigating it isn't a nightmare
- Hydroponics connected to the kitchen so that the chef of the botanists can make food if there's no assistance at hand
- RD Server room has a bit of extra space to build more servers
- A Psychology office, I know we don't have a proper Psychologist job here but I included it for roleplay (or antagonist) purposes
- AI Has a minisat on the outer hull near the bridge

map-deck2
map-deck1

:cl: Cenrus with help from bokkiewokkie & KMC
add: The NSV Gladius, a robust all-round ship for mid to high populations!
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
NEW MAP NEW MAP

Got screenshots?

**Comment by Cenrus** [comment]
Turns out mapdiffbot isn't working (No change there) give me a minute or two

**Comment by Ansome101** [comment]
Looking good! Reminds me of the Aetherwhisp in the shape a bit, but regardless I like the design. You mentioned that pilots can bypass using the magcats essentially if no ATC is present, but do you believe this might make people ignore a present ATC as they can bypass their role regardless? Also, I noticed you used random maint but put normal plating under it. For random maint to work properly you need to put /turf/template_noop as the floor (see Aetherwhisp). Otherwise, I really like it!

**Comment by Cenrus** [comment]
Turf passthrough added to maintenance rooms, as for the ATC it seems that our pilots are well behaved and tend to follow their instructions rather than dry launching themselves after FTL. The same system is used on the Tycoon and it's proven to work

**Comment by Bokkiewokkie** [comment]
The map looks really cool! Though the engine room doesn't make a lot of sense to me:
Right now it has a stormdrive with no pipes (good luck figuring out what side is the input without looking at code) and there's no engine that starts connected roundstart, which delays the startup. And looking at the size of the ship 4 SMES units doesn't seem to be enough to keep the ship powered until it's done being set up (Keep in mind they also have to make an output pipe).
The TEG also seems like an odd choice to me because it's not one of our main engines (and has nerfed power generation because of this) and is also buildable with the circuit printer fairly early on in the round (First engineering tech), so I don't really see the need to put one down if it isn't connected to anything.
The FUEL rods are also out of place as they're used in the RBMK reactor which isn't present (Unless mapdiffbot doesn't see it) and the stormdrive uses control rods which are locked in the storage only openable by the CE. (no CE = no reactor)
Other than that I saw this bit of piping which (doesn't) lead into the reactor room.
image
It's probably better to put a few vents and scrubbers (including pipes) in the room as they most likely won't get in the way of anything and most engineers will probably not set them up which may lead to accidental asphyxiation or toxin inhalation.

The main changes I suggest is adding a RBMK reactor and moving the fuel rods somewhere near the bottom left side of the room (with a few pipes and gas pumps to indicate the direction of gas flow) , having the stormdrive start hooked up to the purple pipe (and a waste pipe of course), putting some wire at the Particle Accelerator, removing the TEG and gas canisters, making a pipe that leads the cooling loop inside, and adding at least a few vents to the room.
Thanks for coming to my TED talk about why the metal plating desert is a bit too deserted.

**Comment by Vexylius** [comment]
Medbay breakroom shutters need robo access to open/close

**Comment by Nightrealm** [comment]
the detective forensics room doesn't have any surgery tools

**Comment by Cenrus** [comment]
@Nightrealm There is a bag with tools in the brig infirmary, I don't want to give security too many surgical tools as they're not medical.

**Comment by Cenrus** [comment]
Known issues: 

- [ ] Elevators are a bit buggy, but usable in their current state.
- [ ] One departure airlock isn't configured roundstart, can't find a solution for this

**Comment by Vexylius** [comment]
Post round survey - people seem to like this map
image

**Comment by Koekiegast** [comment]
I have a few more problems: the t-comms network monitor console starts of with the null network instead of the tcommsat one, i coudn't find the decryption key, the smes units are insuficient to power the ship, which is problematic if you really need the cooling pumps of the rbmk to keep working, that leads me to the problem with that entire room, one apc and no dedicated smes unit is not a very good choice for both engines and the armor pump, the rbmk produces radiation so just having it open in the engine room that is often passes trough if only to control it isn't very wise, the control computers themselves are positioned a bit weird, too far apart to view them on one tile as a last point the smes outer two smes units don't apear to be wired correctly. And that's everything i found.

**Comment by Vexylius** [comment]
Also, stuff that is supposed to be inside the safe in the vault, is outside
image

**Comment by Cenrus** [comment]
> 
> 
> I have a few more problems: the t-comms network monitor console starts of with the null network instead of the tcommsat one, i coudn't find the decryption key, the smes units are insuficient to power the ship, which is problematic if you really need the cooling pumps of the rbmk to keep working, that leads me to the problem with that entire room, one apc and no dedicated smes unit is not a very good choice for both engines and the armor pump, the rbmk produces radiation so just having it open in the engine room that is often passes trough if only to control it isn't very wise, the control computers themselves are positioned a bit weird, too far apart to view them on one tile as a last point the smes outer two smes units don't apear to be wired correctly. And that's everything i found.

The key is under the lamp, here. Are you sure Poly didn't move it, or did someone else steal it?

https://gyazo.com/dbea1c9351f0253b601f705765fd9dff

**Comment by Vexylius** [comment]
Just checked, decryption key is there
image


> > I have a few more problems: the t-comms network monitor console starts of with the null network instead of the tcommsat one, i coudn't find the decryption key, the smes units are insuficient to power the ship, which is problematic if you really need the cooling pumps of the rbmk to keep working, that leads me to the problem with that entire room, one apc and no dedicated smes unit is not a very good choice for both engines and the armor pump, the rbmk produces radiation so just having it open in the engine room that is often passes trough if only to control it isn't very wise, the control computers themselves are positioned a bit weird, too far apart to view them on one tile as a last point the smes outer two smes units don't apear to be wired correctly. And that's everything i found.
> 
> The key is under the lamp, here. Are you sure Poly didn't move it, or did someone else steal it?
> 
> https://gyazo.com/dbea1c9351f0253b601f705765fd9dff

**Comment by Kmc2000** [comment]
The engine room kinda sucks, I'm gonna redo it :))

**Comment by Cenrus** [comment]
Okay big man, show me what you got.

**Comment by Karmic-Skink** [comment]
Might want a couple more SMESes in engineering given the size of the ship.

**Comment by Koekiegast** [comment]
> Just checked, decryption key is there
> image
> 
> > > I have a few more problems: the t-comms network monitor console starts of with the null network instead of the tcommsat one, i coudn't find the decryption key, the smes units are insuficient to power the ship, which is problematic if you really need the cooling pumps of the rbmk to keep working, that leads me to the problem with that entire room, one apc and no dedicated smes unit is not a very good choice for both engines and the armor pump, the rbmk produces radiation so just having it open in the engine room that is often passes trough if only to control it isn't very wise, the control computers themselves are positioned a bit weird, too far apart to view them on one tile as a last point the smes outer two smes units don't apear to be wired correctly. And that's everything i found.
> > 
> > 
> > The key is under the lamp, here. Are you sure Poly didn't move it, or did someone else steal it?
> > https://gyazo.com/dbea1c9351f0253b601f705765fd9dff

i probably just didn't see it then, but it could probably use a better spot than hidden under a lamp.

**Comment by Cenrus** [comment]
This map is ready for testing again now that I've implemented some desired features, and KMC found the power issue (the SMES units hate catwalks)

**Comment by MacBlaze1** [comment]
I recommend you add bypasses to all gases running along the Stormdrive moderator line, no competent engineer wants co2 in his stormdrive, otherwise I need to manually add bypasses and theres not alot of room, remove the plasma constrictor line that readds plasma, you dont need it, its pointless, and if you want it would be helpful to move the plasma to be the very first thing that you can mix, because its important to get an exact % of it for the SD.

**Comment by Karmic-Skink** [comment]
All of the APNPs start configured to the same quadrant.

**Review by Vasily2013 — DISMISSED** [review]
- [ ] The turbine room has no camera, not a huge deal breaker but one might not be amiss. 
- [ ] This freezer in atmos isn't connected.
image
- [ ] Roundstart Active Turfs in Tcomms
image
- [ ] Roundstart Active Turfs in the Server Room
image
- [ ] There seems to be a lack of intercoms in the hangar. 
- [ ] This airlock isn't instancing properly, this is likely due to the airlocks having more than one different adjacent area.
image
- [ ] Please put gas cannisters in the tanks so they're slightly easier to identify at a glance.
- [ ] I'd say flip the plasma and CO2 mixers here to allow finer control over the fuel percentage, but if you want to leave that up to in-round pipe management that's perfectly fine.
image

**Comment by Koekiegast** [comment]
The fact that plasma has to goo trough the sd mix before going to the constricters is a bit of a wierd choice and can cause issues, the t-comms smes unit doesn't start wired in, and it's set up to be wired to the main power wire. Also i still don't think it's such a good idea to have the rbmk, the armor pumps and the sd reliant on one apc.

**Review by Kmc2000 — APPROVED** [review]
Really nice map, well received. I'm looking forward to welcoming it to the pool

**Pull request merged**
