### PR TITLE
Resolve #416 (impossible mining bounties): Remove mining bounties

### LINKED ISSUE #416: Cargo impossible bounties
Cargo can have bones, Goliath hides and other lavaland specific loot as bounties while we have no lavaland on the codebase.

### PR DESCRIPTION
**Pull request by Tennessee116**
## About The Pull Request

This PR removes mining bounties from the code, that's literally it. Resolves #416. 

## Why It's Good For The Game

Bounties need to be complete able, as it allows cargo to purchase more things that would be useful and complete bounty completion bounties.

## Changelog
:cl: Tennessee116
del: Deleted mining bounties.
/:cl:

### CODE REVIEW

**Comment by Tennessee116** [comment]
> Deleting Mining.dm from the bounties is a destructive step and unnecessary.
> 
> Disabling the file via bounty.dm is a better solution, as those bounties may be reenabled at a later point.
> 
> Remember to add //NSV13 tags as these are changes to core files.

That'd just mean doing // to the code mentioning it, correct?

**Comment by Karmic-Skink** [comment]
> 
> That'd just mean doing // to the code mentioning it, correct?

Correct, where changes are made to base files, we need //NSV13 tags to easily locate them

**Comment by Tennessee116** [comment]
> > That'd just mean doing // to the code mentioning it, correct?
> 
> Correct, where changes are made to base files, we need //NSV13 tags to easily locate them

I mean in terms of disabling it.

**Comment by Karmic-Skink** [comment]
> I mean in terms of disabling it.

// for an individual line

/*
CODE
*/

For a block

**Comment by Tennessee116** [comment]
> > I mean in terms of disabling it.
> 
> // for an individual line
> 
> /*
> CODE
> */
> 
> For a block
Alright, I'll go ahead and disable it instead.

**Comment by Tennessee116** [comment]
I'm going to close this pull request and make a new one for disabling it instead of removing it.

**Pull request closed without merging**
