### PR TITLE
 Resprites the CC Official's uniform and adds a CC Official cloak. Gonna have a go at it again.

### PR DESCRIPTION
**Pull request by Bamhalazam**
## About The Pull Request:
Resprites the CC uniform. Adds a cloak.
(FRONT: https://cdn.discordapp.com/attachments/723875082295836722/780799861842247690/cc1.png)
(BACK: https://cdn.discordapp.com/attachments/723875082295836722/780799880078950440/cc2.png)

(SIDE: https://cdn.discordapp.com/attachments/723875082295836722/780799902271275038/cc3.png)
(CLOAK FRONT: https://cdn.discordapp.com/attachments/723875082295836722/780799950740389939/cc6.png)
(CLOAK BACK: https://cdn.discordapp.com/attachments/723875082295836722/780799927722049566/cc7.png)
(CLOAK SIDE: https://cdn.discordapp.com/attachments/723875082295836722/780800038384435220/cc9.png)
 

## Why It's Good For The Game

New sprites, updating it from the old 2000s stuff we had. Better palette, and maybe CC bureaucrats will get some love. As I've said, everyone can't be an admiral.

## Changelog
:cl:
add: Added new things
add: Added more things: Adds CC cloak.
tweak: tweaked a few things: Tweaked CC uni.
imageadd: added some icons and images: cloak.
code: changed some code: Added item, added the item to the CC Official spawnlist.
admin: messed with admin stuff: Changed CC uniform that only admemes can access
/:cl:

### CODE REVIEW

**Comment by Bamhalazam** [comment]
Someone said I corrupted the sprites with map files. I didn't. Look at changed files and commits where I removed it. Also Map Diff Renders. No modified maps. I rest my case.

**Comment by Kmc2000** [comment]
Very nice!

This is a pretty good improvement, and the cape's a nice touch.

**Comment by Bamhalazam** [comment]
bruh travis trying to take this PR out

**Comment by Bamhalazam** [comment]
@Kmc2000 can you do a manual review and PR approve because Travis redtexted a day ago when this was a draft and now is refusing to recheck.

**Pull request closed without merging**
