### PR TITLE
New map: NSV Eclipse

### PR DESCRIPTION
**Pull request by Ansome101**
## About The Pull Request
Adds one new map, the NSV Eclipse, which is suited for dead/low pop crews of a minimum 3, maximum 10.

## Why It's Good For The Game
At present our lowpop maps do not extend down enough to allow our core gameplay to continue at even a meager 3 players. Even on maps designed for lowpop such as the Jeppison, the game becomes stagnant at certain populations and devolves into the equivalent of a normal SS13 game, which we do not want. The Eclipse is my solution to the lowpop gameplay limit and will allow players to complete a patrol due to its limited departments, engineering, and nearly all-access doorways, meaning that there is no wrong job to pick on the Eclipse to get a patrol done - anyone can!

## Changelog
:cl:
add: Added the NSV Eclipse
config: Added the NSV Eclipse to the maps listing
/:cl:

Eclipsemap

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Interesting design  , but won't forcing the bridge staff to also go to asteroids so miners can pick them up create some issues with mining overall?

**Comment by Ansome101** [comment]
And it just works!

**Comment by Kmc2000** [comment]
This map lacks an:
observer_start
landmark

So observing behaves weirdly

**Comment by Kmc2000** [comment]
Overall this map seems pretty comfy! I like it

**Comment by theboy6545** [comment]
mmmmmmmmmmmmmmmmmmmmmmmmmmmm map

**Comment by Nebulacrity** [comment]
The silhouette of the whole thing is too blocky for my liking. Try making it less so, perhaps?
Other than that, the insides look fine.

**Review by Kmc2000 — APPROVED** [review]

**Comment by Ansome101** [comment]
We did it, gamers.

**Pull request merged**
