### PR TITLE
Hammerhead atmos 2

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

Replaces and upgrades (almost) all of atmos!
Also makes all the external walls of the ship Duranium 

## Changelog
:cl:
tweak: Gives the Hammerhead a new atmospherics wing.
/:cl:

### CODE REVIEW

**Comment by Vasily2013** [comment]
Merge conflicts are probably from here. https://github.com/BeeStation/NSV13/pull/901/files

**Comment by Bokkiewokkie** [comment]
oh yep hadn't noticed the merge conflicts I'll take a look at em

**Comment by Vasily2013** [comment]
image
There seems to be an L-bend piece of brown pipe that doesn't attach to anything, at least that's what it looks like in mapdifbot.

**Comment by Bokkiewokkie** [comment]
Haha yeah I had actually spotted that pipe before but I forgot to remove it

**Review by Vasily2013 — CHANGES_REQUESTED** [review]
- [ ] Some empty gas cannisters would be helpful for atmos techs, there only needs to be one or two.
- [ ] The mix to waste line should probably double back through the filter system to avoid gas loss, but this could also be seen as busy work.

Overall this is very good, it flows nicely and offers ease of use for engine mixing.

**Review by Vasily2013 — APPROVED** [review]
yis

**Pull request merged**
