### PR TITLE
"Better" ranks

### PR DESCRIPTION
**Pull request by Vasily2013**
## About The Pull Request

Makes a decent rank structure where all crew are granted the ranks that their positions warrant.

## Why It's Good For The Game

Because everyone deserves to receive credit for the ranks that they warrant.

## Changelog
:cl:
add: new set of ranks
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
While this is hilarious. These ranks are so totally robotic that as a non militaristically-inclined person, I wouldn't be able to tell much from them.

**Comment by covertcorvid** [comment]
actually, one request - make the filename not have spaces, use underscores or something instead

**Comment by covertcorvid** [comment]
(it seems rubbish because it's a joke)

**Comment by Vasily2013** [comment]
> While this is hilarious. These ranks are so totally robotic that as a non militaristically-inclined person, I wouldn't be able to tell much from them.

bigger number higher rank. Fairly simple with warrants.

**Comment by Vasily2013** [comment]
> This is actually rubbish. I want something with effort. If you do not do that by tomorrow I will close this PR. Just having CW and WO whatever seems rubbish.

this is about 80% memes

**Comment by francinum** [comment]
Good jape. It's entirely optional and not the default.

**Pull request closed without merging**
