### PR TITLE
Gender Based Drinks!

### PR DESCRIPTION
**Pull request by Bobbanz1**
## About The Pull Request
Adds Gender Fluid as a drink! 
Also adds Gender Bender as a drink!
This unique and gender confusing drink, known as Gender Fluid, can be made using the following reagents:
- Between The Sheets
- Sugar Rush
- The Manly Dorf

The drink Gender Bender can be made using the following reagents: 
- Gender Fluid
- Stabilizing Agent

Gender Fluid will flip the consumers gender as long as it's inside their body, _although with some unpleasant side-effects_, the second it leaves they'll revert back to their original gender.

Meanwhile Gender Bender will switch your gender one time upon entering your body.
Sprite Credit goes to Suno for making the glass sprite in the first place 

## Why It's Good For The Game
MORE DRINKS

## Changelog
:cl:
add: Added the drink called Gender Fluid!
add: Added the drink called Gender Bender!
/:cl:

### CODE REVIEW

**Comment by covertcorvid** [comment]
Wow, an actual way to fix accidental radstorm sex changes

**Comment by sunofang** [comment]
nice sprites. who made those again?

**Comment by Bobbanz1** [comment]
@sunofang 
> Sprite Credit goes to Suno for making the glass sprite in the first place

That guy

**Comment by sunofang** [comment]
question : how is this a vector for weirdness? like how do you use it in a weird way other than forcefeeding people.

**Comment by Bobbanz1** [comment]
> I'm going to need an actual "why is this good for the game" here considering NSV is not one of _those_ servers. "More drinks" doesn't do it here when the drinks in question are just vectors for weirdness.

It is a quote on quote “joke pr” made in response to the various times the word “Gender Fluid” had been brought up in the Discord over the past few days, usually followed by people commenting on what such a drink would do, the pr isn’t supposed to be test merged or merged and was made with the intent of seeing how long it would take before it inevitably was closed down. 

Given how it’s already lived past it’s expected lifetime and due to the emotional distress it caused some people, I’ve decided to close it since it doesn’t contribute anything of long term value, nor improvement, beyond two drinks that will be made twice and then forgotten by people.

**Pull request closed without merging**
