### PR TITLE
Gives the ATC access to sabres for search and rescue operations

### PR DESCRIPTION
**Pull request by RemervKeberb**
## About The Pull Request

Gives the ATC access to the utility Sabres
## Why It's Good For The Game

Giving the ATC transport pilot access to fly a Sabre would let them initiate search and rescue operations for their downed fighters. 

## Changelog
:cl:
tweak: Gave ATC roundstart Transport Pilot access

### CODE REVIEW

**Comment by RemervKeberb** [comment]
Just to clarify, the ATC doing these search and rescue ops is a good thing because it very often happens that you have no other fighter pilots left that you can call upon to do it instead. And even when there are, A downed pilot means you've just been in combat, the pilots are repairing, rearming and refueling while you go to rescue the downed one. Making it overall flow smoother during downtime.

**Comment by Karmic-Skink** [comment]
Seems like dereliction of duty to me.

**Comment by covertcorvid** [comment]
Maybe we can branch out their role ground side or something. Have them help with repair/reload/refuel and stuff.

**Comment by RemervKeberb** [comment]
Forgot the comment.
But yeah Paramedic's getting the tools needed for that makes a fair bit more sense.

**Pull request closed without merging**
