### PR TITLE
Security Balance: 2!

### PR DESCRIPTION
**Pull request by GoatMonarch**
## About The Pull Request
Hello! So I made an earlier PR [right over here](https://github.com/BeeStation/NSV13/pull/723)
But apparantly I can't "just throw money at the issue to solve it" so I went the opposite direction.

Officers no longer have a security area, causing them to be more onpar with antags.
Now security officers can read their surviving edge book, then run around disarm spamming people with their free 16TC item all round.

I also left the detective's officer for I like them guys.
Sec1
Sec2

## Why It's Good For The Game
Literally everybody thinks security is out of control with their free disarm strikes, of which makes their stunbaton obsulete.
With this change antags can do more antaging, other than just stealthily removing someone round start as fast as possible.

## Changelog
:cl:
del: deletes everything bad with security
balance: security are less broken
/:cl:

### CODE REVIEW

**Comment by GoatMonarch** [comment]
I only changed the maps that really matters. Mapper slaves will have to change their own maps to follow this new map standard.

**Comment by DrSirKnight** [comment]
good pr speed merge

**Comment by Demoxide** [comment]
i have never seen something more balanced than this, speed merge

**Comment by Bokkiewokkie** [comment]
can you add a catwalk for the detective to get to his office? I think this is ready for a testmerge otherwise, I'm interested to see what will happen when this is implemented!

**Comment by theboy6545** [comment]
speedmerge

**Pull request closed without merging**
