### PR TITLE
Disable antag tokens from the torp shop

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request
Antag tokens are both a reward for a significant action outside of standard gameplay, or as penance for active administrative incompetence.

They shouldn't be bought for ingame currency gained passively, even if it's a singular available.

## Changelog
:cl:
del: Legitimate antag tokens can no longer be bought in the torp shop
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
nobody is going to get them!

**Comment by BeloneX** [comment]
but why, it requires so much torps its impossible to get anyway, you would need to play for years to get it.

**Comment by ike709** [comment]
I don't think you realize exactly how long it takes to get that many metacoins, assuming you guys haven't increased the payouts. It's around 1000-1200 hours of living playtime, assuming they buy nothing else.

**Comment by Kmc2000** [comment]
Nah, it's a good meme

**Pull request closed without merging**
