### PR TITLE
Okay but what if you could just build constrictors and they'd connect to pipes

### LINKED ISSUE #342: Issues with Magnetic Constrictor construction
- Build a vertical pipe on layer 2 with the RPD, hold it in your active hand, and click the constrictor. The pipe will magically teleport onto your tile.

- Can't alt click to rotate constrictors like the examine text implies.

- Magnetic constrictors don't connect to nearby pipes when constructed

image

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
that would be cool right

fixes #342 

oh and you can also change the pipe layers for it and now you can't stack multiple constrictors on top of eachother because apparently you could.

suus operatur iuste

## Changelog

:cl:
fix: Magnetic Constrictors now properly connect to pipes when built
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Does this include proper pixelshifting to deal with the visual aspect of pipe layers?

**Comment by Jalleo** [comment]
Has there been any issues or is it good to merge @Kmc2000 ?

**Review by Jalleo — APPROVED** [review]
It appears okay my end. Only potential issue is having a way to change layers of built ones. Is there a way to change it?

**Comment by Bokkiewokkie** [comment]
> It appears okay my end. Only potential issue is having a way to change layers of built ones. Is there a way to change it?
You can change layers by hitting the circuit with a multitool but I was still working on implementing pixelshifting for the layers.

**Pull request merged**
