### PR TITLE
[Lag-b-gone] Offloads physics calculations to C++

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

Project Exmap aims to shift a load of heavy physics calculations to c++, which is far better suited for this sort of thing. Through the power of extools I've been able to shift most of the super heavy lifting off of BYOND, which results in the above image.

* Overmap physics calculation is now done in C++
* Fixed a load of jank with deleting overmaps, and the infamous "fighter pop" bug.
* Made a few optimisations to how the game processess collisions to even further reduce lag.
* Extreme overmap stress will no longer lock up the server

@francinum I'd appreciate your help setting up our own fork of extools, it's currently just sitting on my own personal fork.

## Why It's Good For The Game

(Extended info for those who are interested)

-Data is transferred between BYOND and EXMAP by passing the x & y coords of vectors, lists of vectors are represented as lists of x&y coordinates instead.
-EXMAP doesn't remove the need for vectors, but rather shifts the heavier collision detection elements away from BYOND, meaning the game doesn't throttle nearly as hard.

(Tl;dr)

Lag bad, lag be gone spray good.

Special thanks to ASD for answering my initial questions.

~~Anyone want to do a double dolos run?~~

## Changelog
:cl: Kmc2000
refactor: Overmap physics calculations have been moved to C++ via extools.
fix: Fighters should no longer mysteriously blow up after a delay
fix: Fixed some issues with overmaps failing to GC
fix: Massively reduced the cost of some physics calc.
fix: Heavy overmap combat will no longer freeze / lag the rest of the game.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
YES

**Comment by Demoxide** [comment]
who will give us the comedically exploding fighters now?!

**Comment by Kmc2000** [comment]
> who will give us the comedically exploding fighters now?!
> 
> also i just spotted the subtle armor change values

Fighters no longer get any “second wind” where your health snaps back up, so I’ve adjusted them accordingly.

**Comment by theboy6545** [comment]
He did it, the crazy bastard DID it

**Comment by Bastian0930** [comment]
you crazy ass bitch.

thank you for the hard work!

**Comment by Karmic-Skink** [comment]
This cinematic is a travesty.

**Comment by QAI-07** [comment]
he's only gone and done it

**Comment by SharkeeByond** [comment]
Kmc has premium codersocks

**Comment by theboy6545** [comment]
> :(

Kmc do you need a hug?

**Comment by SharkeeByond** [comment]
> > :(
> 
> Kmc do you need a hug?

He needs big chungus.

**Comment by francinum** [comment]
@Kmc2000 Where have you put the raw code of this?

**Comment by Kmc2000** [comment]
> @Kmc2000 Where have you put the raw code of this?

https://github.com/Kmc2000/extools

**Comment by ondrej008** [comment]
I'll look into optimizing things, namely:
- the fact the main loop for physics processing is O(n^2)
- why are roughly 10 thousand vector2ds created per second during a single Dolos fleet?
- potentially making ship projectiles their seperate thing and removing bullet casings (last memory dump I've seen, bullet casings and memory leaked bullets used about 10% total memory, though the memory dump tool is inaccurate)

**Comment by Jalleo** [comment]
That must be fixed before this is merged. https://github.com/BeeStation/NSV13/pull/1114

**Comment by Kmc2000** [comment]
It ain't perfect, but it's a start

**Comment by Kenionatus** [comment]
"the above image", which Discord now refuses to act as CDN for is
image

**Pull request merged**
