### PR TITLE
The Beebasening 2021

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
Merges BeeStation-Hornet as of March 19th into our codebase

## Why It's Good For The Game
Up to date code?

## Changelog
:cl:
code: Merged current Bee code
/:cl:

### CODE REVIEW

**Comment by covertcorvid** [comment]
@francinum I'm gonna need your expertise on whether we want any of the CI changes and such

**Comment by GoatMonarch** [comment]
Thanks Covertcovid, very cool.

**Comment by Kmc2000** [comment]
Thank you so much ❤️

**Comment by Jalleo** [comment]
Until this gets merged I am going to say we should have a freeze on all the other PR's.

**Comment by Kmc2000** [comment]
> Until this gets merged I am going to say we should have a freeze on all the other PR's.

Agreed

**Comment by Pontenerd** [comment]
This suggestion is most likely gonna cause someone to try rip my head off but might it be worth setting up an autopull not so some poor sap doesn't have to do this again in a few months?

**Comment by covertcorvid** [comment]
> 
> 
> This suggestion is most likely gonna cause someone to try rip my head off but might it be worth setting up an autopull not so some poor sap doesn't have to do this again in a few months?

Last time I asked this I was told we don't have enough maintainers to keep up with a mirror bot.

**Comment by AffectedArc07** [comment]
Get your shit together youre breaking the diffbots.

@Kmc2000 tell me when this PR is merged and ill unban bee. For now, its breaking several other services.

**Comment by Pontenerd** [comment]
> Get your shit together youre breaking the diffbots.
> 
> @Kmc2000 tell me when this PR is merged and ill unban bee. For now, its breaking several other services.
> 

Wait this PR is breaking ALL the diffbots?

**Comment by AffectedArc07** [comment]
> Wait this PR is breaking ALL the diffbots?

If it wasnt I wouldnt be whining

**Comment by Pontenerd** [comment]
> > Wait this PR is breaking ALL the diffbots?
> 
> If it wasnt I wouldnt be whining 

Comical

**Comment by covertcorvid** [comment]
Broken:
- Ammo rack GUI won't open, ORD console won't open
- External airlocks have a stray pixel
- Pool has no liquid?
- Triple check overmap armor values
Not totally broken but weird:
- Doors look terrible with no directions - new animation for dir 1 and 4, legacy for others
- Light monotiles are hideous
- Whispering into radios
- Payday too fast

**Comment by covertcorvid** [comment]
@Kmc2000 Alright, I fixed the two consoles, the fuel pool, the stray pixel on external airlocks, and made the doors use different animation based on direction

**Comment by covertcorvid** [comment]
crates
faction tab
squad tab

**Comment by covertcorvid** [comment]
- [ ] #1272 
- [ ] #1319 
- [ ] Fran approval because config changes
- [ ] Maptainer approval

**Comment by covertcorvid** [comment]
Obsoletes #499 by breaking double-wide airlocks enough to stop using them
Fixes #952  https://github.com/BeeStation/BeeStation-Hornet/pull/2875

**Review by Kmc2000 — APPROVED** [review]
Time to get us unbanned from mapdiff

**Pull request merged**
