### PR TITLE
updates ethereals to TG high demand high compensation dynamic

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

This PR changes Ethereals to be more like TG ethereals in which they drain and can push large amounts of power but also lose a lot of power per life tick.

## Why It's Good For The Game

Instead of Ethereals being a remain around the APC race, they act like a very bright flame, fast burning, and requiring a lot of fuel to keep going.

## Changelog
:cl:
balance: ethereals now lose a lot more power per life tick and also gain much more from power sources.
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Anything that is different from directly upstream and is in a core file (not nsv13) will need a //NSV13 tag.

**Comment by theboy6545** [comment]
Would this PR not be better off upstream?

**Comment by MacBlaze1** [comment]
> Would this PR not be better off upstream?

possibly, though I dont know much about bee species pr requirements

**Comment by Kmc2000** [comment]
Testmerge enstated.

Apologies for the delay in getting to this one.

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
