### PR TITLE
Post-Beebase Shrike Update

### PR DESCRIPTION
**Pull request by Karmic-Skink**
## About The Pull Request
This PR updates a number of minor aspects of the Shrike.
It also unintentionally invokes the greatest FTL13 callback ever. :)

I haven't as of yet changed any pipe placements, if anyone has suggestions, please add them below.

No this does not contain a chem dispenser for medical.

## Why It's Good For The Game
I dunno, it is impossible to please everyone.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

</details>

## Changelog
:cl:
add: Added a new type of beaker box
add: Added at least one large beaker to shrike medical
add: Added an additional pipette to shrike medical
add: Added 30u of Rezadone to shrike medical
tweak: Ensured the shrike medical lobby doors are glass for better visibility of the 4 banners
add: Added an emergency jettison system for the Supermatter Crystal on shrike
spriteadd: Added 3 new types of wider arrow'd guidelines
tweak: Reworked all shrike guidlines to use the newer multilayer system that is also more vibrant
add: Added Munitions guideline from arrivals to shrike
balance: The previous shrike captain's late night bender has been removed (no fun allowed)
balance: The shutters to the captain's cabin now start closed on shrike
add: Added MAA stamp to MAA's locker on shrike
/:cl:

### CODE REVIEW

**Comment by Bokkiewokkie** [comment]
Please specify you're adding to Shrike in the changelog

**Comment by Karmic-Skink** [comment]
The funny should be easy to mitigate if required.

**Review by Bokkiewokkie — CHANGES_REQUESTED** [review]
Add an XO stamp to their locker and it should be all good.

**Comment by Karmic-Skink** [comment]
> Add an XO stamp to their locker and it should be all good.

?

**Pull request merged**
