### PR TITLE
Makes HH distro and scrubbers not linked anymore

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

Fixes:
#1029 
#1032 
#1033 

## Changelog
There is no changelog 😐

### CODE REVIEW

**Comment by Vasily2013** [comment]
Wasn't this fixed in #956 and #957?

**Comment by Bokkiewokkie** [comment]
Yes, I might have accidentally overridden a few of those changes when resolving the merge conflict in #930, which would explain why they're back.

**Review by Vasily2013 — APPROVED** [review]
YEET

**Comment by francinum** [comment]
@Bokkiewokkie @Vasily2013 Please make sure any issues you mention you mention properly
You MUST prefix all issues with something akin to: closes #0000
Individually
You cannot group them like you did here. I've manually closed these issues.

**Pull request merged**
