### PR TITLE
Improves the RCL by making it a radial dial selection of kinds of wires

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

This PR makes the RCL use a Radial Dial upon attack_self or z in hotkey mode to select wires to then place around yourself.

image
image

## Why It's Good For The Game

Requested by veteran engineers as the old RCL is just walking and does not have as much complexity to it. This would allow for faster wiring while also allowing more choice.

## Changelog
:cl:
tweak: The RCL now has a radial dial menu open up when attack_self is called or in hotkey mode, Z, you can also use the action icon in the top left corner. This radial dial menu allows you to select different kinds of wiring to place next to you.
tweak: added the RCL to the engineering protolathe.
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
Not sure about the range boost on this, generally all the engineering tools are up close and personal for a reason.

**Comment by ta3370** [comment]
Keep it limited to Melee range and this would become a pretty good PR.
Could also be later improved with addition of a Next button radial for a set of knot directions. Even things such as the "diagonal turn" configurations (where it goes from say, bottom right to top right of tile), ect. But what the radial has already is plenty good for first iteration and 90% of use cases.

I just... REALLY disagree with the mystical "I can change wires distant from me and people won't even have a reasonable clue it's me" and just long-reach in general in SS13. Even spears don't have the non-thrown range you want to put on this.

**Comment by ta3370** [comment]
Keep it limited to Melee range and this would become a pretty good PR.
Could also be later improved with addition of a Next button radial for a set of knot directions. Even things such as the "diagonal turn" configurations (where it goes from say, bottom right to top right of tile), ect. But what the radial as you've made it already is plenty good for first iteration and 90% of use cases.

I just... REALLY disagree with the mystical "I can change wires distant from me and people won't even have a reasonable clue it's me" and just long-reach in general in SS13. Even spears don't have the non-thrown range you want to put on this.

**Comment by Jalleo** [comment]
This and diagonal movement would go very well together for diagonal hallways. Sadly we cant do diagonal walls. Its a good idea and I approve it to see how well the player interaction will be with it.

**Comment by Karmic-Skink** [comment]
Please add //NSV13 tags to any core files changed.

**Review by Kmc2000 — APPROVED** [review]
This is pretty nice

**Pull request merged**
