### PR TITLE
New Directional Signs

### PR DESCRIPTION
**Pull request by MayhemSailor**
## New (non-janky) Directional Signs

Adds the following directional signs:
- Bridge
- Cargo
- Engineering
- Evac
- Ladder
- Lift
- Medical
- Science
- Security
- Stairs
- ATC
- Hangar
- Munitions

PR4NSV_3

## Why It's Good For The Game

Sleeks the look of directional signs for easier reading and crew directions. The old signs were not removed in this PR due to being included on current maps.

## Changelog
:cl:

imageadd: added 10 new directional signs

/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
These are pretty nice, thanks!

**Comment by Jalleo** [comment]
Thats fine I didn't realize that.

**Comment by MayhemSailor** [comment]
Included the following:
- CAG
- Hangar
- Munitions

Updated OP to see icons

**Comment by MayhemSailor** [comment]
CAG has been replaced with ATC, see OP for icon.

**Pull request merged**
