### PR TITLE
gives atmos and engineers the same access

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

Gives atmos technicians what they're missing of engineers access, and gives engineers what they're missing of atmos' access.

## Why It's Good For The Game

This is a stepping stone on the path to combining the two jobs, and will serve as a stopgap to make them act more in tune.

## Changelog
:cl:
tweak: atmos technicians and engineers now have the same access.
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
I agree that this is an IC issue, and perhaps if people wanted to touch the atmos things for the atmos powered engines, they should be playing Atmos Tech?

**Comment by MacBlaze1** [comment]
> I agree that this is an IC issue, and perhaps if people wanted to touch the atmos things for the atmos powered engines, they should be playing Atmos Tech?

Oh you mean remove engineers atmos access? I think thats a bit regressive.

**Comment by MacBlaze1** [comment]
> Opinion, but I feel this is more of an IC issue. There are multiple ways to solve it ingame. You could ask the captain for access, ask them to hire an atmos tech, or spend 10 seconds bolting a few doors open. Engineers have the tools to break in anywhere, and they were probably going to test wires at roundstart anyway

Atmosians cant break in anywhere, and this was mainly for them, not for engineers

**Comment by badideaguy** [comment]
> > Opinion, but I feel this is more of an IC issue. There are multiple ways to solve it ingame. You could ask the captain for access, ask them to hire an atmos tech, or spend 10 seconds bolting a few doors open. Engineers have the tools to break in anywhere, and they were probably going to test wires at roundstart anyway
> 
> 
> 
> Atmosians cant break in anywhere, and this was mainly for them, not for engineers

That doesn't stop them, via yelling at the AI(or getting hacking tools)

**Comment by Jalleo** [comment]
I have made a vote in talkpoints to talk about merging the two roles concept wise. This PR is just a reference to that talkpoint. Please ensure any discussions about it overall is done in the development channel for focused feedback.

**Pull request closed without merging**
