### PR TITLE
MAA Hardsuit Sprite Update

### PR DESCRIPTION
**Pull request by SerynEngi**
## About The Pull Request

MAA Hardsuit- now with actual NSV sprite!

## Why It's Good For The Game

This removes the temporary sprite for the MAA hardsuit in favor of an actually custom-made one courtesy of BluHNT. Also speeds it up a bit because like the CE hardsuit, its made out of better materials.

## Testing Photographs and Procedure
<details>

MAA hardsuit preview jpeg

</details>

## Changelog
:cl: SerynEngi and BluHNT
add: Added new MAA hardsuit sprite
balance: made MAA hardsuit less weapon-resistant in exchange for more speed.
/:cl:

### CODE REVIEW

**Comment by BlueHNT** [comment]
birdmask

**Review by Bokkiewokkie — CHANGES_REQUESTED** [review]
Code and sprites look good, though since this is a hardsuit it has the ability to turn on a helmet light by default. I would like it if you included mob and item sprites for the helmet to visualize having it on or off (e.g. ERT helmet in image)
image

**Review by Bokkiewokkie — APPROVED** [review]
Lämp

**Comment by Chickenfarmer48** [comment]
Turning the light on when facing left shifts the helmet one pixel. Doesn't happen when facing any other direction.
image 
image

**Review by Bokkiewokkie — APPROVED** [review]
Very cool PR I definitely didn't work on this myself at the end there haha where did you get that idea

**Pull request merged**
