### PR TITLE
Removes a slightly uncool line from the Rubicon Crossing taunt list

### PR DESCRIPTION
**Pull request by athena413**
## About The Pull Request

Rubicon border defense has some cool lines for when you go to the system. One of them is "Defense force, stand ready!", which is the one I've removed.

## Why It's Good For The Game

The other ones are way cooler. If you have good suggestions for something to replace it I'll add it as a replacement.

## Changelog
:cl:
del: I have duct-taped a certain Syndicate captain's mouth shut, so he will no longer say "Defense force, stand ready!"
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
Why?

**Comment by FLME** [comment]
> 
> 
> Why?

"defense force, stand ready" is significantly less cool than the rest of the taunts they can do

**Comment by Pontenerd** [comment]
> 
> 
> > Why?
> 
> "defense force, stand ready" is significantly less cool than the rest of the taunts they can do

Understandable, have a nice day

**Comment by Bokkiewokkie** [comment]
That moment when merge conflict in a one line change

**Comment by FLME** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

i JUST left for vacation you shitter

**Comment by Karmic-Skink** [comment]
Yeah I don't really see the point on this PR tbh. Improve the line rather then removing it?

**Comment by athena413** [comment]
> Yeah I don't really see the point on this PR tbh. Improve the line rather then removing it?

i would 100 percent agree to improving the line but i dont know what to improve it with so if you have a good one please let me know

**Comment by athena413** [comment]
cant be assed

**Comment by RemervKeberb** [comment]
Uhh, uhh. "You've got everyone back at Sol believing in miracles, don't you? Lets show them why you shouldn't get your hopes up."

**Pull request closed without merging**
