### PR TITLE
Broadsides are Dead, Long Live Broadsides

### PR DESCRIPTION
**Pull request by BetaCentari**
## About The Pull Request
THIS IS A REHASH PR from #2182! PROBABLY FIXES PROBLEMS

**YOU FIRE PORT AND BROADSIDE BY CLICKING ON THE LEFT OR RIGHT SIDE OF THE SCREEN RESPECTIVELY**

Adds the SN "Suckerpunch" Broadside Cannons to NSV and to Snake-Class Vessels as well as Hammerhead-Class Vessels. 

Couldn't have done it without @Bobbanz1 and @Bokkiewokkie 
## Why It's Good For The Game
Adds new weapon variety and spices up tactics in flight maneuvers and munitions management. 

**_FIRE BROADSIDES!!_**

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

https://user-images.githubusercontent.com/17231562/201551821-f6eff3ca-f8ab-478e-b124-daf1430ce777.mp4

</details>

## Changelog
:cl:
add: Added SNBC (Space Naval Broadside Cannons)
add: Added Broadside Shell Packing Bench 
add: Added Ammunition for the SNBC
soundadd: Added broadside firing sound effect 
imageadd: Added sprites (animated!) for the SNBC and Bench
tweak: Adjusted bounds of Snake to appropriate levels of chonk
/:cl:

### CODE REVIEW

**Comment by Karmic-Skink** [comment]
In theory you should have just been able to force push to the correct hash, rather than needing a new PR. Shrug?

**Comment by BetaCentari** [comment]
> In theory you should have just been able to force push to the correct hash, rather than needing a new PR. Shrug?

Oh absolutely, I just didn't know you could do that or how for that matter.

**Review by Bokkiewokkie — APPROVED** [review]

**Comment by benbot16** [comment]
image
This feels slightly odd, considering they can be carried in one hand.
Also, it'd be nice if there was a way to pack the casings without having to open the new TGUI menu (altclick?), since sometimes you don't need it and just need to pack shells really quickly.

**Comment by BetaCentari** [comment]
> 
I SWORE I FIXED THIS FFS

**Comment by BetaCentari** [comment]
Fixed and Alt Click Functionality added

**Review by covertcorvid — APPROVED** [review]

**Pull request merged**
