### PR TITLE
Basepixels and Pixelshifting

### PR DESCRIPTION
**Pull request by BetaCentari**
## About The Pull Request
Ports pixelshifting and base pixels from a closed Beestation PR (Skyrat and TG respectively)

Ports: 
https://github.com/Skyrat-SS13/Skyrat-tg/pull/870
https://github.com/tgstation/tgstation/pull/54652

## Why It's Good For The Game
Adds more roleplay potential for exact positioning of player characters
Adds two new variables, base_pixel_x and base_pixel_y that refactors some pixel shifting code to support persistent shifts that usually gets reset by most animation and shifting procs. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
Leaning against a wall with the pixel shifting ability (Hold C+WASD, pixel shift hotkey may be unbound by default)
Capture

</details>

## Changelog
:cl:
add: Added pixel shifting
tweak: Tweaked a lot of animated pixel shifts
code: Added base_pixel_x 
code: Added base_pixel_y
refactor: refactored pixelshifting variables
/:cl:

### CODE REVIEW

**Comment by covertcorvid** [comment]
As far as I know this is working well. I'm torn between asking for NSV tags and not wanting to make you go through all of those xD

**Comment by BetaCentari** [comment]
> As far as I know this is working well. I'm torn between asking for NSV tags and not wanting to make you go through all of those xD

I didn't... do that did I. I'm a dense cookie, eff.... I can do it if you want me to.

**Review by Bokkiewokkie — CHANGES_REQUESTED** [review]
I won't require that you go through every pixel change to add them, but if you could at least add NSV tags to define files and things like atom and mob variables that would be great. Technically you could (or technically should) move variable, proc and other definitions to the /nsv/ folder as well.

**Review by covertcorvid — APPROVED** [review]

**Comment by covertcorvid** [comment]
Bokkie approved via discord

**Pull request merged**
