### PR TITLE
Modifies mining vendor item list

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
Removed lavaland-oriented items: regenerative core stabilizers, skeleton keys, minebot weatherproof upgrade, survival capsules <s>except the bar</s>.
Removed several combat-oriented items: jump boots, minebot armor upgrade, PKA damage and AOE upgrades.
Added jetpack and cryogenic fuel tank.

## Why It's Good For The Game
Makes items in the mining vendor more relevant to NSV mining. Can always put them back if we give miners more dangerous places to explore.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added jetpack and cryogenic fuel tank to the mining vendor.
del: Removed regen core stabilizer, skeleton key, minebot weatherproofing, most survival capsules, jump boots, minebot armor, and PKA damage and AOE upgrades from mining vendor.
/:cl:

### CODE REVIEW

**Review by Bokkiewokkie — APPROVED** [review]

**Comment by Lauwma** [comment]
I think the pka upgrades should stay because there's still simplemobs in some ruins

**Comment by Bobbanz1** [comment]
I gotta ask
How the fuck do they fit an entire cyrofuel tank inside that thing?

**Comment by covertcorvid** [comment]
> I gotta ask How the fuck do they fit an entire cyrofuel tank inside that thing?

This is a great question. I was just trying to come up with something relevant that would be worth the premium.

**Comment by williamcll** [comment]
Is PKA speed retained? Then it should still be fine.

Not sure about replacing jump boots with jetpacks though.

**Pull request merged**
