### PR TITLE
Adds safety checks for things that reference the global overmap list

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
How we keep getting nulls in there I don't know, but this will possibly make them mess things up less

## Why It's Good For The Game
Bugs bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
code: Added checks for nulls to every place we use the global overmap list
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Something something performance though..
There is only exactly two things that even do ops on the list (one add and one remove) so it should in theory not be too difficult to look for the root instead.

**Comment by covertcorvid** [comment]
> Something something performance though.. There is only exactly two things that even do ops on the list (one add and one remove) so it should in theory not be too difficult to look for the root instead.

You would think that it wouldn't be too difficult to find the problem, but since we already check to make sure we're not adding nulls to the list and everything is supposed to remove itself from the list during its Destroy (), you would be wrong

**Review by Bokkiewokkie — APPROVED** [review]
Surely this will be enough
It does feel a bit excessive to both have qdeleted checks and listclearnulls in there, but there's not too many jump_end calls so it's probably fine

**Comment by covertcorvid** [comment]
> Surely this will be enough It does feel a bit excessive to both have qdeleted checks and listclearnulls in there, but there's not too many jump_end calls so it's probably fine

Actually I should take the listclearnulls out so that we can see if DeltaFire's fix works!

**Comment by DeltaFire15** [comment]
> Actually I should take the listclearnulls out so that we can see if DeltaFire's fix works!

Just unTM this PR, handling add / del properly should resolve it entirely and if it shows up again, can just swap around testmerges.

**Pull request closed without merging**
