### PR TITLE
[MDB IGNORE] [IDB IGNORE] Updates the code again (beebase 2021-b)

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
Gets us the latest and greatest beecode

Overmap
- [x] Aim helper broke (can't drag)
- [x] Ship movement bad
- [x] Teleporting via sabres (area gets renamed but has same ref)
- [x] Boarding map didn't load

Munitions
- [x] is it intentional that you can’t change where you aim while holding down the trigger for PDC? (can't drag)
- [ ] deck guns can't find mobs_in_ship

Supercruise
- [x] Science requires discovery research
- [x] Disable explorer job
- [x] Custom shuttle is always *missing*
- [x] Science discovery point amounts are being weird

AI stuff
- [x] AI transceiver controls broken
- [ ] Solar panel controls reappear when not requesting them
- [x] alt clicking cryotube opens it and opens its control panel (should only open it)

TGUI
- [x] Reactor UI still won't auto-update
- [x] Headset interface no worky
- [x] muni consoles don’t update the display after you push the buttons
- [x] space background
- [ ] long delay? noticed on DRADIS

Atmos
- [x] I need to do something about fusion
- [x] Fastmos not working (MUST UPDATE CONFIG FOR ATMOS_EQUALIZE_ENABLED)
- [x] nukes no longer make fire?

Other
- [x] Announcement noise loud
- [x] ai_boarder on enemy ship spawned as a midshipman, was shot. also can't pathfind.
- [x] Disable jumpskirts
- [x] Engi radio not gold
- [x] SSeconomy not paying out
- [x] Atlas escape shuttle windows invisible

## Why It's Good For The Game
Approximately 7 months worth of updates and fixes and stuff

## Changelog
:cl:
code: updated code to BeeStation-Hornet baseline
tweak: put orbital mechanics shuttles back to the old shuttle interface instead
tweak: re-enabled manual firelock use without a crowbar
add: enabled monstermos in auxtools
server: BUILD.bat - make sure to upload PreCompile.bat to EventScripts
server: config flag ATMOS_EQUALIZE_ENABLED required for monstermos
server: Runs on 514.1569
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
dear god

**Comment by covertcorvid** [comment]
Overmap
- Aim helper broke
- Ship movement bad
- Teleporting via sabres
- Roci armor is NaN
- Boarding map didn't load
Munitions
- Ammo sorter runtimes
- is it intentional that you can’t change where you aim while holding down the trigger for PDC?
Supercruise
- Science requires discovery research
- Disable explorer job
- Custom shuttle is always *missing*
AI stuff
- AI can rotated barricade remotely
- AI can unlock a locker that is next to them, and gets too-far-away messages for all closet types
- AI transceiver controls broken
- AI cannot jump to Roci network
- Solar panel controls reappear when not requesting them
- Robot controls do not work
- alt clicking cryotube opens it and opens its control panel
- disposal unit engage and eject content buttion greyed out
- command computers  on atlas are orange eye in XO and captians opffice.
- could nto change alert status on comms cosnole.
Borg
- cannot control+direction to face direction, moves that direction instead
TGUI
- Reactor UI still won't auto-update
- Headset interface no worky
- muni consoles don’t update the display after you push the buttons
Atmos
- I need to do something about fusion
- Fastmos not working
Other
- Announcement noise loud

**Comment by Karmic-Skink** [comment]
Jumpskirts :(
We've lost our special engineering golden colour.
Nukes appeared to be just spreading some warm plasma around the ship.
Deck guns were unable to find mobs in ship.
The Atlas escape shuttle had invisible windows.
SSeconomy didn't appear to be allocating funds ever, but I'm not sure if that system changed when/how it does it payout (trying to get github to display the code is problematic). However manually calling the proc did function. Are we locked to cash from cargo only right now?

**Comment by Bobbanz1** [comment]
I was able to research science nodes that were above the current amount of discovery points. 
Following this, I discovered that the discovery points had ceased to be removed whenever something was researched, however general science points did still get removed. 

Example: Something demanded 10k Discovery points, I was able to research this node at 9k and it only removed 1k, following this I could research stuff without discovery points getting removed, so long as I had the required amount of General science points, scanning stuff with astrometrics still increased the amount of Discovery points available however nothing seemed to decrease the amount available.

**Comment by someone543** [comment]
FTL Nav console starmap has an NT logo instead of a space background
DRADIS console has a noticeable delay (Apparently most TGUIs have this delay)

**Review by Karmic-Skink — APPROVED** [review]
This needs to go in sooner rather than later.

We can fix anything later with hotfixes.

**Pull request merged**
